<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 sp1 (http://www.altova.com) by Bernd Eichinger (The World) -->
<wsdl:definitions xmlns:csw30-wsdl="http://www.opengis.net/cat/csw/3.0/wsdl"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
   targetNamespace="http://www.opengis.net/cat/csw/3.0/wsdl">
   <wsdl:import namespace="http://www.opengis.net/cat/csw/3.0/wsdl"
      location="./xml-interfaces.wsdl"/>
   <wsdl:documentation xmlns:dc="http://purl.org/dc/elements/1.1/">
      <dc:description>HTTP/1.1 protocol bindings for CSW interfaces.</dc:description>
      <dc:date>2012-11-26</dc:date>
      <dc:contributor>Dr. Uwe Voges, u.voges@conterra.de</dc:contributor>
   </wsdl:documentation>
   <wsdl:binding name="csw-GET" type="csw30-wsdl:cswDiscovery">
      <http:binding verb="GET"/>
      <wsdl:documentation>CSW interface bound to the HTTP/1.1 GET method.</wsdl:documentation>
      <wsdl:operation name="cswGetCapabilities">
         <http:operation location="GetCapabilities"/>
         <wsdl:input>
            <http:urlEncoded/>
         </wsdl:input>
         <wsdl:output>
            <mime:mimeXml/>
         </wsdl:output>
         <wsdl:fault name="ServiceExceptionReport">
            <soap:fault name="ServiceExceptionReport" use="literal"/>
         </wsdl:fault>
      </wsdl:operation>
      <wsdl:operation name="cswGetRecordById">
         <http:operation location="GetRecordById"/>
         <wsdl:input>
            <http:urlEncoded/>
         </wsdl:input>
         <wsdl:output>
            <mime:mimeXml/>
         </wsdl:output>
         <wsdl:fault name="ServiceExceptionReport">
            <soap:fault name="ServiceExceptionReport" use="literal"/>
         </wsdl:fault>
      </wsdl:operation>
      <wsdl:operation name="cswGetRecords">
         <http:operation location="GetRecords"/>
         <wsdl:input>
            <http:urlEncoded/>
         </wsdl:input>
         <wsdl:output>
            <mime:mimeXml/>
         </wsdl:output>
         <wsdl:fault name="ServiceExceptionReport">
            <soap:fault name="ServiceExceptionReport" use="literal"/>
         </wsdl:fault>
      </wsdl:operation>
      <wsdl:operation name="cswGetDomain">
         <http:operation location="GetDomain"/>
         <wsdl:input>
            <http:urlEncoded/>
         </wsdl:input>
         <wsdl:output>
            <mime:mimeXml/>
         </wsdl:output>
         <wsdl:fault name="ServiceExceptionReport">
            <soap:fault name="ServiceExceptionReport" use="literal"/>
         </wsdl:fault>
      </wsdl:operation>
   </wsdl:binding>
</wsdl:definitions>
