<DOCFLEX_TEMPLATE VER='1.19'>
CREATED='2004-06-21 01:50:00'
LAST_UPDATE='2014-07-05 20:02:57'
DESIGNER_TOOL='DocFlex SDK 1.x'
DESIGNER_LICENSE_TYPE='Filigris Works Team'
APP_ID='docflex-xml-wsdldoc'
APP_NAME='DocFlex/XML WSDLDoc'
APP_VER='1.0.b'
APP_AUTHOR='Copyright © 2014 Filigris Works, Leonid Rudy Softwareprodukte. All rights reserved.'
FEATURE_TYPE='pro'
TEMPLATE_TYPE='DocumentTemplate'
DSM_TYPE_ID='wsdldoc'
ROOT_ET='#DOCUMENTS'
<TEMPLATE_PARAMS>
	PARAM={
		param.name='$nsURI';
		param.title='Namespace URI';
		param.type='string';
	}
	PARAM={
		param.name='$resourceOutputDir';
		param.title='documentation resources directory';
		param.type='string';
	}
	PARAM={
		param.name='gen.doc';
		param.title='Generate Details';
		param.title.style.bold='true';
		param.group='true';
	}
	PARAM={
		param.name='gen.doc.sorting';
		param.title='Sorting';
		param.title.style.italic='true';
		param.group='true';
	}
	PARAM={
		param.name='gen.doc.sorting.wsdl.files';
		param.title='WSDL Files';
		param.title.style.italic='true';
		param.type='boolean';
	}
	PARAM={
		param.name='gen.doc.sorting.xsd.schemas';
		param.title='Schemas';
		param.title.style.italic='true';
		param.type='boolean';
	}
	PARAM={
		param.name='gen.doc.xsd.comp';
		param.title='XSD Components';
		param.title.style.bold='true';
		param.group='true';
		param.type='boolean';
	}
	PARAM={
		param.name='gen.doc.xsd.comp.element';
		param.title='Elements';
		param.group='true';
		param.type='boolean';
	}
	PARAM={
		param.name='gen.doc.xsd.comp.element.local';
		param.title='Local Elements';
		param.group='true';
		param.type='enum';
		param.enum.values='all;complexType;none';
	}
	PARAM={
		param.name='gen.doc.xsd.comp.element.local.unifyByType';
		param.title='Unify By Type';
		param.title.style.italic='true';
		param.type='boolean';
	}
	PARAM={
		param.name='nav';
		param.title='Navigation';
		param.title.style.bold='true';
		param.group='true';
	}
	PARAM={
		param.name='nav.indexFrame.namespace';
		param.title='Namespace';
		param.title.style.bold='true';
		param.group='true';
		param.type='boolean';
	}
	PARAM={
		param.name='nav.indexFrame.namespace.wsdl.files';
		param.title='WSDL Files';
		param.type='boolean';
	}
	PARAM={
		param.name='nav.indexFrame.namespace.wsdl.defs';
		param.title='WSDL Definitions';
		param.group='true';
		param.type='boolean';
	}
	PARAM={
		param.name='nav.indexFrame.namespace.wsdl.defs.sorting';
		param.title='Sorting';
		param.title.style.italic='true';
		param.type='boolean';
	}
	PARAM={
		param.name='nav.indexFrame.namespace.wsdl.defs.services';
		param.title='Services';
		param.type='boolean';
		param.defaultValue='true';
	}
	PARAM={
		param.name='nav.indexFrame.namespace.wsdl.defs.bindings';
		param.title='Bindings';
		param.type='boolean';
	}
	PARAM={
		param.name='nav.indexFrame.namespace.wsdl.defs.portTypes';
		param.title='Port Types';
		param.type='boolean';
	}
	PARAM={
		param.name='nav.indexFrame.namespace.wsdl.defs.messages';
		param.title='Messages';
		param.type='boolean';
	}
	PARAM={
		param.name='nav.indexFrame.namespace.xsd.schemas';
		param.title='Schemas';
		param.type='boolean';
	}
	PARAM={
		param.name='nav.indexFrame.namespace.xsd.comps';
		param.title='XSD Components';
		param.group='true';
		param.type='boolean';
	}
	PARAM={
		param.name='nav.indexFrame.namespace.xsd.comps.sorting';
		param.title='Sorting';
		param.title.style.italic='true';
		param.type='boolean';
	}
	PARAM={
		param.name='nav.indexFrame.namespace.xsd.comps.elements';
		param.title='Elements';
		param.group='true';
		param.type='boolean';
	}
	PARAM={
		param.name='nav.indexFrame.namespace.xsd.comps.elements.local';
		param.title='Local Elements';
		param.type='enum';
		param.enum.values='all;complexType;none';
		param.enum.displayValues='all;with complex type;none';
	}
	PARAM={
		param.name='nav.indexFrame.namespace.xsd.comps.complexTypes';
		param.title='Complex Types';
		param.type='boolean';
	}
	PARAM={
		param.name='nav.indexFrame.namespace.xsd.comps.simpleTypes';
		param.title='Simple Types';
		param.type='boolean';
	}
	PARAM={
		param.name='nav.indexFrame.namespace.xsd.comps.groups';
		param.title='Element Groups';
		param.type='boolean';
	}
	PARAM={
		param.name='nav.indexFrame.namespace.xsd.comps.attributes';
		param.title='Global Attributes';
		param.type='boolean';
	}
	PARAM={
		param.name='nav.indexFrame.namespace.xsd.comps.attributeGroups';
		param.title='Attribute Groups';
		param.type='boolean';
	}
	PARAM={
		param.name='show';
		param.title='Show';
		param.title.style.bold='true';
		param.group='true';
		param.group.defaultState='expanded';
	}
	PARAM={
		param.name='show.linkTitle';
		param.title='Link Titles (Tooltips)';
		param.type='boolean';
	}
	PARAM={
		param.name='show.localElementExt';
		param.title='Local Element Extensions';
		param.type='enum';
		param.enum.values='always;repeating;never';
	}
</TEMPLATE_PARAMS>
<STYLES>
	CHAR_STYLE={
		style.name='Default Paragraph Font';
		style.id='cs1';
		style.default='true';
	}
	PAR_STYLE={
		style.name='Frame Heading';
		style.id='s1';
		text.font.size='9';
		text.font.style.bold='true';
		par.margin.top='5.8';
		par.margin.bottom='2.5';
		par.option.nowrap='true';
	}
	PAR_STYLE={
		style.name='Frame Heading Note';
		style.id='s2';
		text.font.name='Tahoma';
		text.font.size='6';
		text.font.style.bold='true';
		par.margin.top='0';
		par.margin.bottom='3.3';
		par.option.nowrap='true';
	}
	PAR_STYLE={
		style.name='Frame Item';
		style.id='s3';
		text.font.size='9';
		par.option.nowrap='true';
	}
	PAR_STYLE={
		style.name='Frame Title';
		style.id='s4';
		text.font.name='Arial';
		text.font.size='9.5';
		text.font.style.bold='true';
		par.margin.bottom='5.8';
		par.option.nowrap='true';
	}
	PAR_STYLE={
		style.name='Frame TOC Heading';
		style.id='s5';
		text.font.name='Arial';
		text.font.size='7';
		text.font.style.bold='true';
		par.margin.bottom='1.7';
		par.option.nowrap='true';
	}
	PAR_STYLE={
		style.name='Frame TOC Item';
		style.id='s6';
		text.font.size='8';
		par.option.nowrap='true';
	}
	CHAR_STYLE={
		style.name='Hyperlink';
		style.id='cs2';
		text.decor.underline='true';
		text.color.foreground='#0000FF';
	}
	CHAR_STYLE={
		style.name='Name Modifier';
		style.id='cs3';
		text.font.name='Verdana';
		text.font.size='7';
		text.color.foreground='#B2B2B2';
	}
	PAR_STYLE={
		style.name='Normal';
		style.id='s7';
		style.default='true';
	}
	CHAR_STYLE={
		style.name='Underline';
		style.id='cs4';
		text.decor.underline='true';
	}
</STYLES>
FMT={
	doc.lengthUnits='pt';
}
<HTARGET>
	HKEYS={
		'getStringParam("$nsURI")';
		'"summary"';
	}
</HTARGET>
<ROOT>
	<AREA_SEC>
		DESCR='namespace URI'
		FMT={
			par.style='s4';
			par.option.nowrap='true';
		}
		<AREA>
			<CTRL_GROUP>
				<CTRLS>
					<DATA_CTRL>
						FORMULA='(nsURI = getStringParam("$nsURI")) != "" ? nsURI : "{no namespace}"'
						<DOC_HLINK>
							TITLE_EXPR='getBooleanParam("show.linkTitle")
?
  (nsURI = getStringParam("$nsURI")) != "" ?
    "Namespace {" + nsURI + "}" : "No Namespace"
: ""'
							TARGET_FRAME_EXPR='"detailFrame"'
							HKEYS={
								'getStringParam("$nsURI")';
								'"detail"';
							}
						</DOC_HLINK>
					</DATA_CTRL>
				</CTRLS>
			</CTRL_GROUP>
		</AREA>
	</AREA_SEC>
	<AREA_SEC>
		FMT={
			sec.outputStyle='table';
			table.cell.padding.both='3.3';
			table.bkgr.color='#F5F5F5';
			table.border.style='solid';
			table.border.color='#999999';
			table.option.borderStylesInHTML='true';
		}
		<AREA>
			<CTRL_GROUP>
				<CTRLS>
					<SS_CALL_CTRL>
						SS_NAME='TOC'
						FMT={
							ctrl.size.width='499.5';
							ctrl.size.height='17.3';
						}
					</SS_CALL_CTRL>
				</CTRLS>
			</CTRL_GROUP>
		</AREA>
	</AREA_SEC>
	<ELEMENT_ITER>
		DESCR='WSDL files targeting this namespace'
		COND='getBooleanParam("nav.indexFrame.namespace.wsdl.files")'
		TARGET_ET='wsdl:definitions'
		SCOPE='advanced-location-rules'
		RULES={
			'* -> {findElementsByKey ("namespaces", getParam("$nsURI"))}::wsdl:definitions';
		}
		SORTING='by-expr'
		SORTING_KEY={expr='getXMLDocument().getAttrStringValue("xmlName")',ascending}
		SORTING_COND='getBooleanParam("gen.doc.sorting.wsdl.files")'
		<BODY>
			<AREA_SEC>
				FMT={
					par.style='s3';
				}
				<AREA>
					<CTRL_GROUP>
						FMT={
							txtfl.delimiter.type='none';
						}
						<CTRLS>
							<IMAGE_CTRL>
								IMAGE_TYPE='file-image'
								FILE='../images/wsdl.png'
								OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
								FMT={
									image.alignment='bottom';
									image.padding.right='2.5';
								}
							</IMAGE_CTRL>
							<SS_CALL_CTRL>
								SS_NAME='WSDL Name'
							</SS_CALL_CTRL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
		</BODY>
		<HEADER>
			<AREA_SEC>
				FMT={
					par.style='s1';
				}
				<HTARGET>
					HKEYS={
						'getParam("$nsURI")';
						'"indexFrame"';
						'"wsdl-files"';
					}
				</HTARGET>
				<AREA>
					<CTRL_GROUP>
						<CTRLS>
							<PANEL>
								FMT={
									ctrl.size.width='177';
									ctrl.size.height='38.3';
									text.hlink.fmt='style';
									text.hlink.style='cs4';
									text.hlink.style.use='hover';
								}
								<DOC_HLINK>
									TITLE_EXPR='getBooleanParam("show.linkTitle") ? "see summary" : ""'
									TARGET_FRAME_EXPR='"detailFrame"'
									HKEYS={
										'getStringParam("$nsURI")';
										'"wsdl-file-summary"';
									}
								</DOC_HLINK>
								<AREA>
									<CTRL_GROUP>
										<CTRLS>
											<TEXT_CTRL>
												TEXT='WSDL Files'
											</TEXT_CTRL>
											<DATA_CTRL>
												FORMULA='"(" + iterator.numItems + ")"'
											</DATA_CTRL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</PANEL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
		</HEADER>
	</ELEMENT_ITER>
	<FOLDER>
		DESCR='WSDL definitions'
		COND='getBooleanParam("nav.indexFrame.namespace.wsdl.defs")'
		COLLAPSED
		<BODY>
			<ELEMENT_ITER>
				DESCR='list of services'
				COND='getBooleanParam("nav.indexFrame.namespace.wsdl.defs.services")'
				TARGET_ET='wsdl:service'
				SCOPE='advanced-location-rules'
				RULES={
					'* -> {findElementsByKey ("namespaces", getParam("$nsURI"))}::wsdl:definitions/wsdl:service';
				}
				SORTING='by-attr'
				SORTING_KEY={lpath='@name',ascending}
				SORTING_COND='getBooleanParam("nav.indexFrame.namespace.wsdl.defs.sorting")'
				<BODY>
					<AREA_SEC>
						FMT={
							par.style='s3';
						}
						<AREA>
							<CTRL_GROUP>
								FMT={
									txtfl.delimiter.type='none';
								}
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/service.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											image.alignment='bottom';
											image.padding.right='2.5';
										}
									</IMAGE_CTRL>
									<SS_CALL_CTRL>
										SS_NAME='WSDL Definition Name'
									</SS_CALL_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
				<HEADER>
					<AREA_SEC>
						FMT={
							par.style='s1';
						}
						<HTARGET>
							HKEYS={
								'getParam("$nsURI")';
								'"indexFrame"',required;
								'"services"';
							}
						</HTARGET>
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<PANEL>
										FMT={
											ctrl.size.width='162';
											ctrl.size.height='38.3';
											text.hlink.fmt='style';
											text.hlink.style='cs4';
											text.hlink.style.use='hover';
										}
										<DOC_HLINK>
											TITLE_EXPR='getBooleanParam("show.linkTitle") ? "see summary" : ""'
											TARGET_FRAME_EXPR='"detailFrame"'
											HKEYS={
												'getStringParam("$nsURI")';
												'"service-summary"';
											}
										</DOC_HLINK>
										<AREA>
											<CTRL_GROUP>
												<CTRLS>
													<TEXT_CTRL>
														TEXT='Services'
													</TEXT_CTRL>
													<DATA_CTRL>
														FORMULA='"(" + iterator.numItems + ")"'
													</DATA_CTRL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
			</ELEMENT_ITER>
			<ELEMENT_ITER>
				DESCR='list of bindings'
				COND='getBooleanParam("nav.indexFrame.namespace.wsdl.defs.bindings")'
				TARGET_ET='wsdl:binding'
				SCOPE='advanced-location-rules'
				RULES={
					'* -> {findElementsByKey ("namespaces", getParam("$nsURI"))}::wsdl:definitions/wsdl:binding';
				}
				SORTING='by-attr'
				SORTING_KEY={lpath='@name',ascending}
				SORTING_COND='getBooleanParam("nav.indexFrame.namespace.wsdl.defs.sorting")'
				<BODY>
					<AREA_SEC>
						FMT={
							par.style='s3';
						}
						<AREA>
							<CTRL_GROUP>
								FMT={
									txtfl.delimiter.type='none';
								}
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/binding.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											image.alignment='bottom';
											image.padding.right='2.5';
										}
									</IMAGE_CTRL>
									<SS_CALL_CTRL>
										SS_NAME='WSDL Definition Name'
									</SS_CALL_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
				<HEADER>
					<AREA_SEC>
						FMT={
							par.style='s1';
						}
						<HTARGET>
							HKEYS={
								'getParam("$nsURI")';
								'"indexFrame"',required;
								'"bindings"';
							}
						</HTARGET>
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<PANEL>
										FMT={
											ctrl.size.width='168';
											ctrl.size.height='38.3';
											text.hlink.fmt='style';
											text.hlink.style='cs4';
											text.hlink.style.use='hover';
										}
										<DOC_HLINK>
											TITLE_EXPR='getBooleanParam("show.linkTitle") ? "see summary" : ""'
											TARGET_FRAME_EXPR='"detailFrame"'
											HKEYS={
												'getStringParam("$nsURI")';
												'"binding-summary"';
											}
										</DOC_HLINK>
										<AREA>
											<CTRL_GROUP>
												<CTRLS>
													<TEXT_CTRL>
														TEXT='Bindings'
													</TEXT_CTRL>
													<DATA_CTRL>
														FORMULA='"(" + iterator.numItems + ")"'
													</DATA_CTRL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
			</ELEMENT_ITER>
			<ELEMENT_ITER>
				DESCR='list of port types'
				COND='getBooleanParam("nav.indexFrame.namespace.wsdl.defs.portTypes")'
				TARGET_ET='wsdl:portType'
				SCOPE='advanced-location-rules'
				RULES={
					'* -> {findElementsByKey ("namespaces", getParam("$nsURI"))}::wsdl:definitions/wsdl:portType';
				}
				SORTING='by-attr'
				SORTING_KEY={lpath='@name',ascending}
				SORTING_COND='getBooleanParam("nav.indexFrame.namespace.wsdl.defs.sorting")'
				<BODY>
					<AREA_SEC>
						FMT={
							par.style='s3';
						}
						<AREA>
							<CTRL_GROUP>
								FMT={
									txtfl.delimiter.type='none';
								}
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/portType.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											image.alignment='bottom';
											image.padding.right='2.5';
										}
									</IMAGE_CTRL>
									<SS_CALL_CTRL>
										SS_NAME='WSDL Definition Name'
									</SS_CALL_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
				<HEADER>
					<AREA_SEC>
						FMT={
							par.style='s1';
						}
						<HTARGET>
							HKEYS={
								'getParam("$nsURI")';
								'"indexFrame"',required;
								'"portTypes"';
							}
						</HTARGET>
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<PANEL>
										FMT={
											ctrl.size.width='171.8';
											ctrl.size.height='38.3';
											text.hlink.fmt='style';
											text.hlink.style='cs4';
											text.hlink.style.use='hover';
										}
										<DOC_HLINK>
											TITLE_EXPR='getBooleanParam("show.linkTitle") ? "see summary" : ""'
											TARGET_FRAME_EXPR='"detailFrame"'
											HKEYS={
												'getStringParam("$nsURI")';
												'"portType-summary"';
											}
										</DOC_HLINK>
										<AREA>
											<CTRL_GROUP>
												<CTRLS>
													<TEXT_CTRL>
														TEXT='Port Types'
													</TEXT_CTRL>
													<DATA_CTRL>
														FORMULA='"(" + iterator.numItems + ")"'
													</DATA_CTRL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
			</ELEMENT_ITER>
			<ELEMENT_ITER>
				DESCR='list of messages'
				COND='getBooleanParam("nav.indexFrame.namespace.wsdl.defs.messages")'
				TARGET_ET='wsdl:message'
				SCOPE='advanced-location-rules'
				RULES={
					'* -> {findElementsByKey ("namespaces", getParam("$nsURI"))}::wsdl:definitions/wsdl:message';
				}
				SORTING='by-attr'
				SORTING_KEY={lpath='@name',ascending}
				SORTING_COND='getBooleanParam("nav.indexFrame.namespace.wsdl.defs.sorting")'
				<BODY>
					<AREA_SEC>
						FMT={
							par.style='s3';
						}
						<AREA>
							<CTRL_GROUP>
								FMT={
									txtfl.delimiter.type='none';
								}
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/message.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											image.alignment='bottom';
											image.padding.right='2.5';
										}
									</IMAGE_CTRL>
									<SS_CALL_CTRL>
										SS_NAME='WSDL Definition Name'
									</SS_CALL_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
				<HEADER>
					<AREA_SEC>
						FMT={
							par.style='s1';
						}
						<HTARGET>
							HKEYS={
								'getParam("$nsURI")';
								'"indexFrame"',required;
								'"messages"';
							}
						</HTARGET>
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<PANEL>
										FMT={
											ctrl.size.width='168.8';
											ctrl.size.height='38.3';
											text.hlink.fmt='style';
											text.hlink.style='cs4';
											text.hlink.style.use='hover';
										}
										<DOC_HLINK>
											TITLE_EXPR='getBooleanParam("show.linkTitle") ? "see summary" : ""'
											TARGET_FRAME_EXPR='"detailFrame"'
											HKEYS={
												'getStringParam("$nsURI")';
												'"message-summary"';
											}
										</DOC_HLINK>
										<AREA>
											<CTRL_GROUP>
												<CTRLS>
													<TEXT_CTRL>
														TEXT='Messages'
													</TEXT_CTRL>
													<DATA_CTRL>
														FORMULA='"(" + iterator.numItems + ")"'
													</DATA_CTRL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
			</ELEMENT_ITER>
		</BODY>
	</FOLDER>
	<ELEMENT_ITER>
		DESCR='XML schemas targeting this namespace'
		COND='getBooleanParam("nav.indexFrame.namespace.xsd.schemas")'
		TARGET_ET='xs:schema'
		SCOPE='advanced-location-rules'
		RULES={
			'* -> {findElementsByKey ("namespaces", getParam("$nsURI"))}::xs:schema';
		}
		SORTING='by-compound-key'
		SORTING_KEY={
			{expr='getXMLDocument().getAttrValue("xmlName")',ascending};
			{expr='getServiceAttr("embeddedSchemaNo")',ascending};
		}
		SORTING_COND='getBooleanParam("gen.doc.sorting.xsd.schemas")'
		<BODY>
			<AREA_SEC>
				FMT={
					par.style='s3';
				}
				<AREA>
					<CTRL_GROUP>
						FMT={
							txtfl.delimiter.type='none';
						}
						<CTRLS>
							<IMAGE_CTRL>
								IMAGE_TYPE='file-image'
								FILE='../images/schema.png'
								OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
								FMT={
									image.alignment='bottom';
									image.padding.right='2.5';
								}
							</IMAGE_CTRL>
							<SS_CALL_CTRL>
								SS_NAME='Schema Name'
							</SS_CALL_CTRL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
		</BODY>
		<HEADER>
			<AREA_SEC>
				FMT={
					par.style='s1';
				}
				<HTARGET>
					HKEYS={
						'getParam("$nsURI")';
						'"indexFrame"';
						'"schemas"';
					}
				</HTARGET>
				<AREA>
					<CTRL_GROUP>
						<CTRLS>
							<PANEL>
								FMT={
									ctrl.size.width='168';
									ctrl.size.height='38.3';
									text.hlink.fmt='style';
									text.hlink.style='cs4';
									text.hlink.style.use='hover';
								}
								<DOC_HLINK>
									TITLE_EXPR='getBooleanParam("show.linkTitle") ? "see summary" : ""'
									TARGET_FRAME_EXPR='"detailFrame"'
									HKEYS={
										'getStringParam("$nsURI")';
										'"schema-summary"';
									}
								</DOC_HLINK>
								<AREA>
									<CTRL_GROUP>
										<CTRLS>
											<TEXT_CTRL>
												TEXT='Schemas'
											</TEXT_CTRL>
											<DATA_CTRL>
												FORMULA='"(" + iterator.numItems + ")"'
											</DATA_CTRL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</PANEL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
		</HEADER>
	</ELEMENT_ITER>
	<FOLDER>
		DESCR='XSD components'
		COND='getBooleanParam("nav.indexFrame.namespace.xsd.comps")'
		COLLAPSED
		<BODY>
			<ELEMENT_ITER>
				DESCR='list of elements'
				COND='getBooleanParam("nav.indexFrame.namespace.xsd.comps.elements")'
				TARGET_ET='xs:%element'
				SCOPE='advanced-location-rules'
				RULES={
					'* -> {findElementsByKey ("namespaces", getParam("$nsURI"))}::xs:schema/descendant::xs:%element[instanceOf("xs:element") || ! hasAttr("ref") &&
{
  form = hasAttr("form") ? getAttrValue("form") :
           findAncestor ("xs:schema").getAttrStringValue ("elementFormDefault");

  (form == "qualified" || getStringParam("$nsURI") == "")
}]';
					'*[getParam("$nsURI") == ""] -> {findElementsByKey ("namespaces", "")}::xs:%localElement';
				}
				FILTER='instanceOf("xs:element")
||
// case of local element
{
  // remain only those local elements that are either not documented globally at all
  // or documented globaly themselves (not via a unifier)

  el = findElementByKey ("xsd-globally-documented-local-elements", contextElement.id);
  el == null || el.id == contextElement.id
}
&&
{
  // which local elements to list?
  local = getStringParam("nav.indexFrame.namespace.xsd.comps.elements.local");
  
  local == "complexType" ?
    ((typeQName = getAttrQNameValue("type")) != null) ?
    {
      mainXML = findElementByKey ("main-xmls", getXMLDocument().id);

      checkElementsByKey ("xsd-types", typeQName,
        BooleanQuery (
          instanceOf("xs:complexType")
          &&
          checkElementByKey ("main-xmls", getXMLDocument().id, mainXML)
        )
      )
    }
    : hasChild("xs:complexType")
  :
  local == "all"
}'
				SORTING='by-expr'
				SORTING_KEY={expr='callStockSection("XSD Component Name")',ascending}
				SORTING_COND='getBooleanParam("nav.indexFrame.namespace.xsd.comps.sorting")'
				<BODY>
					<AREA_SEC>
						FMT={
							par.style='s3';
						}
						<AREA>
							<CTRL_GROUP>
								FMT={
									txtfl.delimiter.type='none';
								}
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/element.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											image.alignment='bottom';
											image.padding.right='2.5';
										}
									</IMAGE_CTRL>
									<SS_CALL_CTRL>
										SS_NAME='XSD Component Name'
									</SS_CALL_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
				<HEADER>
					<AREA_SEC>
						INIT_EXPR='! hasParamValue("gen.doc.xsd.comp.element.local", "none") &&
getBooleanParam("gen.doc.xsd.comp.element.local.unifyByType") ?
{
  elementCount = 0;

  iterate (
    iterator.items,
    @(GOMElement) el,
    FlexQuery ({
      count = el.instanceOf ("xs:element") ? 1 :
                countElementsByKey ("xsd-globally-documented-local-elements", el.id);

      elementCount = elementCount + (count > 0 ? count : 1);
    })
  )
} : {
  elementCount = iterator.numItems
};

setVar ("elementCount", elementCount);'
						FMT={
							sec.spacing.after='2.5';
							par.style='s1';
						}
						<HTARGET>
							HKEYS={
								'getParam("$nsURI")';
								'"indexFrame"';
								'"elements"';
							}
						</HTARGET>
						<AREA>
							<CTRL_GROUP>
								FMT={
									par.margin.bottom='0';
								}
								<CTRLS>
									<PANEL>
										FMT={
											ctrl.size.width='374.3';
											ctrl.size.height='38.3';
											text.hlink.fmt='style';
											text.hlink.style='cs4';
											text.hlink.style.use='hover';
										}
										<DOC_HLINK>
											TITLE_EXPR='getBooleanParam("show.linkTitle") ? "see summary" : ""'
											TARGET_FRAME_EXPR='"detailFrame"'
											HKEYS={
												'getStringParam("$nsURI")';
												'"element-summary"';
											}
										</DOC_HLINK>
										<AREA>
											<CTRL_GROUP>
												<CTRLS>
													<TEXT_CTRL>
														COND='hasParamValue("nav.indexFrame.namespace.xsd.comps.elements.local", "all")'
														TEXT='All'
													</TEXT_CTRL>
													<TEXT_CTRL>
														COND='hasParamValue("nav.indexFrame.namespace.xsd.comps.elements.local", "none")'
														TEXT='Global'
													</TEXT_CTRL>
													<TEXT_CTRL>
														TEXT='Elements'
													</TEXT_CTRL>
													<TEXT_CTRL>
														TEXT='('
													</TEXT_CTRL>
													<DELIMITER>
														FMT={
															txtfl.delimiter.type='none';
														}
													</DELIMITER>
													<DATA_CTRL>
														FORMULA='iterator.numItems'
													</DATA_CTRL>
													<DELIMITER>
														FMT={
															txtfl.delimiter.type='text';
															txtfl.delimiter.text=' / ';
														}
													</DELIMITER>
													<DATA_CTRL>
														COND='getIntVar("elementCount") != iterator.numItems'
														FORMULA='getVar("elementCount")'
													</DATA_CTRL>
													<DELIMITER>
														FMT={
															txtfl.delimiter.type='none';
														}
													</DELIMITER>
													<TEXT_CTRL>
														TEXT=')'
													</TEXT_CTRL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
							<CTRL_GROUP>
								FMT={
									par.style='s2';
								}
								<CTRLS>
									<TEMPLATE_CALL_CTRL>
										TEMPLATE_FILE='../xsd/element/elementListNote.tpl'
										PASSED_PARAMS={
											'$elements.local','getStringParam("nav.indexFrame.namespace.xsd.comps.elements.local")';
											'$elements.local.unifiedByType','getIntVar("elementCount") != iterator.numItems';
										}
									</TEMPLATE_CALL_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
			</ELEMENT_ITER>
			<ELEMENT_ITER>
				DESCR='list of complex types'
				COND='getBooleanParam("nav.indexFrame.namespace.xsd.comps.complexTypes")'
				TARGET_ET='xs:complexType'
				SCOPE='advanced-location-rules'
				RULES={
					'* -> {findElementsByKey ("namespaces", getParam("$nsURI"))}::xs:schema';
					'xs:schema -> xs:complexType',recursive;
					'xs:schema -> xs:redefine/xs:complexType',recursive;
				}
				SORTING='by-compound-key'
				SORTING_KEY={
					{expr='getAttrStringValue("name")',ascending};
					{expr='hasServiceAttr ("redefinition") ?
  getServiceAttr ("redefinition").toInt() : -1',ascending};
				}
				SORTING_COND='getBooleanParam("nav.indexFrame.namespace.xsd.comps.sorting")'
				<BODY>
					<AREA_SEC>
						FMT={
							par.style='s3';
						}
						<AREA>
							<CTRL_GROUP>
								FMT={
									txtfl.delimiter.type='none';
								}
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/complexType.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											image.alignment='bottom';
											image.padding.right='2.5';
										}
									</IMAGE_CTRL>
									<SS_CALL_CTRL>
										SS_NAME='XSD Component Name'
									</SS_CALL_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
				<HEADER>
					<AREA_SEC>
						FMT={
							par.style='s1';
						}
						<HTARGET>
							HKEYS={
								'getParam("$nsURI")';
								'"indexFrame"';
								'"complexTypes"';
							}
						</HTARGET>
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<PANEL>
										FMT={
											ctrl.size.width='190.5';
											ctrl.size.height='38.3';
											text.hlink.fmt='style';
											text.hlink.style='cs4';
											text.hlink.style.use='hover';
										}
										<DOC_HLINK>
											TITLE_EXPR='getBooleanParam("show.linkTitle") ? "see summary" : ""'
											TARGET_FRAME_EXPR='"detailFrame"'
											HKEYS={
												'getStringParam("$nsURI")';
												'"complexType-summary"';
											}
										</DOC_HLINK>
										<AREA>
											<CTRL_GROUP>
												<CTRLS>
													<TEXT_CTRL>
														TEXT='Complex Types'
													</TEXT_CTRL>
													<DATA_CTRL>
														FORMULA='"(" + iterator.numItems + ")"'
													</DATA_CTRL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
			</ELEMENT_ITER>
			<ELEMENT_ITER>
				DESCR='list of simple types'
				COND='getBooleanParam("nav.indexFrame.namespace.xsd.comps.simpleTypes")'
				TARGET_ET='xs:simpleType'
				SCOPE='advanced-location-rules'
				RULES={
					'* -> {findElementsByKey ("namespaces", getParam("$nsURI"))}::xs:schema';
					'xs:schema -> xs:simpleType',recursive;
					'xs:schema -> xs:redefine/xs:simpleType',recursive;
				}
				SORTING='by-compound-key'
				SORTING_KEY={
					{expr='getAttrStringValue("name")',ascending};
					{expr='hasServiceAttr ("redefinition") ?
  getServiceAttr ("redefinition").toInt() : -1',ascending};
				}
				SORTING_COND='getBooleanParam("nav.indexFrame.namespace.xsd.comps.sorting")'
				<BODY>
					<AREA_SEC>
						FMT={
							par.style='s3';
						}
						<AREA>
							<CTRL_GROUP>
								FMT={
									txtfl.delimiter.type='none';
								}
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/simpleType.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											image.alignment='bottom';
											image.padding.right='2.5';
										}
									</IMAGE_CTRL>
									<SS_CALL_CTRL>
										SS_NAME='XSD Component Name'
									</SS_CALL_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
				<HEADER>
					<AREA_SEC>
						FMT={
							par.style='s1';
						}
						<HTARGET>
							HKEYS={
								'getParam("$nsURI")';
								'"indexFrame"';
								'"simpleTypes"';
							}
						</HTARGET>
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<PANEL>
										FMT={
											ctrl.size.width='184.5';
											ctrl.size.height='38.3';
											text.hlink.fmt='style';
											text.hlink.style='cs4';
											text.hlink.style.use='hover';
										}
										<DOC_HLINK>
											TITLE_EXPR='getBooleanParam("show.linkTitle") ? "see summary" : ""'
											TARGET_FRAME_EXPR='"detailFrame"'
											HKEYS={
												'getStringParam("$nsURI")';
												'"simpleType-summary"';
											}
										</DOC_HLINK>
										<AREA>
											<CTRL_GROUP>
												<CTRLS>
													<TEXT_CTRL>
														TEXT='Simple Types'
													</TEXT_CTRL>
													<DATA_CTRL>
														FORMULA='"(" + iterator.numItems + ")"'
													</DATA_CTRL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
			</ELEMENT_ITER>
			<ELEMENT_ITER>
				DESCR='list of element groups'
				COND='getBooleanParam("nav.indexFrame.namespace.xsd.comps.groups")'
				TARGET_ET='xs:group'
				SCOPE='advanced-location-rules'
				RULES={
					'* -> {findElementsByKey ("namespaces", getParam("$nsURI"))}::xs:schema';
					'xs:schema -> xs:group',recursive;
					'xs:schema -> xs:redefine/xs:group',recursive;
				}
				SORTING='by-compound-key'
				SORTING_KEY={
					{expr='getAttrStringValue("name")',ascending};
					{expr='hasServiceAttr ("redefinition") ?
  getServiceAttr ("redefinition").toInt() : -1',ascending};
				}
				SORTING_COND='getBooleanParam("nav.indexFrame.namespace.xsd.comps.sorting")'
				<BODY>
					<AREA_SEC>
						FMT={
							par.style='s3';
						}
						<AREA>
							<CTRL_GROUP>
								FMT={
									txtfl.delimiter.type='none';
								}
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/group.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											image.alignment='bottom';
											image.padding.right='2.5';
										}
									</IMAGE_CTRL>
									<SS_CALL_CTRL>
										SS_NAME='XSD Component Name'
									</SS_CALL_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
				<HEADER>
					<AREA_SEC>
						FMT={
							par.style='s1';
						}
						<HTARGET>
							HKEYS={
								'getParam("$nsURI")';
								'"indexFrame"';
								'"groups"';
							}
						</HTARGET>
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<PANEL>
										FMT={
											ctrl.size.width='192';
											ctrl.size.height='38.3';
											text.hlink.fmt='style';
											text.hlink.style='cs4';
											text.hlink.style.use='hover';
										}
										<DOC_HLINK>
											TITLE_EXPR='getBooleanParam("show.linkTitle") ? "see summary" : ""'
											TARGET_FRAME_EXPR='"detailFrame"'
											HKEYS={
												'getStringParam("$nsURI")';
												'"group-summary"';
											}
										</DOC_HLINK>
										<AREA>
											<CTRL_GROUP>
												<CTRLS>
													<TEXT_CTRL>
														TEXT='Element Groups'
													</TEXT_CTRL>
													<DATA_CTRL>
														FORMULA='"(" + iterator.numItems + ")"'
													</DATA_CTRL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
			</ELEMENT_ITER>
			<ELEMENT_ITER>
				DESCR='list of global attributes'
				COND='getBooleanParam("nav.indexFrame.namespace.xsd.comps.attributes")'
				TARGET_ET='xs:attribute'
				SCOPE='advanced-location-rules'
				RULES={
					'* -> {findElementsByKey ("namespaces", getParam("$nsURI"))}::xs:schema/xs:attribute';
				}
				SORTING='by-attr'
				SORTING_KEY={lpath='@name',ascending}
				SORTING_COND='getBooleanParam("nav.indexFrame.namespace.xsd.comps.sorting")'
				<BODY>
					<AREA_SEC>
						FMT={
							par.style='s3';
						}
						<AREA>
							<CTRL_GROUP>
								FMT={
									txtfl.delimiter.type='none';
								}
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/attribute.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											image.alignment='bottom';
											image.padding.right='2.5';
										}
									</IMAGE_CTRL>
									<SS_CALL_CTRL>
										SS_NAME='XSD Component Name'
									</SS_CALL_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
				<HEADER>
					<AREA_SEC>
						FMT={
							par.style='s1';
						}
						<HTARGET>
							HKEYS={
								'getParam("$nsURI")';
								'"indexFrame"';
								'"attributes"';
							}
						</HTARGET>
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<PANEL>
										FMT={
											ctrl.size.width='167.3';
											ctrl.size.height='38.3';
											text.hlink.fmt='style';
											text.hlink.style='cs4';
											text.hlink.style.use='hover';
										}
										<DOC_HLINK>
											TITLE_EXPR='getBooleanParam("show.linkTitle") ? "see summary" : ""'
											TARGET_FRAME_EXPR='"detailFrame"'
											HKEYS={
												'getStringParam("$nsURI")';
												'"attribute-summary"';
											}
										</DOC_HLINK>
										<AREA>
											<CTRL_GROUP>
												<CTRLS>
													<TEXT_CTRL>
														TEXT='Attributes'
													</TEXT_CTRL>
													<DATA_CTRL>
														FORMULA='"(" + iterator.numItems + ")"'
													</DATA_CTRL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
			</ELEMENT_ITER>
			<ELEMENT_ITER>
				DESCR='list of attribute groups'
				COND='getBooleanParam("nav.indexFrame.namespace.xsd.comps.attributeGroups")'
				TARGET_ET='xs:attributeGroup'
				SCOPE='advanced-location-rules'
				RULES={
					'* -> {findElementsByKey ("namespaces", getParam("$nsURI"))}::xs:schema';
					'xs:schema -> xs:attributeGroup',recursive;
					'xs:schema -> xs:redefine/xs:attributeGroup',recursive;
				}
				SORTING='by-compound-key'
				SORTING_KEY={
					{expr='getAttrStringValue("name")',ascending};
					{expr='hasServiceAttr ("redefinition") ?
  getServiceAttr ("redefinition").toInt() : -1',ascending};
				}
				SORTING_COND='getBooleanParam("nav.indexFrame.namespace.xsd.comps.sorting")'
				<BODY>
					<AREA_SEC>
						FMT={
							par.style='s3';
						}
						<AREA>
							<CTRL_GROUP>
								FMT={
									txtfl.delimiter.type='none';
								}
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/attributeGroup.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											image.alignment='bottom';
											image.padding.right='2.5';
										}
									</IMAGE_CTRL>
									<SS_CALL_CTRL>
										SS_NAME='XSD Component Name'
									</SS_CALL_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
				<HEADER>
					<AREA_SEC>
						FMT={
							par.style='s1';
						}
						<HTARGET>
							HKEYS={
								'getParam("$nsURI")';
								'"indexFrame"';
								'"attributeGroups"';
							}
						</HTARGET>
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<PANEL>
										FMT={
											ctrl.size.width='190.5';
											ctrl.size.height='38.3';
											text.hlink.fmt='style';
											text.hlink.style='cs4';
											text.hlink.style.use='hover';
										}
										<DOC_HLINK>
											TITLE_EXPR='getBooleanParam("show.linkTitle") ? "see summary" : ""'
											TARGET_FRAME_EXPR='"detailFrame"'
											HKEYS={
												'getStringParam("$nsURI")';
												'"attributeGroup-summary"';
											}
										</DOC_HLINK>
										<AREA>
											<CTRL_GROUP>
												<CTRLS>
													<TEXT_CTRL>
														TEXT='Attribute Groups'
													</TEXT_CTRL>
													<DATA_CTRL>
														FORMULA='"(" + iterator.numItems + ")"'
													</DATA_CTRL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
			</ELEMENT_ITER>
		</BODY>
	</FOLDER>
</ROOT>
<STOCK_SECTIONS>
	<TEMPLATE_CALL>
		SS_NAME='Schema Name'
		MATCHING_ET='xs:schema'
		TEMPLATE_FILE='../xsd/schema/schemaName.tpl'
		PASSED_PARAMS={
			'$targetFrame','"detailFrame"';
		}
	</TEMPLATE_CALL>
	<FOLDER>
		SS_NAME='TOC'
		FMT={
			table.cell.padding.both='0';
			table.border.style='none';
		}
		<BODY>
			<FOLDER>
				DESCR='WSDL'
				FMT={
					sec.outputStyle='table';
					sec.spacing.after='1.7';
					table.cell.padding.both='0';
					table.border.style='none';
				}
				<BODY>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "wsdl-files"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/wsdls.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='WSDL Files'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"wsdl-files"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "services"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/services.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Services'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"services"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "bindings"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/bindings.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Bindings'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"bindings"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "portTypes"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/portTypes.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Port Types'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"portTypes"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "messages"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/messages.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Messages'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"messages"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
				<HEADER>
					<AREA_SEC>
						FMT={
							sec.outputStyle='pars';
						}
						<AREA>
							<SPACER>
								FMT={
									spacer.height='2.5';
								}
							</SPACER>
							<CTRL_GROUP>
								FMT={
									par.style='s5';
								}
								<CTRLS>
									<TEXT_CTRL>
										TEXT='WSDL Files / Definitions'
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
			</FOLDER>
			<FOLDER>
				DESCR='XSD'
				FMT={
					sec.outputStyle='table';
					table.cell.padding.both='0';
					table.border.style='none';
				}
				<BODY>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "schemas"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/types.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Schemas'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"schemas"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "elements"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/elements.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Elements'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"elements"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "complexTypes"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/complexTypes.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Complex Types'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"complexTypes"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "simpleTypes"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/simpleTypes.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Simple Types'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"simpleTypes"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "groups"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/groups.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Element Groups'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"groups"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "attributes"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/attributes.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Attributes'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"attributes"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "attributeGroups"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/attributeGroups.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Attribute Groups'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"attributeGroups"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
				<HEADER>
					<AREA_SEC>
						FMT={
							sec.outputStyle='pars';
						}
						<AREA>
							<SPACER>
								FMT={
									spacer.height='2.5';
								}
							</SPACER>
							<CTRL_GROUP>
								FMT={
									par.style='s5';
								}
								<CTRLS>
									<TEXT_CTRL>
										TEXT='XSD Schemas / Components'
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
			</FOLDER>
		</BODY>
	</FOLDER>
	<FOLDER>
		SS_NAME='TOC1'
		FMT={
			table.cell.padding.both='0';
			table.border.style='none';
		}
		<BODY>
			<FOLDER>
				DESCR='WSDL'
				FMT={
					sec.outputStyle='table';
					sec.spacing.after='1.7';
					table.cell.padding.both='0';
					table.border.style='none';
				}
				<BODY>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "wsdl-files"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/wsdls.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='WSDL Files'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"wsdl-files"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "services"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/services.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Services'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"services"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "bindings"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/bindings.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Bindings'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"bindings"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "portTypes"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/portTypes.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Port Types'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"portTypes"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "messages"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/messages.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Messages'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"messages"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
				<HEADER>
					<AREA_SEC>
						FMT={
							sec.outputStyle='pars';
						}
						<AREA>
							<CTRL_GROUP>
								FMT={
									par.style='s5';
								}
								<CTRLS>
									<TEXT_CTRL>
										TEXT='WSDL Files / Definitions'
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
			</FOLDER>
			<FOLDER>
				DESCR='XSD'
				FMT={
					sec.outputStyle='table';
					table.cell.padding.both='0';
					table.border.style='none';
				}
				<BODY>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "schemas"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/types.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Schemas'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"schemas"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "elements"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/elements.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Elements'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"elements"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "complexTypes"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/complexTypes.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Complex Types'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"complexTypes"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "simpleTypes"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/simpleTypes.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Simple Types'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"simpleTypes"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "groups"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/groups.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Element Groups'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"groups"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "attributes"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/attributes.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Attributes'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"attributes"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='findHyperTarget (
  Array (
    getParam("$nsURI"),
    "indexFrame",
    "attributeGroups"
  )
) != null'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<IMAGE_CTRL>
										IMAGE_TYPE='file-image'
										FILE='../images/attributeGroups.png'
										OUTPUT_DIR_EXPR='getStringParam("$resourceOutputDir")'
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='18';
											image.alignment='bottom';
											image.padding.right='1.7';
										}
									</IMAGE_CTRL>
									<TEXT_CTRL>
										TEXT='Attribute Groups'
										FMT={
											ctrl.size.width='478.5';
											ctrl.size.height='18';
											par.style='s6';
										}
										<DOC_HLINK>
											HKEYS={
												'getParam("$nsURI")';
												'"indexFrame"';
												'"attributeGroups"';
											}
										</DOC_HLINK>
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
				<HEADER>
					<AREA_SEC>
						FMT={
							sec.outputStyle='pars';
						}
						<AREA>
							<SPACER>
								FMT={
									spacer.height='2.5';
								}
							</SPACER>
							<CTRL_GROUP>
								FMT={
									par.style='s5';
								}
								<CTRLS>
									<TEXT_CTRL>
										TEXT='Schemas / Components'
									</TEXT_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
			</FOLDER>
		</BODY>
	</FOLDER>
	<TEMPLATE_CALL>
		SS_NAME='WSDL Definition Name'
		DESCR='prints the qualified name of the WSDL definition'
		TEMPLATE_FILE='../wsdl/misc/defName.tpl'
		PASSED_PARAMS={
			'$targetFrame','"detailFrame"';
		}
		FMT={
			sec.outputStyle='text-par';
		}
	</TEMPLATE_CALL>
	<TEMPLATE_CALL>
		SS_NAME='WSDL Name'
		MATCHING_ET='wsdl:definitions'
		TEMPLATE_FILE='../wsdl/file/wsdlName.tpl'
		PASSED_PARAMS={
			'$targetFrame','"detailFrame"';
		}
	</TEMPLATE_CALL>
	<TEMPLATE_CALL>
		SS_NAME='XSD Component Name'
		DESCR='prints the qualified name of any global schema component or local element (passed as the stock-section context element)'
		TEMPLATE_FILE='../xsd/component/componentName.tpl'
		PASSED_PARAMS={
			'$targetFrame','"detailFrame"';
		}
		FMT={
			sec.outputStyle='text-par';
		}
	</TEMPLATE_CALL>
</STOCK_SECTIONS>
CHECKSUM='paXhvl6ogTWCiqqU15ZgCcA0Ut3N3Y8GmOdgIYx+QX0'
</DOCFLEX_TEMPLATE>