var KML_2_2_0_Module_Factory = function () {
  var KML_2_2_0 = {
    n: 'KML_2_2_0',
    dens: 'http:\/\/www.opengis.net\/kml\/2.2',
    deps: ['Atom_1_0', 'xAL_2_0', 'Atom_1_0'],
    tis: [{
        ln: 'ListStyleType',
        bti: '.AbstractSubStyleType',
        ps: [{
            n: 'listItemType'
          }, {
            n: 'bgColor'
          }, {
            n: 'itemIcon',
            col: true,
            en: 'ItemIcon',
            ti: '.ItemIconType'
          }, {
            n: 'maxSnippetLines',
            ti: 'Int'
          }, {
            n: 'listStyleSimpleExtensionGroup',
            col: true,
            en: 'ListStyleSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'listStyleObjectExtensionGroup',
            col: true,
            en: 'ListStyleObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'AbstractObjectType',
        ps: [{
            n: 'objectSimpleExtensionGroup',
            col: true,
            en: 'ObjectSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }, {
            n: 'targetId',
            an: {
              lp: 'targetId'
            },
            t: 'a'
          }]
      }, {
        ln: 'AbstractLatLonBoxType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'north',
            ti: 'Double'
          }, {
            n: 'south',
            ti: 'Double'
          }, {
            n: 'east',
            ti: 'Double'
          }, {
            n: 'west',
            ti: 'Double'
          }, {
            n: 'abstractLatLonBoxSimpleExtensionGroup',
            col: true,
            en: 'AbstractLatLonBoxSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'abstractLatLonBoxObjectExtensionGroup',
            col: true,
            en: 'AbstractLatLonBoxObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'IconStyleType',
        bti: '.AbstractColorStyleType',
        ps: [{
            n: 'scale',
            ti: 'Double'
          }, {
            n: 'heading',
            ti: 'Double'
          }, {
            n: 'icon',
            en: 'Icon',
            ti: '.BasicLinkType'
          }, {
            n: 'hotSpot',
            ti: '.Vec2Type'
          }, {
            n: 'iconStyleSimpleExtensionGroup',
            col: true,
            en: 'IconStyleSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'iconStyleObjectExtensionGroup',
            col: true,
            en: 'IconStyleObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'StyleMapType',
        bti: '.AbstractStyleSelectorType',
        ps: [{
            n: 'pair',
            col: true,
            en: 'Pair',
            ti: '.PairType'
          }, {
            n: 'styleMapSimpleExtensionGroup',
            col: true,
            en: 'StyleMapSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'styleMapObjectExtensionGroup',
            col: true,
            en: 'StyleMapObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'ScaleType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'x',
            ti: 'Double'
          }, {
            n: 'y',
            ti: 'Double'
          }, {
            n: 'z',
            ti: 'Double'
          }, {
            n: 'scaleSimpleExtensionGroup',
            col: true,
            en: 'ScaleSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'scaleObjectExtensionGroup',
            col: true,
            en: 'ScaleObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'AbstractColorStyleType',
        bti: '.AbstractSubStyleType',
        ps: [{
            n: 'color'
          }, {
            n: 'colorMode'
          }, {
            n: 'abstractColorStyleSimpleExtensionGroup',
            col: true,
            en: 'AbstractColorStyleSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'abstractColorStyleObjectExtensionGroup',
            col: true,
            en: 'AbstractColorStyleObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'PairType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'key'
          }, {
            n: 'styleUrl'
          }, {
            n: 'abstractStyleSelectorGroup',
            mx: false,
            dom: false,
            typed: false,
            en: 'AbstractStyleSelectorGroup',
            ti: '.AbstractStyleSelectorType',
            t: 'er'
          }, {
            n: 'pairSimpleExtensionGroup',
            col: true,
            en: 'PairSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'pairObjectExtensionGroup',
            col: true,
            en: 'PairObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'GroundOverlayType',
        bti: '.AbstractOverlayType',
        ps: [{
            n: 'altitude',
            ti: 'Double'
          }, {
            n: 'altitudeModeGroup',
            mx: false,
            dom: false,
            typed: false,
            ti: 'AnyType',
            t: 'er'
          }, {
            n: 'latLonBox',
            en: 'LatLonBox',
            ti: '.LatLonBoxType'
          }, {
            n: 'groundOverlaySimpleExtensionGroup',
            col: true,
            en: 'GroundOverlaySimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'groundOverlayObjectExtensionGroup',
            col: true,
            en: 'GroundOverlayObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'AbstractGeometryType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'abstractGeometrySimpleExtensionGroup',
            col: true,
            en: 'AbstractGeometrySimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'abstractGeometryObjectExtensionGroup',
            col: true,
            en: 'AbstractGeometryObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'BoundaryType',
        ps: [{
            n: 'linearRing',
            en: 'LinearRing',
            ti: '.LinearRingType'
          }, {
            n: 'boundarySimpleExtensionGroup',
            col: true,
            en: 'BoundarySimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'boundaryObjectExtensionGroup',
            col: true,
            en: 'BoundaryObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'StyleType',
        bti: '.AbstractStyleSelectorType',
        ps: [{
            n: 'iconStyle',
            en: 'IconStyle',
            ti: '.IconStyleType'
          }, {
            n: 'labelStyle',
            en: 'LabelStyle',
            ti: '.LabelStyleType'
          }, {
            n: 'lineStyle',
            en: 'LineStyle',
            ti: '.LineStyleType'
          }, {
            n: 'polyStyle',
            en: 'PolyStyle',
            ti: '.PolyStyleType'
          }, {
            n: 'balloonStyle',
            en: 'BalloonStyle',
            ti: '.BalloonStyleType'
          }, {
            n: 'listStyle',
            en: 'ListStyle',
            ti: '.ListStyleType'
          }, {
            n: 'styleSimpleExtensionGroup',
            col: true,
            en: 'StyleSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'styleObjectExtensionGroup',
            col: true,
            en: 'StyleObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'LinearRingType',
        bti: '.AbstractGeometryType',
        ps: [{
            n: 'extrude',
            ti: 'Boolean'
          }, {
            n: 'tessellate',
            ti: 'Boolean'
          }, {
            n: 'altitudeModeGroup',
            mx: false,
            dom: false,
            typed: false,
            ti: 'AnyType',
            t: 'er'
          }, {
            n: 'coordinates',
            ti: {
              t: 'l'
            }
          }, {
            n: 'linearRingSimpleExtensionGroup',
            col: true,
            en: 'LinearRingSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'linearRingObjectExtensionGroup',
            col: true,
            en: 'LinearRingObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'SnippetType',
        ps: [{
            n: 'value',
            t: 'v'
          }, {
            n: 'maxLines',
            ti: 'Int',
            an: {
              lp: 'maxLines'
            },
            t: 'a'
          }]
      }, {
        ln: 'BalloonStyleType',
        bti: '.AbstractSubStyleType',
        ps: [{
            n: 'color'
          }, {
            n: 'bgColor'
          }, {
            n: 'textColor'
          }, {
            n: 'text'
          }, {
            n: 'displayMode'
          }, {
            n: 'balloonStyleSimpleExtensionGroup',
            col: true,
            en: 'BalloonStyleSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'balloonStyleObjectExtensionGroup',
            col: true,
            en: 'BalloonStyleObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'AbstractViewType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'abstractViewSimpleExtensionGroup',
            col: true,
            en: 'AbstractViewSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'abstractViewObjectExtensionGroup',
            col: true,
            en: 'AbstractViewObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'LodType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'minLodPixels',
            ti: 'Double'
          }, {
            n: 'maxLodPixels',
            ti: 'Double'
          }, {
            n: 'minFadeExtent',
            ti: 'Double'
          }, {
            n: 'maxFadeExtent',
            ti: 'Double'
          }, {
            n: 'lodSimpleExtensionGroup',
            col: true,
            en: 'LodSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'lodObjectExtensionGroup',
            col: true,
            en: 'LodObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'FolderType',
        bti: '.AbstractContainerType',
        ps: [{
            n: 'abstractFeatureGroup',
            col: true,
            mx: false,
            dom: false,
            typed: false,
            en: 'AbstractFeatureGroup',
            ti: '.AbstractFeatureType',
            t: 'er'
          }, {
            n: 'folderSimpleExtensionGroup',
            col: true,
            en: 'FolderSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'folderObjectExtensionGroup',
            col: true,
            en: 'FolderObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'RegionType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'latLonAltBox',
            en: 'LatLonAltBox',
            ti: '.LatLonAltBoxType'
          }, {
            n: 'lod',
            en: 'Lod',
            ti: '.LodType'
          }, {
            n: 'regionSimpleExtensionGroup',
            col: true,
            en: 'RegionSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'regionObjectExtensionGroup',
            col: true,
            en: 'RegionObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'PlacemarkType',
        bti: '.AbstractFeatureType',
        ps: [{
            n: 'abstractGeometryGroup',
            mx: false,
            dom: false,
            typed: false,
            en: 'AbstractGeometryGroup',
            ti: '.AbstractGeometryType',
            t: 'er'
          }, {
            n: 'placemarkSimpleExtensionGroup',
            col: true,
            en: 'PlacemarkSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'placemarkObjectExtensionGroup',
            col: true,
            en: 'PlacemarkObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'SimpleFieldType',
        ps: [{
            n: 'displayName'
          }, {
            n: 'simpleFieldExtension',
            col: true,
            en: 'SimpleFieldExtension',
            ti: 'AnyType'
          }, {
            n: 'type',
            an: {
              lp: 'type'
            },
            t: 'a'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }]
      }, {
        ln: 'KmlType',
        ps: [{
            n: 'networkLinkControl',
            en: 'NetworkLinkControl',
            ti: '.NetworkLinkControlType'
          }, {
            n: 'abstractFeatureGroup',
            mx: false,
            dom: false,
            typed: false,
            en: 'AbstractFeatureGroup',
            ti: '.AbstractFeatureType',
            t: 'er'
          }, {
            n: 'kmlSimpleExtensionGroup',
            col: true,
            en: 'KmlSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'kmlObjectExtensionGroup',
            col: true,
            en: 'KmlObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }, {
            n: 'hint',
            an: {
              lp: 'hint'
            },
            t: 'a'
          }]
      }, {
        ln: 'ModelType',
        bti: '.AbstractGeometryType',
        ps: [{
            n: 'altitudeModeGroup',
            mx: false,
            dom: false,
            typed: false,
            ti: 'AnyType',
            t: 'er'
          }, {
            n: 'location',
            en: 'Location',
            ti: '.LocationType'
          }, {
            n: 'orientation',
            en: 'Orientation',
            ti: '.OrientationType'
          }, {
            n: 'scale',
            en: 'Scale',
            ti: '.ScaleType'
          }, {
            n: 'link',
            en: 'Link',
            ti: '.LinkType'
          }, {
            n: 'resourceMap',
            en: 'ResourceMap',
            ti: '.ResourceMapType'
          }, {
            n: 'modelSimpleExtensionGroup',
            col: true,
            en: 'ModelSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'modelObjectExtensionGroup',
            col: true,
            en: 'ModelObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'LabelStyleType',
        bti: '.AbstractColorStyleType',
        ps: [{
            n: 'scale',
            ti: 'Double'
          }, {
            n: 'labelStyleSimpleExtensionGroup',
            col: true,
            en: 'LabelStyleSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'labelStyleObjectExtensionGroup',
            col: true,
            en: 'LabelStyleObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'Vec2Type',
        ps: [{
            n: 'x',
            ti: 'Double',
            an: {
              lp: 'x'
            },
            t: 'a'
          }, {
            n: 'y',
            ti: 'Double',
            an: {
              lp: 'y'
            },
            t: 'a'
          }, {
            n: 'xunits',
            an: {
              lp: 'xunits'
            },
            t: 'a'
          }, {
            n: 'yunits',
            an: {
              lp: 'yunits'
            },
            t: 'a'
          }]
      }, {
        ln: 'PhotoOverlayType',
        bti: '.AbstractOverlayType',
        ps: [{
            n: 'rotation',
            ti: 'Double'
          }, {
            n: 'viewVolume',
            en: 'ViewVolume',
            ti: '.ViewVolumeType'
          }, {
            n: 'imagePyramid',
            en: 'ImagePyramid',
            ti: '.ImagePyramidType'
          }, {
            n: 'point',
            en: 'Point',
            ti: '.PointType'
          }, {
            n: 'shape'
          }, {
            n: 'photoOverlaySimpleExtensionGroup',
            col: true,
            en: 'PhotoOverlaySimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'photoOverlayObjectExtensionGroup',
            col: true,
            en: 'PhotoOverlayObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'ImagePyramidType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'tileSize',
            ti: 'Int'
          }, {
            n: 'maxWidth',
            ti: 'Int'
          }, {
            n: 'maxHeight',
            ti: 'Int'
          }, {
            n: 'gridOrigin'
          }, {
            n: 'imagePyramidSimpleExtensionGroup',
            col: true,
            en: 'ImagePyramidSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'imagePyramidObjectExtensionGroup',
            col: true,
            en: 'ImagePyramidObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'CreateType',
        ps: [{
            n: 'abstractContainerGroup',
            col: true,
            mx: false,
            dom: false,
            typed: false,
            en: 'AbstractContainerGroup',
            ti: '.AbstractContainerType',
            t: 'er'
          }]
      }, {
        ln: 'NetworkLinkType',
        bti: '.AbstractFeatureType',
        ps: [{
            n: 'refreshVisibility',
            ti: 'Boolean'
          }, {
            n: 'flyToView',
            ti: 'Boolean'
          }, {
            n: 'url',
            en: 'Url',
            ti: '.LinkType'
          }, {
            n: 'link',
            en: 'Link',
            ti: '.LinkType'
          }, {
            n: 'networkLinkSimpleExtensionGroup',
            col: true,
            en: 'NetworkLinkSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'networkLinkObjectExtensionGroup',
            col: true,
            en: 'NetworkLinkObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'LineStyleType',
        bti: '.AbstractColorStyleType',
        ps: [{
            n: 'width',
            ti: 'Double'
          }, {
            n: 'lineStyleSimpleExtensionGroup',
            col: true,
            en: 'LineStyleSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'lineStyleObjectExtensionGroup',
            col: true,
            en: 'LineStyleObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'AbstractFeatureType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'name'
          }, {
            n: 'visibility',
            ti: 'Boolean'
          }, {
            n: 'open',
            ti: 'Boolean'
          }, {
            n: 'atomAuthor',
            en: {
              lp: 'author',
              ns: 'http:\/\/www.w3.org\/2005\/Atom'
            },
            ti: 'Atom_1_0.AtomPersonConstruct'
          }, {
            n: 'atomLink',
            en: {
              lp: 'link',
              ns: 'http:\/\/www.w3.org\/2005\/Atom'
            },
            ti: 'Atom_1_0.Link'
          }, {
            n: 'address'
          }, {
            n: 'addressDetails',
            en: {
              lp: 'AddressDetails',
              ns: 'urn:oasis:names:tc:ciq:xsdschema:xAL:2.0'
            },
            ti: 'xAL_2_0.AddressDetails'
          }, {
            n: 'phoneNumber'
          }, {
            n: 'complexSnippet',
            en: 'Snippet',
            ti: '.SnippetType'
          }, {
            n: 'snippet'
          }, {
            n: 'description'
          }, {
            n: 'abstractViewGroup',
            mx: false,
            dom: false,
            typed: false,
            en: 'AbstractViewGroup',
            ti: '.AbstractViewType',
            t: 'er'
          }, {
            n: 'abstractTimePrimitiveGroup',
            mx: false,
            dom: false,
            typed: false,
            en: 'AbstractTimePrimitiveGroup',
            ti: '.AbstractTimePrimitiveType',
            t: 'er'
          }, {
            n: 'styleUrl'
          }, {
            n: 'abstractStyleSelectorGroup',
            col: true,
            mx: false,
            dom: false,
            typed: false,
            en: 'AbstractStyleSelectorGroup',
            ti: '.AbstractStyleSelectorType',
            t: 'er'
          }, {
            n: 'region',
            en: 'Region',
            ti: '.RegionType'
          }, {
            n: 'metadata',
            en: 'Metadata',
            ti: '.MetadataType'
          }, {
            n: 'extendedData',
            en: 'ExtendedData',
            ti: '.ExtendedDataType'
          }, {
            n: 'abstractFeatureSimpleExtensionGroup',
            col: true,
            en: 'AbstractFeatureSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'abstractFeatureObjectExtensionGroup',
            col: true,
            en: 'AbstractFeatureObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'ResourceMapType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'alias',
            col: true,
            en: 'Alias',
            ti: '.AliasType'
          }, {
            n: 'resourceMapSimpleExtensionGroup',
            col: true,
            en: 'ResourceMapSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'resourceMapObjectExtensionGroup',
            col: true,
            en: 'ResourceMapObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'NetworkLinkControlType',
        ps: [{
            n: 'minRefreshPeriod',
            ti: 'Double'
          }, {
            n: 'maxSessionLength',
            ti: 'Double'
          }, {
            n: 'cookie'
          }, {
            n: 'message'
          }, {
            n: 'linkName'
          }, {
            n: 'linkDescription'
          }, {
            n: 'linkSnippet',
            ti: '.SnippetType'
          }, {
            n: 'expires'
          }, {
            n: 'update',
            en: 'Update',
            ti: '.UpdateType'
          }, {
            n: 'abstractViewGroup',
            mx: false,
            dom: false,
            typed: false,
            en: 'AbstractViewGroup',
            ti: '.AbstractViewType',
            t: 'er'
          }, {
            n: 'networkLinkControlSimpleExtensionGroup',
            col: true,
            en: 'NetworkLinkControlSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'networkLinkControlObjectExtensionGroup',
            col: true,
            en: 'NetworkLinkControlObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'LatLonBoxType',
        bti: '.AbstractLatLonBoxType',
        ps: [{
            n: 'rotation',
            ti: 'Double'
          }, {
            n: 'latLonBoxSimpleExtensionGroup',
            col: true,
            en: 'LatLonBoxSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'latLonBoxObjectExtensionGroup',
            col: true,
            en: 'LatLonBoxObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'TimeStampType',
        bti: '.AbstractTimePrimitiveType',
        ps: [{
            n: 'when'
          }, {
            n: 'timeStampSimpleExtensionGroup',
            col: true,
            en: 'TimeStampSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'timeStampObjectExtensionGroup',
            col: true,
            en: 'TimeStampObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'AbstractContainerType',
        bti: '.AbstractFeatureType',
        ps: [{
            n: 'abstractContainerSimpleExtensionGroup',
            col: true,
            en: 'AbstractContainerSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'abstractContainerObjectExtensionGroup',
            col: true,
            en: 'AbstractContainerObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'ViewVolumeType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'leftFov',
            ti: 'Double'
          }, {
            n: 'rightFov',
            ti: 'Double'
          }, {
            n: 'bottomFov',
            ti: 'Double'
          }, {
            n: 'topFov',
            ti: 'Double'
          }, {
            n: 'near',
            ti: 'Double'
          }, {
            n: 'viewVolumeSimpleExtensionGroup',
            col: true,
            en: 'ViewVolumeSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'viewVolumeObjectExtensionGroup',
            col: true,
            en: 'ViewVolumeObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'AbstractOverlayType',
        bti: '.AbstractFeatureType',
        ps: [{
            n: 'color'
          }, {
            n: 'drawOrder',
            ti: 'Int'
          }, {
            n: 'icon',
            en: 'Icon',
            ti: '.LinkType'
          }, {
            n: 'abstractOverlaySimpleExtensionGroup',
            col: true,
            en: 'AbstractOverlaySimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'abstractOverlayObjectExtensionGroup',
            col: true,
            en: 'AbstractOverlayObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'ItemIconType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'state',
            ti: {
              t: 'l'
            }
          }, {
            n: 'href'
          }, {
            n: 'itemIconSimpleExtensionGroup',
            col: true,
            en: 'ItemIconSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'itemIconObjectExtensionGroup',
            col: true,
            en: 'ItemIconObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'CameraType',
        bti: '.AbstractViewType',
        ps: [{
            n: 'longitude',
            ti: 'Double'
          }, {
            n: 'latitude',
            ti: 'Double'
          }, {
            n: 'altitude',
            ti: 'Double'
          }, {
            n: 'heading',
            ti: 'Double'
          }, {
            n: 'tilt',
            ti: 'Double'
          }, {
            n: 'roll',
            ti: 'Double'
          }, {
            n: 'altitudeModeGroup',
            mx: false,
            dom: false,
            typed: false,
            ti: 'AnyType',
            t: 'er'
          }, {
            n: 'cameraSimpleExtensionGroup',
            col: true,
            en: 'CameraSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'cameraObjectExtensionGroup',
            col: true,
            en: 'CameraObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'LatLonAltBoxType',
        bti: '.AbstractLatLonBoxType',
        ps: [{
            n: 'minAltitude',
            ti: 'Double'
          }, {
            n: 'maxAltitude',
            ti: 'Double'
          }, {
            n: 'altitudeModeGroup',
            mx: false,
            dom: false,
            typed: false,
            ti: 'AnyType',
            t: 'er'
          }, {
            n: 'latLonAltBoxSimpleExtensionGroup',
            col: true,
            en: 'LatLonAltBoxSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'latLonAltBoxObjectExtensionGroup',
            col: true,
            en: 'LatLonAltBoxObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'TimeSpanType',
        bti: '.AbstractTimePrimitiveType',
        ps: [{
            n: 'begin'
          }, {
            n: 'end'
          }, {
            n: 'timeSpanSimpleExtensionGroup',
            col: true,
            en: 'TimeSpanSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'timeSpanObjectExtensionGroup',
            col: true,
            en: 'TimeSpanObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'AbstractSubStyleType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'abstractSubStyleSimpleExtensionGroup',
            col: true,
            en: 'AbstractSubStyleSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'abstractSubStyleObjectExtensionGroup',
            col: true,
            en: 'AbstractSubStyleObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'SchemaDataType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'simpleData',
            col: true,
            en: 'SimpleData',
            ti: '.SimpleDataType'
          }, {
            n: 'schemaDataExtension',
            col: true,
            en: 'SchemaDataExtension',
            ti: 'AnyType'
          }, {
            n: 'schemaUrl',
            an: {
              lp: 'schemaUrl'
            },
            t: 'a'
          }]
      }, {
        ln: 'DocumentType',
        bti: '.AbstractContainerType',
        ps: [{
            n: 'schema',
            col: true,
            en: 'Schema',
            ti: '.SchemaType'
          }, {
            n: 'abstractFeatureGroup',
            col: true,
            mx: false,
            dom: false,
            typed: false,
            en: 'AbstractFeatureGroup',
            ti: '.AbstractFeatureType',
            t: 'er'
          }, {
            n: 'documentSimpleExtensionGroup',
            col: true,
            en: 'DocumentSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'documentObjectExtensionGroup',
            col: true,
            en: 'DocumentObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'UpdateType',
        ps: [{
            n: 'targetHref'
          }, {
            n: 'createOrDeleteOrChange',
            col: true,
            etis: [{
                en: 'Create',
                ti: '.CreateType'
              }, {
                en: 'Delete',
                ti: '.DeleteType'
              }, {
                en: 'Change',
                ti: '.ChangeType'
              }, {
                en: 'UpdateOpExtensionGroup',
                ti: 'AnyType'
              }],
            t: 'es'
          }, {
            n: 'updateExtensionGroup',
            col: true,
            en: 'UpdateExtensionGroup',
            ti: 'AnyType'
          }]
      }, {
        ln: 'ScreenOverlayType',
        bti: '.AbstractOverlayType',
        ps: [{
            n: 'overlayXY',
            ti: '.Vec2Type'
          }, {
            n: 'screenXY',
            ti: '.Vec2Type'
          }, {
            n: 'rotationXY',
            ti: '.Vec2Type'
          }, {
            n: 'size',
            ti: '.Vec2Type'
          }, {
            n: 'rotation',
            ti: 'Double'
          }, {
            n: 'screenOverlaySimpleExtensionGroup',
            col: true,
            en: 'ScreenOverlaySimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'screenOverlayObjectExtensionGroup',
            col: true,
            en: 'ScreenOverlayObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'DeleteType',
        ps: [{
            n: 'abstractFeatureGroup',
            col: true,
            mx: false,
            dom: false,
            typed: false,
            en: 'AbstractFeatureGroup',
            ti: '.AbstractFeatureType',
            t: 'er'
          }]
      }, {
        ln: 'MetadataType',
        ps: [{
            n: 'any',
            col: true,
            mx: false,
            t: 'ae'
          }]
      }, {
        ln: 'PointType',
        bti: '.AbstractGeometryType',
        ps: [{
            n: 'extrude',
            ti: 'Boolean'
          }, {
            n: 'altitudeModeGroup',
            mx: false,
            dom: false,
            typed: false,
            ti: 'AnyType',
            t: 'er'
          }, {
            n: 'coordinates',
            ti: {
              t: 'l'
            }
          }, {
            n: 'pointSimpleExtensionGroup',
            col: true,
            en: 'PointSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'pointObjectExtensionGroup',
            col: true,
            en: 'PointObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'SimpleDataType',
        ps: [{
            n: 'value',
            t: 'v'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }]
      }, {
        ln: 'LookAtType',
        bti: '.AbstractViewType',
        ps: [{
            n: 'longitude',
            ti: 'Double'
          }, {
            n: 'latitude',
            ti: 'Double'
          }, {
            n: 'altitude',
            ti: 'Double'
          }, {
            n: 'heading',
            ti: 'Double'
          }, {
            n: 'tilt',
            ti: 'Double'
          }, {
            n: 'range',
            ti: 'Double'
          }, {
            n: 'altitudeModeGroup',
            mx: false,
            dom: false,
            typed: false,
            ti: 'AnyType',
            t: 'er'
          }, {
            n: 'lookAtSimpleExtensionGroup',
            col: true,
            en: 'LookAtSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'lookAtObjectExtensionGroup',
            col: true,
            en: 'LookAtObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'ChangeType',
        ps: [{
            n: 'abstractObjectGroup',
            col: true,
            mx: false,
            dom: false,
            typed: false,
            en: 'AbstractObjectGroup',
            ti: '.AbstractObjectType',
            t: 'er'
          }]
      }, {
        ln: 'AliasType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'targetHref'
          }, {
            n: 'sourceHref'
          }, {
            n: 'aliasSimpleExtensionGroup',
            col: true,
            en: 'AliasSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'aliasObjectExtensionGroup',
            col: true,
            en: 'AliasObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'MultiGeometryType',
        bti: '.AbstractGeometryType',
        ps: [{
            n: 'abstractGeometryGroup',
            col: true,
            mx: false,
            dom: false,
            typed: false,
            en: 'AbstractGeometryGroup',
            ti: '.AbstractGeometryType',
            t: 'er'
          }, {
            n: 'multiGeometrySimpleExtensionGroup',
            col: true,
            en: 'MultiGeometrySimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'multiGeometryObjectExtensionGroup',
            col: true,
            en: 'MultiGeometryObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'SchemaType',
        ps: [{
            n: 'simpleField',
            col: true,
            en: 'SimpleField',
            ti: '.SimpleFieldType'
          }, {
            n: 'schemaExtension',
            col: true,
            en: 'SchemaExtension',
            ti: 'AnyType'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }]
      }, {
        ln: 'LocationType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'longitude',
            ti: 'Double'
          }, {
            n: 'latitude',
            ti: 'Double'
          }, {
            n: 'altitude',
            ti: 'Double'
          }, {
            n: 'locationSimpleExtensionGroup',
            col: true,
            en: 'LocationSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'locationObjectExtensionGroup',
            col: true,
            en: 'LocationObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'PolyStyleType',
        bti: '.AbstractColorStyleType',
        ps: [{
            n: 'fill',
            ti: 'Boolean'
          }, {
            n: 'outline',
            ti: 'Boolean'
          }, {
            n: 'polyStyleSimpleExtensionGroup',
            col: true,
            en: 'PolyStyleSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'polyStyleObjectExtensionGroup',
            col: true,
            en: 'PolyStyleObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'BasicLinkType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'href'
          }, {
            n: 'basicLinkSimpleExtensionGroup',
            col: true,
            en: 'BasicLinkSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'basicLinkObjectExtensionGroup',
            col: true,
            en: 'BasicLinkObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'LineStringType',
        bti: '.AbstractGeometryType',
        ps: [{
            n: 'extrude',
            ti: 'Boolean'
          }, {
            n: 'tessellate',
            ti: 'Boolean'
          }, {
            n: 'altitudeModeGroup',
            mx: false,
            dom: false,
            typed: false,
            ti: 'AnyType',
            t: 'er'
          }, {
            n: 'coordinates',
            ti: {
              t: 'l'
            }
          }, {
            n: 'lineStringSimpleExtensionGroup',
            col: true,
            en: 'LineStringSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'lineStringObjectExtensionGroup',
            col: true,
            en: 'LineStringObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'AbstractTimePrimitiveType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'abstractTimePrimitiveSimpleExtensionGroup',
            col: true,
            en: 'AbstractTimePrimitiveSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'abstractTimePrimitiveObjectExtensionGroup',
            col: true,
            en: 'AbstractTimePrimitiveObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'ExtendedDataType',
        ps: [{
            n: 'data',
            col: true,
            en: 'Data',
            ti: '.DataType'
          }, {
            n: 'schemaData',
            col: true,
            en: 'SchemaData',
            ti: '.SchemaDataType'
          }, {
            n: 'any',
            col: true,
            mx: false,
            t: 'ae'
          }]
      }, {
        ln: 'LinkType',
        bti: '.BasicLinkType',
        ps: [{
            n: 'refreshMode'
          }, {
            n: 'refreshInterval',
            ti: 'Double'
          }, {
            n: 'viewRefreshMode'
          }, {
            n: 'viewRefreshTime',
            ti: 'Double'
          }, {
            n: 'viewBoundScale',
            ti: 'Double'
          }, {
            n: 'viewFormat'
          }, {
            n: 'httpQuery'
          }, {
            n: 'linkSimpleExtensionGroup',
            col: true,
            en: 'LinkSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'linkObjectExtensionGroup',
            col: true,
            en: 'LinkObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'PolygonType',
        bti: '.AbstractGeometryType',
        ps: [{
            n: 'extrude',
            ti: 'Boolean'
          }, {
            n: 'tessellate',
            ti: 'Boolean'
          }, {
            n: 'altitudeModeGroup',
            mx: false,
            dom: false,
            typed: false,
            ti: 'AnyType',
            t: 'er'
          }, {
            n: 'outerBoundaryIs',
            ti: '.BoundaryType'
          }, {
            n: 'innerBoundaryIs',
            col: true,
            ti: '.BoundaryType'
          }, {
            n: 'polygonSimpleExtensionGroup',
            col: true,
            en: 'PolygonSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'polygonObjectExtensionGroup',
            col: true,
            en: 'PolygonObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'DataType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'displayName'
          }, {
            n: 'value'
          }, {
            n: 'dataExtension',
            col: true,
            en: 'DataExtension',
            ti: 'AnyType'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }]
      }, {
        ln: 'OrientationType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'heading',
            ti: 'Double'
          }, {
            n: 'tilt',
            ti: 'Double'
          }, {
            n: 'roll',
            ti: 'Double'
          }, {
            n: 'orientationSimpleExtensionGroup',
            col: true,
            en: 'OrientationSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'orientationObjectExtensionGroup',
            col: true,
            en: 'OrientationObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        ln: 'AbstractStyleSelectorType',
        bti: '.AbstractObjectType',
        ps: [{
            n: 'abstractStyleSelectorSimpleExtensionGroup',
            col: true,
            en: 'AbstractStyleSelectorSimpleExtensionGroup',
            ti: 'AnyType'
          }, {
            n: 'abstractStyleSelectorObjectExtensionGroup',
            col: true,
            en: 'AbstractStyleSelectorObjectExtensionGroup',
            ti: '.AbstractObjectType'
          }]
      }, {
        t: 'enum',
        ln: 'StyleStateEnumType',
        vs: ['normal', 'highlight']
      }, {
        t: 'enum',
        ln: 'ListItemTypeEnumType',
        vs: ['radioFolder', 'check', 'checkHideChildren', 'checkOffOnly']
      }, {
        t: 'enum',
        ln: 'AltitudeModeEnumType',
        vs: ['clampToGround', 'relativeToGround', 'absolute']
      }, {
        t: 'enum',
        ln: 'ViewRefreshModeEnumType',
        vs: ['never', 'onRequest', 'onStop', 'onRegion']
      }, {
        t: 'enum',
        ln: 'RefreshModeEnumType',
        vs: ['onChange', 'onInterval', 'onExpire']
      }, {
        t: 'enum',
        ln: 'UnitsEnumType',
        vs: ['fraction', 'pixels', 'insetPixels']
      }, {
        t: 'enum',
        ln: 'GridOriginEnumType',
        vs: ['lowerLeft', 'upperLeft']
      }, {
        t: 'enum',
        ln: 'ShapeEnumType',
        vs: ['rectangle', 'cylinder', 'sphere']
      }, {
        t: 'enum',
        ln: 'ItemIconStateEnumType',
        vs: ['open', 'closed', 'error', 'fetching0', 'fetching1', 'fetching2']
      }, {
        t: 'enum',
        ln: 'ColorModeEnumType',
        vs: ['normal', 'random']
      }, {
        t: 'enum',
        ln: 'DisplayModeEnumType',
        vs: ['default', 'hide']
      }],
    eis: [{
        en: 'DocumentSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'rotationXY',
        ti: '.Vec2Type'
      }, {
        en: 'CameraObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'ImagePyramidSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'ScreenOverlaySimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'viewFormat'
      }, {
        en: 'styleUrl'
      }, {
        en: 'LodSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'PolyStyleObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'begin'
      }, {
        en: 'maxHeight',
        ti: 'Int'
      }, {
        en: 'LookAtObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'PhotoOverlayObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'size',
        ti: '.Vec2Type'
      }, {
        en: 'scale',
        ti: 'Double'
      }, {
        en: 'latitude',
        ti: 'Double'
      }, {
        en: 'NetworkLinkControlSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'AbstractOverlayGroup',
        ti: '.AbstractOverlayType',
        sh: 'AbstractFeatureGroup'
      }, {
        en: 'SchemaExtension',
        ti: 'AnyType'
      }, {
        en: 'SchemaData',
        ti: '.SchemaDataType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'ViewVolume',
        ti: '.ViewVolumeType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'targetHref'
      }, {
        en: 'expires'
      }, {
        en: 'BasicLinkObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'altitude',
        ti: 'Double'
      }, {
        en: 'east',
        ti: 'Double'
      }, {
        en: 'rotation',
        ti: 'Double'
      }, {
        en: 'AbstractGeometryObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'AbstractFeatureSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'AbstractStyleSelectorObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'href'
      }, {
        en: 'width',
        ti: 'Double'
      }, {
        en: 'ItemIconSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'LatLonAltBoxObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'LatLonAltBox',
        ti: '.LatLonAltBoxType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'LinearRing',
        ti: '.LinearRingType',
        sh: 'AbstractGeometryGroup'
      }, {
        en: 'NetworkLinkControl',
        ti: '.NetworkLinkControlType'
      }, {
        en: 'LatLonBoxSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'open',
        ti: 'Boolean'
      }, {
        en: 'ObjectSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'ImagePyramidObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'ListStyleObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'Change',
        ti: '.ChangeType'
      }, {
        en: 'AbstractFeatureGroup',
        ti: '.AbstractFeatureType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'fill',
        ti: 'Boolean'
      }, {
        en: 'LinkSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'heading',
        ti: 'Double'
      }, {
        en: 'linkDescription'
      }, {
        en: 'AbstractFeatureObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'Url',
        ti: '.LinkType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'LookAtSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'LinearRingObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'Schema',
        ti: '.SchemaType'
      }, {
        en: 'ModelSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'ExtendedData',
        ti: '.ExtendedDataType'
      }, {
        en: 'ScaleObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'ResourceMapSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'maxFadeExtent',
        ti: 'Double'
      }, {
        en: 'LookAt',
        ti: '.LookAtType',
        sh: 'AbstractViewGroup'
      }, {
        en: 'AbstractTimePrimitiveGroup',
        ti: '.AbstractTimePrimitiveType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'TimeSpan',
        ti: '.TimeSpanType',
        sh: 'AbstractTimePrimitiveGroup'
      }, {
        en: 'LabelStyleObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'BalloonStyleSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'leftFov',
        ti: 'Double'
      }, {
        en: 'hotSpot',
        ti: '.Vec2Type'
      }, {
        en: 'Point',
        ti: '.PointType',
        sh: 'AbstractGeometryGroup'
      }, {
        en: 'LatLonBox',
        ti: '.LatLonBoxType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'LineStringSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'tilt',
        ti: 'Double'
      }, {
        en: 'AbstractOverlaySimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'altitudeModeGroup',
        ti: 'AnyType'
      }, {
        en: 'refreshVisibility',
        ti: 'Boolean'
      }, {
        en: 'UpdateOpExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'AbstractLatLonBoxSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'message'
      }, {
        en: 'LocationObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'NetworkLink',
        ti: '.NetworkLinkType',
        sh: 'AbstractFeatureGroup'
      }, {
        en: 'sourceHref'
      }, {
        en: 'minRefreshPeriod',
        ti: 'Double'
      }, {
        en: 'GroundOverlay',
        ti: '.GroundOverlayType',
        sh: 'AbstractOverlayGroup'
      }, {
        en: 'NetworkLinkObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'PolyStyle',
        ti: '.PolyStyleType',
        sh: 'AbstractColorStyleGroup'
      }, {
        en: 'LatLonAltBoxSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'textColor'
      }, {
        en: 'PolygonObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'PointSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'LineStringObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'range',
        ti: 'Double'
      }, {
        en: 'PhotoOverlay',
        ti: '.PhotoOverlayType',
        sh: 'AbstractOverlayGroup'
      }, {
        en: 'MultiGeometrySimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'ItemIcon',
        ti: '.ItemIconType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'Metadata',
        ti: '.MetadataType'
      }, {
        en: 'cookie'
      }, {
        en: 'OrientationSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'Style',
        ti: '.StyleType',
        sh: 'AbstractStyleSelectorGroup'
      }, {
        en: 'displayMode'
      }, {
        en: 'refreshInterval',
        ti: 'Double'
      }, {
        en: 'AbstractStyleSelectorGroup',
        ti: '.AbstractStyleSelectorType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'north',
        ti: 'Double'
      }, {
        en: 'rightFov',
        ti: 'Double'
      }, {
        en: 'LineString',
        ti: '.LineStringType',
        sh: 'AbstractGeometryGroup'
      }, {
        en: 'AbstractGeometrySimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'ListStyle',
        ti: '.ListStyleType',
        sh: 'AbstractSubStyleGroup'
      }, {
        en: 'shape'
      }, {
        en: 'BoundarySimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'outline',
        ti: 'Boolean'
      }, {
        en: 'end'
      }, {
        en: 'snippet'
      }, {
        en: 'Delete',
        ti: '.DeleteType'
      }, {
        en: 'phoneNumber'
      }, {
        en: 'AbstractContainerObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'colorMode'
      }, {
        en: 'overlayXY',
        ti: '.Vec2Type'
      }, {
        en: 'altitudeMode',
        sh: 'altitudeModeGroup'
      }, {
        en: 'maxLodPixels',
        ti: 'Double'
      }, {
        en: 'topFov',
        ti: 'Double'
      }, {
        en: 'BalloonStyle',
        ti: '.BalloonStyleType',
        sh: 'AbstractSubStyleGroup'
      }, {
        en: 'state',
        ti: {
          t: 'l'
        }
      }, {
        en: 'Create',
        ti: '.CreateType'
      }, {
        en: 'Location',
        ti: '.LocationType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'south',
        ti: 'Double'
      }, {
        en: 'Data',
        ti: '.DataType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'tileSize',
        ti: 'Int'
      }, {
        en: 'LabelStyleSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'AbstractColorStyleGroup',
        ti: '.AbstractColorStyleType',
        sh: 'AbstractSubStyleGroup'
      }, {
        en: 'BoundaryObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'NetworkLinkControlObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'PlacemarkObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'maxAltitude',
        ti: 'Double'
      }, {
        en: 'Snippet',
        ti: '.SnippetType'
      }, {
        en: 'GroundOverlaySimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'west',
        ti: 'Double'
      }, {
        en: 'RegionSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'AbstractTimePrimitiveSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'viewRefreshMode'
      }, {
        en: 'SimpleData',
        ti: '.SimpleDataType'
      }, {
        en: 'StyleObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'longitude',
        ti: 'Double'
      }, {
        en: 'maxSnippetLines',
        ti: 'Int'
      }, {
        en: 'AbstractColorStyleSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'SimpleFieldExtension',
        ti: 'AnyType'
      }, {
        en: 'NetworkLinkSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'DocumentObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'LinkObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'FolderSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'AbstractSubStyleObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'LineStyleObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'TimeStampSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'Placemark',
        ti: '.PlacemarkType',
        sh: 'AbstractFeatureGroup'
      }, {
        en: 'kml',
        ti: '.KmlType'
      }, {
        en: 'tessellate',
        ti: 'Boolean'
      }, {
        en: 'name'
      }, {
        en: 'LatLonBoxObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'minFadeExtent',
        ti: 'Double'
      }, {
        en: 'minAltitude',
        ti: 'Double'
      }, {
        en: 'IconStyleObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'outerBoundaryIs',
        ti: '.BoundaryType'
      }, {
        en: 'ItemIconObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'AliasObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'bottomFov',
        ti: 'Double'
      }, {
        en: 'IconStyleSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'PairObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'Alias',
        ti: '.AliasType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'x',
        ti: 'Double'
      }, {
        en: 'AbstractContainerGroup',
        ti: '.AbstractContainerType',
        sh: 'AbstractFeatureGroup'
      }, {
        en: 'UpdateExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'IconStyle',
        ti: '.IconStyleType',
        sh: 'AbstractColorStyleGroup'
      }, {
        en: 'RegionObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'address'
      }, {
        en: 'MultiGeometry',
        ti: '.MultiGeometryType',
        sh: 'AbstractGeometryGroup'
      }, {
        en: 'bgColor'
      }, {
        en: 'Icon',
        ti: '.LinkType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'LinearRingSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'AbstractGeometryGroup',
        ti: '.AbstractGeometryType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'linkName'
      }, {
        en: 'innerBoundaryIs',
        ti: '.BoundaryType'
      }, {
        en: 'Pair',
        ti: '.PairType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'maxSessionLength',
        ti: 'Double'
      }, {
        en: 'AbstractObjectGroup',
        ti: '.AbstractObjectType'
      }, {
        en: 'AbstractSubStyleSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'MultiGeometryObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'PointObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'CameraSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'KmlObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'AbstractViewSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'PairSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'Document',
        ti: '.DocumentType',
        sh: 'AbstractContainerGroup'
      }, {
        en: 'Scale',
        ti: '.ScaleType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'Link',
        ti: '.LinkType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'LineStyle',
        ti: '.LineStyleType',
        sh: 'AbstractColorStyleGroup'
      }, {
        en: 'PolygonSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'SimpleField',
        ti: '.SimpleFieldType'
      }, {
        en: 'SchemaDataExtension',
        ti: 'AnyType'
      }, {
        en: 'Camera',
        ti: '.CameraType',
        sh: 'AbstractViewGroup'
      }, {
        en: 'AbstractOverlayObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'TimeSpanObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'Lod',
        ti: '.LodType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'PlacemarkSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'minLodPixels',
        ti: 'Double'
      }, {
        en: 'viewBoundScale',
        ti: 'Double'
      }, {
        en: 'visibility',
        ti: 'Boolean'
      }, {
        en: 'AbstractStyleSelectorSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'ViewVolumeObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'OrientationObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'text'
      }, {
        en: 'FolderObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'ResourceMapObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'TimeStamp',
        ti: '.TimeStampType',
        sh: 'AbstractTimePrimitiveGroup'
      }, {
        en: 'flyToView',
        ti: 'Boolean'
      }, {
        en: 'viewRefreshTime',
        ti: 'Double'
      }, {
        en: 'StyleMapSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'PhotoOverlaySimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'LabelStyle',
        ti: '.LabelStyleType',
        sh: 'AbstractColorStyleGroup'
      }, {
        en: 'gridOrigin'
      }, {
        en: 'Model',
        ti: '.ModelType',
        sh: 'AbstractGeometryGroup'
      }, {
        en: 'StyleMap',
        ti: '.StyleMapType',
        sh: 'AbstractStyleSelectorGroup'
      }, {
        en: 'near',
        ti: 'Double'
      }, {
        en: 'coordinates',
        ti: {
          t: 'l'
        }
      }, {
        en: 'AbstractViewObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'ModelObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'ListStyleSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'key'
      }, {
        en: 'ImagePyramid',
        ti: '.ImagePyramidType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'BalloonStyleObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'y',
        ti: 'Double'
      }, {
        en: 'drawOrder',
        ti: 'Int'
      }, {
        en: 'PolyStyleSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'value'
      }, {
        en: 'AbstractViewGroup',
        ti: '.AbstractViewType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'ScaleSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'Folder',
        ti: '.FolderType',
        sh: 'AbstractContainerGroup'
      }, {
        en: 'StyleSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'extrude',
        ti: 'Boolean'
      }, {
        en: 'GroundOverlayObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'Polygon',
        ti: '.PolygonType',
        sh: 'AbstractGeometryGroup'
      }, {
        en: 'linkSnippet',
        ti: '.SnippetType'
      }, {
        en: 'KmlSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'AbstractColorStyleObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'Update',
        ti: '.UpdateType'
      }, {
        en: 'LodObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'AbstractContainerSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'LineStyleSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'LocationSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'displayName'
      }, {
        en: 'DataExtension',
        ti: 'AnyType'
      }, {
        en: 'TimeSpanSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'ScreenOverlayObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'when'
      }, {
        en: 'ResourceMap',
        ti: '.ResourceMapType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'StyleMapObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'maxWidth',
        ti: 'Int'
      }, {
        en: 'screenXY',
        ti: '.Vec2Type'
      }, {
        en: 'refreshMode'
      }, {
        en: 'BasicLinkSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'AbstractSubStyleGroup',
        ti: '.AbstractSubStyleType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'description'
      }, {
        en: 'ScreenOverlay',
        ti: '.ScreenOverlayType',
        sh: 'AbstractOverlayGroup'
      }, {
        en: 'AbstractTimePrimitiveObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'TimeStampObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'listItemType'
      }, {
        en: 'color'
      }, {
        en: 'Region',
        ti: '.RegionType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'roll',
        ti: 'Double'
      }, {
        en: 'AbstractLatLonBoxObjectExtensionGroup',
        ti: '.AbstractObjectType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'Orientation',
        ti: '.OrientationType',
        sh: 'AbstractObjectGroup'
      }, {
        en: 'z',
        ti: 'Double'
      }, {
        en: 'ViewVolumeSimpleExtensionGroup',
        ti: 'AnyType'
      }, {
        en: 'httpQuery'
      }, {
        en: 'AliasSimpleExtensionGroup',
        ti: 'AnyType'
      }]
  };
  return {
    KML_2_2_0: KML_2_2_0
  };
};
if (typeof define === 'function' && define.amd) {
  define([], KML_2_2_0_Module_Factory);
}
else {
  var KML_2_2_0_Module = KML_2_2_0_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.KML_2_2_0 = KML_2_2_0_Module.KML_2_2_0;
  }
  else {
    var KML_2_2_0 = KML_2_2_0_Module.KML_2_2_0;
  }
}