var OWC_0_3_1_Module_Factory = function () {
  var OWC_0_3_1 = {
    name: 'OWC_0_3_1',
    defaultElementNamespaceURI: 'http:\/\/www.opengis.net\/ows-context',
    typeInfos: [{
        type: 'classInfo',
        localName: 'ResourceListType',
        propertyInfos: [{
            type: 'element',
            name: 'layer',
            collection: true,
            elementName: 'Layer',
            typeInfo: 'OWC_0_3_1.LayerType'
          }]
      }, {
        type: 'classInfo',
        localName: 'OWSContextType',
        propertyInfos: [{
            type: 'element',
            name: 'general',
            elementName: 'General',
            typeInfo: 'OWC_0_3_1.GeneralType'
          }, {
            type: 'element',
            name: 'resourceList',
            elementName: 'ResourceList',
            typeInfo: 'OWC_0_3_1.ResourceListType'
          }, {
            name: 'version',
            typeInfo: 'String',
            attributeName: 'version',
            type: 'attribute'
          }, {
            name: 'id',
            typeInfo: 'String',
            attributeName: 'id',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'LayerType',
        baseTypeInfo: 'OWC_0_3_1.AbstractResourceType',
        propertyInfos: [{
            type: 'element',
            name: 'dimensionList',
            elementName: 'DimensionList',
            typeInfo: 'OWC_0_3_1.DimensionListType'
          }, {
            type: 'element',
            name: 'responseCRS',
            elementName: 'ResponseCRS',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'parameterList',
            elementName: 'ParameterList',
            typeInfo: 'OWC_0_3_1.ParameterListType'
          }, {
            type: 'element',
            name: 'depth',
            elementName: 'Depth',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'resx',
            elementName: 'Resx',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'resy',
            elementName: 'Resy',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'resz',
            elementName: 'Resz',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'maxFeatures',
            elementName: 'MaxFeatures',
            typeInfo: 'Integer'
          }, {
            type: 'element',
            name: 'filter',
            elementName: {
              localPart: 'Filter',
              namespaceURI: 'http:\/\/www.opengis.net\/ogc'
            },
            typeInfo: 'Filter_1_0_0.FilterType'
          }, {
            type: 'element',
            name: 'inlineGeometry',
            elementName: 'InlineGeometry',
            typeInfo: 'OWC_0_3_1.InlineFeatureCollectionType'
          }, {
            name: 'document',
            collection: true,
            domAllowed: true,
            typedObjectAllowed: true,
            type: 'anyElement'
          }, {
            type: 'element',
            name: 'vendorExtension',
            elementName: 'VendorExtension',
            typeInfo: 'OWC_0_3_1.ExtensionType'
          }, {
            name: 'queryable',
            typeInfo: 'Boolean',
            attributeName: 'queryable',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'ServerType',
        propertyInfos: [{
            type: 'element',
            name: 'onlineResource',
            collection: true,
            elementName: 'OnlineResource',
            typeInfo: 'OWC_0_3_1.OnlineResourceType'
          }, {
            name: '_default',
            typeInfo: 'Boolean',
            attributeName: 'default',
            type: 'attribute'
          }, {
            name: 'service',
            typeInfo: 'String',
            attributeName: 'service',
            type: 'attribute'
          }, {
            name: 'version',
            typeInfo: 'String',
            attributeName: 'version',
            type: 'attribute'
          }, {
            name: 'title',
            typeInfo: 'String',
            attributeName: 'title',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'DimensionType',
        propertyInfos: [{
            name: 'value',
            typeInfo: 'String',
            type: 'value'
          }, {
            name: 'name',
            typeInfo: 'String',
            attributeName: 'name',
            type: 'attribute'
          }, {
            name: 'units',
            typeInfo: 'String',
            attributeName: 'units',
            type: 'attribute'
          }, {
            name: 'unitSymbol',
            typeInfo: 'String',
            attributeName: 'unitSymbol',
            type: 'attribute'
          }, {
            name: 'userValue',
            typeInfo: 'String',
            attributeName: 'userValue',
            type: 'attribute'
          }, {
            name: '_default',
            typeInfo: 'String',
            attributeName: 'default',
            type: 'attribute'
          }, {
            name: 'multipleValues',
            typeInfo: 'Boolean',
            attributeName: 'multipleValues',
            type: 'attribute'
          }, {
            name: 'nearestValue',
            typeInfo: 'Boolean',
            attributeName: 'nearestValue',
            type: 'attribute'
          }, {
            name: 'current',
            typeInfo: 'Boolean',
            attributeName: 'current',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'StyleType',
        propertyInfos: [{
            type: 'element',
            name: 'name',
            elementName: 'Name',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'title',
            elementName: 'Title',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: '_abstract',
            elementName: 'Abstract',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'legendURL',
            elementName: 'LegendURL',
            typeInfo: 'OWC_0_3_1.URLType'
          }, {
            type: 'element',
            name: 'sld',
            elementName: 'SLD',
            typeInfo: 'OWC_0_3_1.SLDType'
          }, {
            name: 'current',
            typeInfo: 'Boolean',
            attributeName: 'current',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'DimensionListType',
        propertyInfos: [{
            type: 'element',
            name: 'dimension',
            collection: true,
            elementName: 'Dimension',
            typeInfo: 'OWC_0_3_1.DimensionType'
          }]
      }, {
        type: 'classInfo',
        localName: 'GeneralType',
        propertyInfos: [{
            type: 'element',
            name: 'window',
            elementName: 'Window',
            typeInfo: 'OWC_0_3_1.WindowType'
          }, {
            name: 'boundingBox',
            elementName: {
              localPart: 'BoundingBox',
              namespaceURI: 'http:\/\/www.opengis.net\/ows'
            },
            typeInfo: 'OWS_1_0_0.BoundingBoxType',
            type: 'elementRef'
          }, {
            type: 'element',
            name: 'minScaleDenominator',
            elementName: {
              localPart: 'MinScaleDenominator',
              namespaceURI: 'http:\/\/www.opengis.net\/sld'
            },
            typeInfo: 'Double'
          }, {
            type: 'element',
            name: 'maxScaleDenominator',
            elementName: {
              localPart: 'MaxScaleDenominator',
              namespaceURI: 'http:\/\/www.opengis.net\/sld'
            },
            typeInfo: 'Double'
          }, {
            type: 'element',
            name: 'title',
            elementName: {
              localPart: 'Title',
              namespaceURI: 'http:\/\/www.opengis.net\/ows'
            },
            typeInfo: 'String'
          }, {
            type: 'element',
            name: '_abstract',
            elementName: {
              localPart: 'Abstract',
              namespaceURI: 'http:\/\/www.opengis.net\/ows'
            },
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'keywords',
            elementName: {
              localPart: 'Keywords',
              namespaceURI: 'http:\/\/www.opengis.net\/ows'
            },
            typeInfo: 'OWS_1_0_0.KeywordsType'
          }, {
            type: 'element',
            name: 'logoURL',
            elementName: 'LogoURL',
            typeInfo: 'OWC_0_3_1.URLType'
          }, {
            type: 'element',
            name: 'descriptionURL',
            elementName: 'DescriptionURL',
            typeInfo: 'OWC_0_3_1.URLType'
          }, {
            type: 'element',
            name: 'serviceProvider',
            elementName: {
              localPart: 'ServiceProvider',
              namespaceURI: 'http:\/\/www.opengis.net\/ows'
            },
            typeInfo: 'OWS_1_0_0.ServiceProvider'
          }, {
            type: 'element',
            name: 'extension',
            elementName: 'Extension',
            typeInfo: 'OWC_0_3_1.ExtensionType'
          }]
      }, {
        type: 'classInfo',
        localName: 'FormatType',
        propertyInfos: [{
            name: 'value',
            typeInfo: 'String',
            type: 'value'
          }, {
            name: 'current',
            typeInfo: 'Boolean',
            attributeName: 'current',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'InlineFeatureCollectionType',
        baseTypeInfo: 'GML_2_1_2.AbstractFeatureCollectionType',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'OnlineResourceType',
        baseTypeInfo: 'OWS_1_0_0.OnlineResourceType',
        propertyInfos: [{
            name: 'method',
            typeInfo: 'String',
            attributeName: 'method',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'StyleListType',
        propertyInfos: [{
            type: 'element',
            name: 'style',
            collection: true,
            elementName: 'Style',
            typeInfo: 'OWC_0_3_1.StyleType'
          }]
      }, {
        type: 'classInfo',
        localName: 'ExtensionType',
        propertyInfos: [{
            name: 'any',
            domAllowed: true,
            typedObjectAllowed: true,
            type: 'anyElement'
          }]
      }, {
        type: 'classInfo',
        localName: 'FormatListType',
        propertyInfos: [{
            type: 'element',
            name: 'format',
            collection: true,
            elementName: 'Format',
            typeInfo: 'OWC_0_3_1.FormatType'
          }]
      }, {
        type: 'classInfo',
        localName: 'AbstractResourceType',
        baseTypeInfo: 'OWS_1_0_0.IdentificationType',
        propertyInfos: [{
            type: 'element',
            name: 'server',
            collection: true,
            elementName: 'Server',
            typeInfo: 'OWC_0_3_1.ServerType'
          }, {
            type: 'element',
            name: 'dataURL',
            elementName: 'DataURL',
            typeInfo: 'OWC_0_3_1.URLType'
          }, {
            type: 'element',
            name: 'metadataURL',
            elementName: 'MetadataURL',
            typeInfo: 'OWC_0_3_1.URLType'
          }, {
            type: 'element',
            name: 'minScaleDenominator',
            elementName: {
              localPart: 'MinScaleDenominator',
              namespaceURI: 'http:\/\/www.opengis.net\/sld'
            },
            typeInfo: 'Double'
          }, {
            type: 'element',
            name: 'maxScaleDenominator',
            elementName: {
              localPart: 'MaxScaleDenominator',
              namespaceURI: 'http:\/\/www.opengis.net\/sld'
            },
            typeInfo: 'Double'
          }, {
            type: 'element',
            name: 'styleList',
            elementName: 'StyleList',
            typeInfo: 'OWC_0_3_1.StyleListType'
          }, {
            type: 'element',
            name: 'extension',
            elementName: 'Extension',
            typeInfo: 'OWC_0_3_1.ExtensionType'
          }, {
            type: 'element',
            name: 'layer',
            collection: true,
            elementName: 'Layer',
            typeInfo: 'OWC_0_3_1.LayerType'
          }, {
            name: 'name',
            typeInfo: 'String',
            attributeName: 'name',
            type: 'attribute'
          }, {
            name: 'id',
            typeInfo: 'String',
            attributeName: 'id',
            type: 'attribute'
          }, {
            name: 'group',
            typeInfo: 'String',
            attributeName: 'group',
            type: 'attribute'
          }, {
            name: 'hidden',
            typeInfo: 'Boolean',
            attributeName: 'hidden',
            type: 'attribute'
          }, {
            name: 'opacity',
            typeInfo: 'Decimal',
            attributeName: 'opacity',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'WindowType',
        propertyInfos: [{
            name: 'width',
            typeInfo: 'Integer',
            attributeName: 'width',
            type: 'attribute'
          }, {
            name: 'height',
            typeInfo: 'Integer',
            attributeName: 'height',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'ParameterListType',
        propertyInfos: [{
            type: 'element',
            name: 'parameter',
            collection: true,
            elementName: 'Parameter',
            typeInfo: 'OWC_0_3_1.ExtensionType'
          }]
      }, {
        type: 'classInfo',
        localName: 'SLDType',
        propertyInfos: [{
            type: 'element',
            name: 'name',
            elementName: 'Name',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'title',
            elementName: 'Title',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'legendURL',
            elementName: 'LegendURL',
            typeInfo: 'OWC_0_3_1.URLType'
          }, {
            type: 'element',
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: 'OWC_0_3_1.OnlineResourceType'
          }, {
            type: 'element',
            name: 'styledLayerDescriptor',
            elementName: {
              localPart: 'StyledLayerDescriptor',
              namespaceURI: 'http:\/\/www.opengis.net\/sld'
            },
            typeInfo: 'SLD_1_0_0.StyledLayerDescriptor'
          }, {
            type: 'element',
            name: 'featureTypeStyle',
            elementName: {
              localPart: 'FeatureTypeStyle',
              namespaceURI: 'http:\/\/www.opengis.net\/sld'
            },
            typeInfo: 'SLD_1_0_0.FeatureTypeStyle'
          }]
      }, {
        type: 'classInfo',
        localName: 'URLType',
        propertyInfos: [{
            type: 'element',
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: 'OWC_0_3_1.OnlineResourceType'
          }, {
            name: 'width',
            typeInfo: 'Integer',
            attributeName: 'width',
            type: 'attribute'
          }, {
            name: 'height',
            typeInfo: 'Integer',
            attributeName: 'height',
            type: 'attribute'
          }, {
            name: 'format',
            typeInfo: 'String',
            attributeName: 'format',
            type: 'attribute'
          }]
      }, {
        type: 'enumInfo',
        localName: 'ServiceType',
        baseTypeInfo: 'String',
        values: ['urn:ogc:serviceType:WMS', 'urn:ogc:serviceType:WFS', 'urn:ogc:serviceType:WCS', 'urn:ogc:serviceType:GML', 'urn:ogc:serviceType:SLD', 'urn:ogc:serviceType:FES', 'urn:ogc:serviceType:KML']
      }, {
        type: 'enumInfo',
        localName: 'MethodType',
        baseTypeInfo: 'String',
        values: ['GET', 'POST']
      }],
    elementInfos: [{
        elementName: 'OWSContext',
        typeInfo: 'OWC_0_3_1.OWSContextType'
      }, {
        elementName: 'Layer',
        typeInfo: 'OWC_0_3_1.LayerType'
      }, {
        elementName: 'ResourceList',
        typeInfo: 'OWC_0_3_1.ResourceListType'
      }]
  };
  return {
    OWC_0_3_1: OWC_0_3_1
  };
};
if (typeof define === 'function' && define.amd) {
  define([], OWC_0_3_1_Module_Factory);
}
else {
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.OWC_0_3_1 = OWC_0_3_1_Module_Factory().OWC_0_3_1;
  }
  else {
    var OWC_0_3_1 = OWC_0_3_1_Module_Factory().OWC_0_3_1;
  }
}