var OWS_1_1_0_Module_Factory = function () {
  var OWS_1_1_0 = {
    name: 'OWS_1_1_0',
    defaultElementNamespaceURI: 'http:\/\/www.opengis.net\/ows\/1.1',
    defaultAttributeNamespaceURI: 'http:\/\/www.w3.org\/1999\/xlink',
    typeInfos: [{
        type: 'classInfo',
        localName: 'OperationsMetadata',
        propertyInfos: [{
            type: 'element',
            name: 'operation',
            collection: true,
            elementName: 'Operation',
            typeInfo: 'OWS_1_1_0.Operation'
          }, {
            type: 'element',
            name: 'parameter',
            collection: true,
            elementName: 'Parameter',
            typeInfo: 'OWS_1_1_0.DomainType'
          }, {
            type: 'element',
            name: 'constraint',
            collection: true,
            elementName: 'Constraint',
            typeInfo: 'OWS_1_1_0.DomainType'
          }, {
            type: 'element',
            name: 'extendedCapabilities',
            elementName: 'ExtendedCapabilities',
            typeInfo: 'AnyType'
          }]
      }, {
        type: 'classInfo',
        localName: 'Operation',
        propertyInfos: [{
            type: 'element',
            name: 'dcp',
            collection: true,
            elementName: 'DCP',
            typeInfo: 'OWS_1_1_0.DCP'
          }, {
            type: 'element',
            name: 'parameter',
            collection: true,
            elementName: 'Parameter',
            typeInfo: 'OWS_1_1_0.DomainType'
          }, {
            type: 'element',
            name: 'constraint',
            collection: true,
            elementName: 'Constraint',
            typeInfo: 'OWS_1_1_0.DomainType'
          }, {
            type: 'element',
            name: 'metadata',
            collection: true,
            elementName: 'Metadata',
            typeInfo: 'OWS_1_1_0.MetadataType'
          }, {
            name: 'name',
            typeInfo: 'String',
            attributeName: {
              localPart: 'name'
            },
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'DCP',
        propertyInfos: [{
            type: 'element',
            name: 'http',
            elementName: 'HTTP',
            typeInfo: 'OWS_1_1_0.HTTP'
          }]
      }, {
        type: 'classInfo',
        localName: 'HTTP',
        propertyInfos: [{
            name: 'getOrPost',
            collection: true,
            elementTypeInfos: [{
                elementName: 'Get',
                typeInfo: 'OWS_1_1_0.RequestMethodType'
              }, {
                elementName: 'Post',
                typeInfo: 'OWS_1_1_0.RequestMethodType'
              }],
            type: 'elementRefs'
          }]
      }, {
        type: 'classInfo',
        localName: 'RequestMethodType',
        baseTypeInfo: 'OWS_1_1_0.OnlineResourceType',
        propertyInfos: [{
            type: 'element',
            name: 'constraint',
            collection: true,
            elementName: 'Constraint',
            typeInfo: 'OWS_1_1_0.DomainType'
          }]
      }, {
        type: 'classInfo',
        localName: 'DomainType',
        baseTypeInfo: 'OWS_1_1_0.UnNamedDomainType',
        propertyInfos: [{
            name: 'name',
            typeInfo: 'String',
            attributeName: {
              localPart: 'name'
            },
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'MetadataType',
        propertyInfos: [{
            type: 'element',
            name: 'abstractMetaData',
            elementName: 'AbstractMetaData',
            typeInfo: 'AnyType'
          }, {
            name: 'about',
            typeInfo: 'String',
            attributeName: {
              localPart: 'about'
            },
            type: 'attribute'
          }, {
            name: 'type',
            typeInfo: 'XLink_1_0.TypeType',
            attributeName: 'type',
            type: 'attribute'
          }, {
            name: 'href',
            typeInfo: 'String',
            attributeName: 'href',
            type: 'attribute'
          }, {
            name: 'role',
            typeInfo: 'String',
            attributeName: 'role',
            type: 'attribute'
          }, {
            name: 'arcrole',
            typeInfo: 'String',
            attributeName: 'arcrole',
            type: 'attribute'
          }, {
            name: 'title',
            typeInfo: 'String',
            attributeName: 'title',
            type: 'attribute'
          }, {
            name: 'show',
            typeInfo: 'XLink_1_0.ShowType',
            attributeName: 'show',
            type: 'attribute'
          }, {
            name: 'actuate',
            typeInfo: 'XLink_1_0.ActuateType',
            attributeName: 'actuate',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'WGS84BoundingBoxType',
        baseTypeInfo: 'OWS_1_1_0.BoundingBoxType',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'BoundingBoxType',
        propertyInfos: [{
            type: 'element',
            name: 'lowerCorner',
            elementName: 'LowerCorner',
            typeInfo: {
              type: 'list',
              typeInfo: 'Double'
            }
          }, {
            type: 'element',
            name: 'upperCorner',
            elementName: 'UpperCorner',
            typeInfo: {
              type: 'list',
              typeInfo: 'Double'
            }
          }, {
            name: 'crs',
            typeInfo: 'String',
            attributeName: {
              localPart: 'crs'
            },
            type: 'attribute'
          }, {
            name: 'dimensions',
            typeInfo: 'Integer',
            attributeName: {
              localPart: 'dimensions'
            },
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'DomainMetadataType',
        propertyInfos: [{
            name: 'value',
            typeInfo: 'String',
            type: 'value'
          }, {
            name: 'reference',
            typeInfo: 'String',
            attributeName: {
              localPart: 'reference',
              namespaceURI: 'http:\/\/www.opengis.net\/ows\/1.1'
            },
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'CodeType',
        propertyInfos: [{
            name: 'value',
            typeInfo: 'String',
            type: 'value'
          }, {
            name: 'codeSpace',
            typeInfo: 'String',
            attributeName: {
              localPart: 'codeSpace'
            },
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'ValuesReference',
        propertyInfos: [{
            name: 'value',
            typeInfo: 'String',
            type: 'value'
          }, {
            name: 'reference',
            typeInfo: 'String',
            attributeName: {
              localPart: 'reference',
              namespaceURI: 'http:\/\/www.opengis.net\/ows\/1.1'
            },
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'ContactType',
        propertyInfos: [{
            type: 'element',
            name: 'phone',
            elementName: 'Phone',
            typeInfo: 'OWS_1_1_0.TelephoneType'
          }, {
            type: 'element',
            name: 'address',
            elementName: 'Address',
            typeInfo: 'OWS_1_1_0.AddressType'
          }, {
            type: 'element',
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: 'OWS_1_1_0.OnlineResourceType'
          }, {
            type: 'element',
            name: 'hoursOfService',
            elementName: 'HoursOfService',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'contactInstructions',
            elementName: 'ContactInstructions',
            typeInfo: 'String'
          }]
      }, {
        type: 'classInfo',
        localName: 'ServiceIdentification',
        baseTypeInfo: 'OWS_1_1_0.DescriptionType',
        propertyInfos: [{
            type: 'element',
            name: 'serviceType',
            elementName: 'ServiceType',
            typeInfo: 'OWS_1_1_0.CodeType'
          }, {
            type: 'element',
            name: 'serviceTypeVersion',
            collection: true,
            elementName: 'ServiceTypeVersion',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'profile',
            collection: true,
            elementName: 'Profile',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'fees',
            elementName: 'Fees',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'accessConstraints',
            collection: true,
            elementName: 'AccessConstraints',
            typeInfo: 'String'
          }]
      }, {
        type: 'classInfo',
        localName: 'DescriptionType',
        propertyInfos: [{
            type: 'element',
            name: 'title',
            collection: true,
            elementName: 'Title',
            typeInfo: 'OWS_1_1_0.LanguageStringType'
          }, {
            type: 'element',
            name: '_abstract',
            collection: true,
            elementName: 'Abstract',
            typeInfo: 'OWS_1_1_0.LanguageStringType'
          }, {
            type: 'element',
            name: 'keywords',
            collection: true,
            elementName: 'Keywords',
            typeInfo: 'OWS_1_1_0.KeywordsType'
          }]
      }, {
        type: 'classInfo',
        localName: 'LanguageStringType',
        propertyInfos: [{
            name: 'value',
            typeInfo: 'String',
            type: 'value'
          }, {
            name: 'lang',
            typeInfo: 'String',
            attributeName: {
              localPart: 'lang',
              namespaceURI: 'http:\/\/www.w3.org\/XML\/1998\/namespace'
            },
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'KeywordsType',
        propertyInfos: [{
            type: 'element',
            name: 'keyword',
            collection: true,
            elementName: 'Keyword',
            typeInfo: 'OWS_1_1_0.LanguageStringType'
          }, {
            type: 'element',
            name: 'type',
            elementName: 'Type',
            typeInfo: 'OWS_1_1_0.CodeType'
          }]
      }, {
        type: 'classInfo',
        localName: 'ReferenceGroupType',
        baseTypeInfo: 'OWS_1_1_0.BasicIdentificationType',
        propertyInfos: [{
            name: 'abstractReferenceBase',
            collection: true,
            elementName: 'AbstractReferenceBase',
            typeInfo: 'OWS_1_1_0.AbstractReferenceBaseType',
            type: 'elementRef'
          }]
      }, {
        type: 'classInfo',
        localName: 'GetResourceByIdType',
        propertyInfos: [{
            type: 'element',
            name: 'resourceID',
            collection: true,
            elementName: 'ResourceID',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'outputFormat',
            elementName: 'OutputFormat',
            typeInfo: 'String'
          }, {
            name: 'service',
            typeInfo: 'String',
            attributeName: {
              localPart: 'service'
            },
            type: 'attribute'
          }, {
            name: 'version',
            typeInfo: 'String',
            attributeName: {
              localPart: 'version'
            },
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'AllowedValues',
        propertyInfos: [{
            name: 'valueOrRange',
            collection: true,
            elementTypeInfos: [{
                elementName: 'Value',
                typeInfo: 'OWS_1_1_0.ValueType'
              }, {
                elementName: 'Range',
                typeInfo: 'OWS_1_1_0.RangeType'
              }],
            type: 'elements'
          }]
      }, {
        type: 'classInfo',
        localName: 'ValueType',
        propertyInfos: [{
            name: 'value',
            typeInfo: 'String',
            type: 'value'
          }]
      }, {
        type: 'classInfo',
        localName: 'RangeType',
        propertyInfos: [{
            type: 'element',
            name: 'minimumValue',
            elementName: 'MinimumValue',
            typeInfo: 'OWS_1_1_0.ValueType'
          }, {
            type: 'element',
            name: 'maximumValue',
            elementName: 'MaximumValue',
            typeInfo: 'OWS_1_1_0.ValueType'
          }, {
            type: 'element',
            name: 'spacing',
            elementName: 'Spacing',
            typeInfo: 'OWS_1_1_0.ValueType'
          }, {
            name: 'rangeClosure',
            typeInfo: {
              type: 'list',
              typeInfo: 'String'
            },
            attributeName: {
              localPart: 'rangeClosure',
              namespaceURI: 'http:\/\/www.opengis.net\/ows\/1.1'
            },
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'AbstractReferenceBaseType',
        propertyInfos: [{
            name: 'type',
            typeInfo: 'String',
            attributeName: {
              localPart: 'type',
              namespaceURI: 'http:\/\/www.opengis.net\/ows\/1.1'
            },
            type: 'attribute'
          }, {
            name: 'href',
            typeInfo: 'String',
            attributeName: 'href',
            type: 'attribute'
          }, {
            name: 'role',
            typeInfo: 'String',
            attributeName: 'role',
            type: 'attribute'
          }, {
            name: 'arcrole',
            typeInfo: 'String',
            attributeName: 'arcrole',
            type: 'attribute'
          }, {
            name: 'title',
            typeInfo: 'String',
            attributeName: 'title',
            type: 'attribute'
          }, {
            name: 'show',
            typeInfo: 'XLink_1_0.ShowType',
            attributeName: 'show',
            type: 'attribute'
          }, {
            name: 'actuate',
            typeInfo: 'XLink_1_0.ActuateType',
            attributeName: 'actuate',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'ServiceReferenceType',
        baseTypeInfo: 'OWS_1_1_0.ReferenceType',
        propertyInfos: [{
            type: 'element',
            name: 'requestMessage',
            elementName: 'RequestMessage',
            typeInfo: 'AnyType'
          }, {
            type: 'element',
            name: 'requestMessageReference',
            elementName: 'RequestMessageReference',
            typeInfo: 'String'
          }]
      }, {
        type: 'classInfo',
        localName: 'ReferenceType',
        baseTypeInfo: 'OWS_1_1_0.AbstractReferenceBaseType',
        propertyInfos: [{
            type: 'element',
            name: 'identifier',
            elementName: 'Identifier',
            typeInfo: 'OWS_1_1_0.CodeType'
          }, {
            type: 'element',
            name: '_abstract',
            collection: true,
            elementName: 'Abstract',
            typeInfo: 'OWS_1_1_0.LanguageStringType'
          }, {
            type: 'element',
            name: 'format',
            elementName: 'Format',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'metadata',
            collection: true,
            elementName: 'Metadata',
            typeInfo: 'OWS_1_1_0.MetadataType'
          }]
      }, {
        type: 'classInfo',
        localName: 'ServiceProvider',
        propertyInfos: [{
            type: 'element',
            name: 'providerName',
            elementName: 'ProviderName',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'providerSite',
            elementName: 'ProviderSite',
            typeInfo: 'OWS_1_1_0.OnlineResourceType'
          }, {
            type: 'element',
            name: 'serviceContact',
            elementName: 'ServiceContact',
            typeInfo: 'OWS_1_1_0.ResponsiblePartySubsetType'
          }]
      }, {
        type: 'classInfo',
        localName: 'OnlineResourceType',
        propertyInfos: [{
            name: 'type',
            typeInfo: 'XLink_1_0.TypeType',
            attributeName: 'type',
            type: 'attribute'
          }, {
            name: 'href',
            typeInfo: 'String',
            attributeName: 'href',
            type: 'attribute'
          }, {
            name: 'role',
            typeInfo: 'String',
            attributeName: 'role',
            type: 'attribute'
          }, {
            name: 'arcrole',
            typeInfo: 'String',
            attributeName: 'arcrole',
            type: 'attribute'
          }, {
            name: 'title',
            typeInfo: 'String',
            attributeName: 'title',
            type: 'attribute'
          }, {
            name: 'show',
            typeInfo: 'XLink_1_0.ShowType',
            attributeName: 'show',
            type: 'attribute'
          }, {
            name: 'actuate',
            typeInfo: 'XLink_1_0.ActuateType',
            attributeName: 'actuate',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'ResponsiblePartySubsetType',
        propertyInfos: [{
            type: 'element',
            name: 'individualName',
            elementName: 'IndividualName',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'positionName',
            elementName: 'PositionName',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'contactInfo',
            elementName: 'ContactInfo',
            typeInfo: 'OWS_1_1_0.ContactType'
          }, {
            type: 'element',
            name: 'role',
            elementName: 'Role',
            typeInfo: 'OWS_1_1_0.CodeType'
          }]
      }, {
        type: 'classInfo',
        localName: 'ExceptionReport',
        propertyInfos: [{
            type: 'element',
            name: 'exception',
            collection: true,
            elementName: 'Exception',
            typeInfo: 'OWS_1_1_0.ExceptionType'
          }, {
            name: 'version',
            typeInfo: 'String',
            attributeName: {
              localPart: 'version'
            },
            type: 'attribute'
          }, {
            name: 'lang',
            typeInfo: 'String',
            attributeName: {
              localPart: 'lang',
              namespaceURI: 'http:\/\/www.w3.org\/XML\/1998\/namespace'
            },
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'ExceptionType',
        propertyInfos: [{
            type: 'element',
            name: 'exceptionText',
            collection: true,
            elementName: 'ExceptionText',
            typeInfo: 'String'
          }, {
            name: 'exceptionCode',
            typeInfo: 'String',
            attributeName: {
              localPart: 'exceptionCode'
            },
            type: 'attribute'
          }, {
            name: 'locator',
            typeInfo: 'String',
            attributeName: {
              localPart: 'locator'
            },
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'GetCapabilitiesType',
        propertyInfos: [{
            type: 'element',
            name: 'acceptVersions',
            elementName: 'AcceptVersions',
            typeInfo: 'OWS_1_1_0.AcceptVersionsType'
          }, {
            type: 'element',
            name: 'sections',
            elementName: 'Sections',
            typeInfo: 'OWS_1_1_0.SectionsType'
          }, {
            type: 'element',
            name: 'acceptFormats',
            elementName: 'AcceptFormats',
            typeInfo: 'OWS_1_1_0.AcceptFormatsType'
          }, {
            name: 'updateSequence',
            typeInfo: 'String',
            attributeName: {
              localPart: 'updateSequence'
            },
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'NoValues',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'ManifestType',
        baseTypeInfo: 'OWS_1_1_0.BasicIdentificationType',
        propertyInfos: [{
            type: 'element',
            name: 'referenceGroup',
            collection: true,
            elementName: 'ReferenceGroup',
            typeInfo: 'OWS_1_1_0.ReferenceGroupType'
          }]
      }, {
        type: 'classInfo',
        localName: 'DatasetDescriptionSummaryBaseType',
        baseTypeInfo: 'OWS_1_1_0.DescriptionType',
        propertyInfos: [{
            type: 'element',
            name: 'wgs84BoundingBox',
            collection: true,
            elementName: 'WGS84BoundingBox',
            typeInfo: 'OWS_1_1_0.WGS84BoundingBoxType'
          }, {
            type: 'element',
            name: 'identifier',
            elementName: 'Identifier',
            typeInfo: 'OWS_1_1_0.CodeType'
          }, {
            name: 'boundingBox',
            collection: true,
            elementName: 'BoundingBox',
            typeInfo: 'OWS_1_1_0.BoundingBoxType',
            type: 'elementRef'
          }, {
            type: 'element',
            name: 'metadata',
            collection: true,
            elementName: 'Metadata',
            typeInfo: 'OWS_1_1_0.MetadataType'
          }, {
            type: 'element',
            name: 'datasetDescriptionSummary',
            collection: true,
            elementName: 'DatasetDescriptionSummary',
            typeInfo: 'OWS_1_1_0.DatasetDescriptionSummaryBaseType'
          }]
      }, {
        type: 'classInfo',
        localName: 'ResponsiblePartyType',
        propertyInfos: [{
            type: 'element',
            name: 'individualName',
            elementName: 'IndividualName',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'organisationName',
            elementName: 'OrganisationName',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'positionName',
            elementName: 'PositionName',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'contactInfo',
            elementName: 'ContactInfo',
            typeInfo: 'OWS_1_1_0.ContactType'
          }, {
            type: 'element',
            name: 'role',
            elementName: 'Role',
            typeInfo: 'OWS_1_1_0.CodeType'
          }]
      }, {
        type: 'classInfo',
        localName: 'AnyValue',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'BasicIdentificationType',
        baseTypeInfo: 'OWS_1_1_0.DescriptionType',
        propertyInfos: [{
            type: 'element',
            name: 'identifier',
            elementName: 'Identifier',
            typeInfo: 'OWS_1_1_0.CodeType'
          }, {
            type: 'element',
            name: 'metadata',
            collection: true,
            elementName: 'Metadata',
            typeInfo: 'OWS_1_1_0.MetadataType'
          }]
      }, {
        type: 'classInfo',
        localName: 'TelephoneType',
        propertyInfos: [{
            type: 'element',
            name: 'voice',
            collection: true,
            elementName: 'Voice',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'facsimile',
            collection: true,
            elementName: 'Facsimile',
            typeInfo: 'String'
          }]
      }, {
        type: 'classInfo',
        localName: 'ContentsBaseType',
        propertyInfos: [{
            type: 'element',
            name: 'datasetDescriptionSummary',
            collection: true,
            elementName: 'DatasetDescriptionSummary',
            typeInfo: 'OWS_1_1_0.DatasetDescriptionSummaryBaseType'
          }, {
            type: 'element',
            name: 'otherSource',
            collection: true,
            elementName: 'OtherSource',
            typeInfo: 'OWS_1_1_0.MetadataType'
          }]
      }, {
        type: 'classInfo',
        localName: 'CapabilitiesBaseType',
        propertyInfos: [{
            type: 'element',
            name: 'serviceIdentification',
            elementName: 'ServiceIdentification',
            typeInfo: 'OWS_1_1_0.ServiceIdentification'
          }, {
            type: 'element',
            name: 'serviceProvider',
            elementName: 'ServiceProvider',
            typeInfo: 'OWS_1_1_0.ServiceProvider'
          }, {
            type: 'element',
            name: 'operationsMetadata',
            elementName: 'OperationsMetadata',
            typeInfo: 'OWS_1_1_0.OperationsMetadata'
          }, {
            name: 'version',
            typeInfo: 'String',
            attributeName: {
              localPart: 'version'
            },
            type: 'attribute'
          }, {
            name: 'updateSequence',
            typeInfo: 'String',
            attributeName: {
              localPart: 'updateSequence'
            },
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'UnNamedDomainType',
        propertyInfos: [{
            type: 'element',
            name: 'allowedValues',
            elementName: 'AllowedValues',
            typeInfo: 'OWS_1_1_0.AllowedValues'
          }, {
            type: 'element',
            name: 'anyValue',
            elementName: 'AnyValue',
            typeInfo: 'OWS_1_1_0.AnyValue'
          }, {
            type: 'element',
            name: 'noValues',
            elementName: 'NoValues',
            typeInfo: 'OWS_1_1_0.NoValues'
          }, {
            type: 'element',
            name: 'valuesReference',
            elementName: 'ValuesReference',
            typeInfo: 'OWS_1_1_0.ValuesReference'
          }, {
            type: 'element',
            name: 'defaultValue',
            elementName: 'DefaultValue',
            typeInfo: 'OWS_1_1_0.ValueType'
          }, {
            type: 'element',
            name: 'meaning',
            elementName: 'Meaning',
            typeInfo: 'OWS_1_1_0.DomainMetadataType'
          }, {
            type: 'element',
            name: 'dataType',
            elementName: 'DataType',
            typeInfo: 'OWS_1_1_0.DomainMetadataType'
          }, {
            type: 'element',
            name: 'uom',
            elementName: 'UOM',
            typeInfo: 'OWS_1_1_0.DomainMetadataType'
          }, {
            type: 'element',
            name: 'referenceSystem',
            elementName: 'ReferenceSystem',
            typeInfo: 'OWS_1_1_0.DomainMetadataType'
          }, {
            type: 'element',
            name: 'metadata',
            collection: true,
            elementName: 'Metadata',
            typeInfo: 'OWS_1_1_0.MetadataType'
          }]
      }, {
        type: 'classInfo',
        localName: 'AcceptVersionsType',
        propertyInfos: [{
            type: 'element',
            name: 'version',
            collection: true,
            elementName: 'Version',
            typeInfo: 'String'
          }]
      }, {
        type: 'classInfo',
        localName: 'IdentificationType',
        baseTypeInfo: 'OWS_1_1_0.BasicIdentificationType',
        propertyInfos: [{
            name: 'boundingBox',
            collection: true,
            elementName: 'BoundingBox',
            typeInfo: 'OWS_1_1_0.BoundingBoxType',
            type: 'elementRef'
          }, {
            type: 'element',
            name: 'outputFormat',
            collection: true,
            elementName: 'OutputFormat',
            typeInfo: 'String'
          }, {
            name: 'availableCRS',
            collection: true,
            elementName: 'AvailableCRS',
            typeInfo: 'String',
            type: 'elementRef'
          }]
      }, {
        type: 'classInfo',
        localName: 'AcceptFormatsType',
        propertyInfos: [{
            type: 'element',
            name: 'outputFormat',
            collection: true,
            elementName: 'OutputFormat',
            typeInfo: 'String'
          }]
      }, {
        type: 'classInfo',
        localName: 'SectionsType',
        propertyInfos: [{
            type: 'element',
            name: 'section',
            collection: true,
            elementName: 'Section',
            typeInfo: 'String'
          }]
      }, {
        type: 'classInfo',
        localName: 'AddressType',
        propertyInfos: [{
            type: 'element',
            name: 'deliveryPoint',
            collection: true,
            elementName: 'DeliveryPoint',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'city',
            elementName: 'City',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'administrativeArea',
            elementName: 'AdministrativeArea',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'postalCode',
            elementName: 'PostalCode',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'country',
            elementName: 'Country',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'electronicMailAddress',
            collection: true,
            elementName: 'ElectronicMailAddress',
            typeInfo: 'String'
          }]
      }],
    elementInfos: [{
        elementName: 'OperationsMetadata',
        typeInfo: 'OWS_1_1_0.OperationsMetadata'
      }, {
        elementName: 'Operation',
        typeInfo: 'OWS_1_1_0.Operation'
      }, {
        elementName: 'DCP',
        typeInfo: 'OWS_1_1_0.DCP'
      }, {
        elementName: 'HTTP',
        typeInfo: 'OWS_1_1_0.HTTP'
      }, {
        elementName: 'ValuesReference',
        typeInfo: 'OWS_1_1_0.ValuesReference'
      }, {
        elementName: 'ServiceIdentification',
        typeInfo: 'OWS_1_1_0.ServiceIdentification'
      }, {
        elementName: 'AllowedValues',
        typeInfo: 'OWS_1_1_0.AllowedValues'
      }, {
        elementName: 'ServiceProvider',
        typeInfo: 'OWS_1_1_0.ServiceProvider'
      }, {
        elementName: 'ExceptionReport',
        typeInfo: 'OWS_1_1_0.ExceptionReport'
      }, {
        elementName: 'NoValues',
        typeInfo: 'OWS_1_1_0.NoValues'
      }, {
        elementName: 'AnyValue',
        typeInfo: 'OWS_1_1_0.AnyValue'
      }, {
        elementName: 'Metadata',
        typeInfo: 'OWS_1_1_0.MetadataType'
      }, {
        elementName: 'MaximumValue',
        typeInfo: 'OWS_1_1_0.ValueType'
      }, {
        elementName: 'WGS84BoundingBox',
        typeInfo: 'OWS_1_1_0.WGS84BoundingBoxType',
        substitutionHead: 'BoundingBox'
      }, {
        elementName: 'ReferenceSystem',
        typeInfo: 'OWS_1_1_0.DomainMetadataType'
      }, {
        elementName: 'Keywords',
        typeInfo: 'OWS_1_1_0.KeywordsType'
      }, {
        elementName: 'OrganisationName',
        typeInfo: 'String'
      }, {
        elementName: 'DataType',
        typeInfo: 'OWS_1_1_0.DomainMetadataType'
      }, {
        elementName: 'ContactInfo',
        typeInfo: 'OWS_1_1_0.ContactType'
      }, {
        elementName: 'InputData',
        typeInfo: 'OWS_1_1_0.ManifestType'
      }, {
        elementName: 'AbstractMetaData',
        typeInfo: 'AnyType'
      }, {
        elementName: 'IndividualName',
        typeInfo: 'String'
      }, {
        elementName: 'DefaultValue',
        typeInfo: 'OWS_1_1_0.ValueType'
      }, {
        elementName: 'OtherSource',
        typeInfo: 'OWS_1_1_0.MetadataType'
      }, {
        elementName: 'Identifier',
        typeInfo: 'OWS_1_1_0.CodeType'
      }, {
        elementName: 'Language',
        typeInfo: 'String'
      }, {
        elementName: 'GetCapabilities',
        typeInfo: 'OWS_1_1_0.GetCapabilitiesType'
      }, {
        elementName: 'BoundingBox',
        typeInfo: 'OWS_1_1_0.BoundingBoxType'
      }, {
        elementName: 'Resource',
        typeInfo: 'AnyType'
      }, {
        elementName: 'OutputFormat',
        typeInfo: 'String'
      }, {
        elementName: 'Title',
        typeInfo: 'OWS_1_1_0.LanguageStringType'
      }, {
        elementName: 'Spacing',
        typeInfo: 'OWS_1_1_0.ValueType'
      }, {
        elementName: 'Fees',
        typeInfo: 'String'
      }, {
        elementName: 'Range',
        typeInfo: 'OWS_1_1_0.RangeType'
      }, {
        elementName: 'Manifest',
        typeInfo: 'OWS_1_1_0.ManifestType'
      }, {
        elementName: 'Exception',
        typeInfo: 'OWS_1_1_0.ExceptionType'
      }, {
        elementName: 'AbstractReferenceBase',
        typeInfo: 'OWS_1_1_0.AbstractReferenceBaseType'
      }, {
        elementName: 'ServiceReference',
        typeInfo: 'OWS_1_1_0.ServiceReferenceType',
        substitutionHead: 'Reference'
      }, {
        elementName: 'ReferenceGroup',
        typeInfo: 'OWS_1_1_0.ReferenceGroupType'
      }, {
        elementName: 'AccessConstraints',
        typeInfo: 'String'
      }, {
        elementName: 'ExtendedCapabilities',
        typeInfo: 'AnyType'
      }, {
        elementName: 'GetResourceByID',
        typeInfo: 'OWS_1_1_0.GetResourceByIdType'
      }, {
        elementName: 'DatasetDescriptionSummary',
        typeInfo: 'OWS_1_1_0.DatasetDescriptionSummaryBaseType'
      }, {
        elementName: 'PositionName',
        typeInfo: 'String'
      }, {
        elementName: 'Abstract',
        typeInfo: 'OWS_1_1_0.LanguageStringType'
      }, {
        elementName: 'Reference',
        typeInfo: 'OWS_1_1_0.ReferenceType',
        substitutionHead: 'AbstractReferenceBase'
      }, {
        elementName: 'Value',
        typeInfo: 'OWS_1_1_0.ValueType'
      }, {
        elementName: 'AvailableCRS',
        typeInfo: 'String'
      }, {
        elementName: 'MinimumValue',
        typeInfo: 'OWS_1_1_0.ValueType'
      }, {
        elementName: 'OperationResponse',
        typeInfo: 'OWS_1_1_0.ManifestType'
      }, {
        elementName: 'Meaning',
        typeInfo: 'OWS_1_1_0.DomainMetadataType'
      }, {
        elementName: 'SupportedCRS',
        typeInfo: 'String',
        substitutionHead: 'AvailableCRS'
      }, {
        elementName: 'Role',
        typeInfo: 'OWS_1_1_0.CodeType'
      }, {
        elementName: 'UOM',
        typeInfo: 'OWS_1_1_0.DomainMetadataType'
      }, {
        elementName: 'PointOfContact',
        typeInfo: 'OWS_1_1_0.ResponsiblePartyType'
      }, {
        elementName: 'Post',
        typeInfo: 'OWS_1_1_0.RequestMethodType',
        scope: 'OWS_1_1_0.HTTP'
      }, {
        elementName: 'Get',
        typeInfo: 'OWS_1_1_0.RequestMethodType',
        scope: 'OWS_1_1_0.HTTP'
      }]
  };
  return {
    OWS_1_1_0: OWS_1_1_0
  };
};
if (typeof define === 'function' && define.amd) {
  define([], OWS_1_1_0_Module_Factory);
}
else {
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.OWS_1_1_0 = OWS_1_1_0_Module_Factory().OWS_1_1_0;
  }
  else {
    var OWS_1_1_0 = OWS_1_1_0_Module_Factory().OWS_1_1_0;
  }
}