var SensorML_1_0_1_Module_Factory = function () {
  var SensorML_1_0_1 = {
    n: 'SensorML_1_0_1',
    dens: 'http:\/\/www.opengis.net\/sensorML\/1.0.1',
    dans: 'http:\/\/www.w3.org\/1999\/xlink',
    deps: ['SWE_1_0_1', 'XLink_1_0', 'GML_3_1_1', 'IC_2_0'],
    tis: [{
        ln: 'ContactList',
        ps: [{
            n: 'description',
            en: {
              lp: 'description',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            ti: 'GML_3_1_1.StringOrRefType'
          }, {
            n: 'member',
            col: true,
            ti: '.ContactList.Member'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }]
      }, {
        ln: 'Outputs.OutputList',
        ps: [{
            n: 'output',
            col: true,
            ti: '.IoComponentPropertyType'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }]
      }, {
        ln: 'Inputs.InputList',
        ps: [{
            n: 'input',
            col: true,
            ti: '.IoComponentPropertyType'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }]
      }, {
        ln: 'IoComponentPropertyType',
        ps: [{
            n: 'count',
            en: {
              lp: 'Count',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.Count'
          }, {
            n: 'quantity',
            en: {
              lp: 'Quantity',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.Quantity'
          }, {
            n: 'time',
            en: {
              lp: 'Time',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.Time'
          }, {
            n: '_boolean',
            en: {
              lp: 'Boolean',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.Boolean'
          }, {
            n: 'category',
            en: {
              lp: 'Category',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.Category'
          }, {
            n: 'text',
            en: {
              lp: 'Text',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.Text'
          }, {
            n: 'quantityRange',
            en: {
              lp: 'QuantityRange',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.QuantityRange'
          }, {
            n: 'countRange',
            en: {
              lp: 'CountRange',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.CountRange'
          }, {
            n: 'timeRange',
            en: {
              lp: 'TimeRange',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.TimeRange'
          }, {
            n: 'abstractDataRecord',
            mx: false,
            dom: false,
            typed: false,
            en: {
              lp: 'AbstractDataRecord',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.AbstractDataRecordType',
            t: 'er'
          }, {
            n: 'abstractDataArray',
            mx: false,
            dom: false,
            typed: false,
            en: {
              lp: 'AbstractDataArray',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.AbstractDataArrayType',
            t: 'er'
          }, {
            n: 'observableProperty',
            en: {
              lp: 'ObservableProperty',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.ObservableProperty'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'ComponentArrayType',
        bti: '.AbstractDerivableComponentType',
        ps: [{
            n: 'inputs',
            ti: '.Inputs'
          }, {
            n: 'outputs',
            ti: '.Outputs'
          }, {
            n: 'parameters',
            ti: '.ComponentArrayType.Parameters'
          }, {
            n: 'components',
            ti: '.Components'
          }, {
            n: 'positions',
            ti: '.Positions'
          }, {
            n: 'connections',
            ti: '.Connections'
          }]
      }, {
        ln: 'ArrayLink.SourceIndex',
        ps: [{
            n: 'ref',
            an: {
              lp: 'ref'
            },
            t: 'a'
          }]
      }, {
        ln: 'Interface',
        ps: [{
            n: 'interfaceDefinition',
            en: 'InterfaceDefinition',
            ti: '.InterfaceDefinition'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Event',
        ps: [{
            n: 'date'
          }, {
            n: 'description',
            en: {
              lp: 'description',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            ti: 'GML_3_1_1.StringOrRefType'
          }, {
            n: 'keywords',
            col: true,
            ti: '.Keywords'
          }, {
            n: 'identification',
            col: true,
            ti: '.Identification'
          }, {
            n: 'classification',
            col: true,
            ti: '.Classification'
          }, {
            n: 'contact',
            col: true,
            ti: '.Contact'
          }, {
            n: 'documentation',
            col: true,
            ti: '.Documentation'
          }, {
            n: 'property',
            col: true,
            ti: 'SWE_1_0_1.DataComponentPropertyType'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }]
      }, {
        ln: 'Components',
        ps: [{
            n: 'componentList',
            en: 'ComponentList',
            ti: '.Components.ComponentList'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'RuleLanguageType',
        ps: [{
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'AbstractListType',
        ps: [{
            n: 'otherAttributes',
            t: 'aa'
          }, {
            n: 'any',
            col: true,
            typed: false,
            mx: false,
            t: 'ae'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }]
      }, {
        ln: 'DocumentList',
        ps: [{
            n: 'description',
            en: {
              lp: 'description',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            ti: 'GML_3_1_1.StringOrRefType'
          }, {
            n: 'member',
            col: true,
            ti: '.DocumentList.Member'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }]
      }, {
        ln: 'Rights',
        ps: [{
            n: 'documentation',
            ti: '.Documentation'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'privacyAct',
            ti: 'Boolean',
            an: {
              lp: 'privacyAct'
            },
            t: 'a'
          }, {
            n: 'intellectualPropertyRights',
            ti: 'Boolean',
            an: {
              lp: 'intellectualPropertyRights'
            },
            t: 'a'
          }, {
            n: 'copyRights',
            ti: 'Boolean',
            an: {
              lp: 'copyRights'
            },
            t: 'a'
          }]
      }, {
        ln: 'Parameters.ParameterList',
        ps: [{
            n: 'parameter',
            col: true,
            ti: 'SWE_1_0_1.DataComponentPropertyType'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }]
      }, {
        ln: 'ContactInfo.Phone',
        ps: [{
            n: 'voice',
            col: true
          }, {
            n: 'facsimile',
            col: true
          }]
      }, {
        ln: 'ProcessMethodType.Implementation',
        ps: [{
            n: 'processChain',
            en: 'ProcessChain',
            ti: '.ProcessChainType'
          }, {
            n: 'implementationCode',
            en: 'ImplementationCode',
            ti: '.ProcessMethodType.Implementation.ImplementationCode'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'DataSourcesPropertyType',
        ps: [{
            n: 'dataSourceList',
            en: 'DataSourceList',
            ti: '.AbstractListType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Identification.IdentifierList',
        ps: [{
            n: 'identifier',
            col: true,
            ti: '.Identification.IdentifierList.Identifier'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }]
      }, {
        ln: 'ProcessMethodType.Rules.RulesDefinition',
        ps: [{
            n: 'description',
            en: {
              lp: 'description',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            ti: 'GML_3_1_1.StringOrRefType'
          }, {
            n: 'ruleLanguage',
            mx: false,
            dom: false,
            typed: false,
            ti: '.RuleLanguageType',
            t: 'er'
          }]
      }, {
        ln: 'DataSourceType.DataDefinition',
        ps: [{
            n: 'dataBlockDefinition',
            en: {
              lp: 'DataBlockDefinition',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.DataBlockDefinitionType'
          }, {
            n: 'dataStreamDefinition',
            en: {
              lp: 'DataStreamDefinition',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.DataStreamDefinitionType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Parameters',
        ps: [{
            n: 'parameterList',
            en: 'ParameterList',
            ti: '.Parameters.ParameterList'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Identification.IdentifierList.Identifier',
        ps: [{
            n: 'term',
            en: 'Term',
            ti: '.Term'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }]
      }, {
        ln: 'PresentationLayerPropertyType',
        ps: [{
            n: 'abstractDataRecord',
            mx: false,
            dom: false,
            typed: false,
            en: {
              lp: 'AbstractDataRecord',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.AbstractDataRecordType',
            t: 'er'
          }, {
            n: 'category',
            en: {
              lp: 'Category',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.Category'
          }, {
            n: 'dataBlockDefinition',
            en: {
              lp: 'DataBlockDefinition',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.DataBlockDefinitionType'
          }, {
            n: 'dataStreamDefinition',
            en: {
              lp: 'DataStreamDefinition',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.DataStreamDefinitionType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'ConnectionsPropertyType',
        ps: [{
            n: 'connectionList',
            en: 'ConnectionList',
            ti: '.AbstractListType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'SensorML',
        ps: [{
            n: 'keywords',
            col: true,
            ti: '.Keywords'
          }, {
            n: 'identification',
            col: true,
            ti: '.Identification'
          }, {
            n: 'classification',
            col: true,
            ti: '.Classification'
          }, {
            n: 'validTime',
            ti: '.ValidTime'
          }, {
            n: 'securityConstraint',
            ti: '.SecurityConstraint'
          }, {
            n: 'legalConstraint',
            col: true,
            ti: '.LegalConstraint'
          }, {
            n: 'characteristics',
            col: true,
            ti: '.Characteristics'
          }, {
            n: 'capabilities',
            col: true,
            ti: '.Capabilities'
          }, {
            n: 'contact',
            col: true,
            ti: '.Contact'
          }, {
            n: 'documentation',
            col: true,
            ti: '.Documentation'
          }, {
            n: 'history',
            col: true,
            ti: '.History'
          }, {
            n: 'member',
            col: true,
            ti: '.SensorML.Member'
          }, {
            n: 'version',
            an: {
              lp: 'version'
            },
            t: 'a'
          }]
      }, {
        ln: 'Documentation',
        ps: [{
            n: 'document',
            en: 'Document',
            ti: '.Document'
          }, {
            n: 'documentList',
            en: 'DocumentList',
            ti: '.DocumentList'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'ArrayLink',
        ps: [{
            n: 'sourceArray',
            ti: '.ArrayLink.SourceArray'
          }, {
            n: 'destinationIndex',
            col: true,
            ti: '.ArrayLink.DestinationIndex'
          }, {
            n: 'destinationArray',
            ti: '.ArrayLink.DestinationArray'
          }, {
            n: 'sourceIndex',
            ti: '.ArrayLink.SourceIndex'
          }, {
            n: 'connection',
            col: true,
            ti: '.Connection'
          }]
      }, {
        ln: 'Connection',
        ps: [{
            n: 'link',
            en: 'Link',
            ti: '.Link'
          }, {
            n: 'arrayLink',
            en: 'ArrayLink',
            ti: '.ArrayLink'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }]
      }, {
        ln: 'TemporalReferenceFrame',
        ps: [{
            n: 'temporalCRS',
            en: {
              lp: 'TemporalCRS',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            ti: 'GML_3_1_1.TemporalCRSType'
          }]
      }, {
        ln: 'ProcessMethodType.Implementation.ImplementationCode.SourceRef',
        ps: [{
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'ContactInfo',
        ps: [{
            n: 'phone',
            ti: '.ContactInfo.Phone'
          }, {
            n: 'address',
            ti: '.ContactInfo.Address'
          }, {
            n: 'onlineResource',
            col: true,
            ti: '.OnlineResource'
          }, {
            n: 'hoursOfService'
          }, {
            n: 'contactInstructions'
          }]
      }, {
        ln: 'Security',
        ps: [{
            n: 'classification',
            ti: 'IC_2_0.ClassificationType',
            an: {
              lp: 'classification',
              ns: 'urn:us:gov:ic:ism:v2'
            },
            t: 'a'
          }, {
            n: 'ownerProducer',
            ti: {
              t: 'l'
            },
            an: {
              lp: 'ownerProducer',
              ns: 'urn:us:gov:ic:ism:v2'
            },
            t: 'a'
          }, {
            n: 'scIcontrols',
            ti: {
              t: 'l'
            },
            an: {
              lp: 'SCIcontrols',
              ns: 'urn:us:gov:ic:ism:v2'
            },
            t: 'a'
          }, {
            n: 'sarIdentifier',
            ti: {
              t: 'l'
            },
            an: {
              lp: 'SARIdentifier',
              ns: 'urn:us:gov:ic:ism:v2'
            },
            t: 'a'
          }, {
            n: 'disseminationControls',
            ti: {
              t: 'l'
            },
            an: {
              lp: 'disseminationControls',
              ns: 'urn:us:gov:ic:ism:v2'
            },
            t: 'a'
          }, {
            n: 'fgIsourceOpen',
            ti: {
              t: 'l'
            },
            an: {
              lp: 'FGIsourceOpen',
              ns: 'urn:us:gov:ic:ism:v2'
            },
            t: 'a'
          }, {
            n: 'fgIsourceProtected',
            ti: {
              t: 'l'
            },
            an: {
              lp: 'FGIsourceProtected',
              ns: 'urn:us:gov:ic:ism:v2'
            },
            t: 'a'
          }, {
            n: 'releasableTo',
            ti: {
              t: 'l'
            },
            an: {
              lp: 'releasableTo',
              ns: 'urn:us:gov:ic:ism:v2'
            },
            t: 'a'
          }, {
            n: 'nonICmarkings',
            ti: {
              t: 'l'
            },
            an: {
              lp: 'nonICmarkings',
              ns: 'urn:us:gov:ic:ism:v2'
            },
            t: 'a'
          }, {
            n: 'classifiedBy',
            an: {
              lp: 'classifiedBy',
              ns: 'urn:us:gov:ic:ism:v2'
            },
            t: 'a'
          }, {
            n: 'classificationReason',
            an: {
              lp: 'classificationReason',
              ns: 'urn:us:gov:ic:ism:v2'
            },
            t: 'a'
          }, {
            n: 'derivedFrom',
            an: {
              lp: 'derivedFrom',
              ns: 'urn:us:gov:ic:ism:v2'
            },
            t: 'a'
          }, {
            n: 'declassDate',
            ti: 'Calendar',
            an: {
              lp: 'declassDate',
              ns: 'urn:us:gov:ic:ism:v2'
            },
            t: 'a'
          }, {
            n: 'declassEvent',
            an: {
              lp: 'declassEvent',
              ns: 'urn:us:gov:ic:ism:v2'
            },
            t: 'a'
          }, {
            n: 'declassException',
            ti: {
              t: 'l'
            },
            an: {
              lp: 'declassException',
              ns: 'urn:us:gov:ic:ism:v2'
            },
            t: 'a'
          }, {
            n: 'typeOfExemptedSource',
            ti: {
              t: 'l'
            },
            an: {
              lp: 'typeOfExemptedSource',
              ns: 'urn:us:gov:ic:ism:v2'
            },
            t: 'a'
          }, {
            n: 'dateOfExemptedSource',
            ti: 'Calendar',
            an: {
              lp: 'dateOfExemptedSource',
              ns: 'urn:us:gov:ic:ism:v2'
            },
            t: 'a'
          }, {
            n: 'declassManualReview',
            ti: 'Boolean',
            an: {
              lp: 'declassManualReview',
              ns: 'urn:us:gov:ic:ism:v2'
            },
            t: 'a'
          }]
      }, {
        ln: 'ArrayLink.DestinationIndex',
        ps: [{
            n: 'ref',
            an: {
              lp: 'ref'
            },
            t: 'a'
          }]
      }, {
        ln: 'ParametersPropertyType',
        ps: [{
            n: 'parameterList',
            en: 'ParameterList',
            ti: '.AbstractListType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Inputs',
        ps: [{
            n: 'inputList',
            en: 'InputList',
            ti: '.Inputs.InputList'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'OutputsPropertyType',
        ps: [{
            n: 'outputList',
            en: 'OutputList',
            ti: '.AbstractListType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'SpatialReferenceFrame',
        ps: [{
            n: 'engineeringCRS',
            en: {
              lp: 'EngineeringCRS',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            ti: 'GML_3_1_1.EngineeringCRSType'
          }]
      }, {
        ln: 'InputsPropertyType',
        ps: [{
            n: 'inputList',
            en: 'InputList',
            ti: '.AbstractListType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'History',
        ps: [{
            n: 'eventList',
            en: 'EventList',
            ti: '.EventList'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'AbstractSMLType',
        bti: 'GML_3_1_1.AbstractFeatureType'
      }, {
        ln: 'ResponsibleParty',
        ps: [{
            n: 'individualName'
          }, {
            n: 'organizationName'
          }, {
            n: 'positionName'
          }, {
            n: 'contactInfo',
            ti: '.ContactInfo'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }]
      }, {
        ln: 'ProcessModelType',
        bti: '.AbstractPureProcessType',
        ps: [{
            n: 'method',
            ti: '.MethodPropertyType'
          }]
      }, {
        ln: 'AbstractDerivableComponentType',
        bti: '.AbstractProcessType',
        ps: [{
            n: 'spatialReferenceFrame',
            ti: '.SpatialReferenceFrame'
          }, {
            n: 'temporalReferenceFrame',
            ti: '.TemporalReferenceFrame'
          }, {
            n: 'targetLocation',
            en: 'location',
            ti: '.Location'
          }, {
            n: 'targetPosition',
            en: 'position',
            ti: '.Position'
          }, {
            n: 'timePosition',
            ti: '.TimePosition'
          }, {
            n: 'interfaces',
            ti: '.Interfaces'
          }]
      }, {
        ln: 'ComponentType',
        bti: '.AbstractComponentType',
        ps: [{
            n: 'method',
            ti: '.MethodPropertyType'
          }]
      }, {
        ln: 'ProcessMethodType',
        bti: 'GML_3_1_1.AbstractGMLType',
        ps: [{
            n: 'keywords',
            col: true,
            ti: '.Keywords'
          }, {
            n: 'identification',
            col: true,
            ti: '.Identification'
          }, {
            n: 'classification',
            col: true,
            ti: '.Classification'
          }, {
            n: 'validTime',
            ti: '.ValidTime'
          }, {
            n: 'securityConstraint',
            ti: '.SecurityConstraint'
          }, {
            n: 'legalConstraint',
            col: true,
            ti: '.LegalConstraint'
          }, {
            n: 'characteristics',
            col: true,
            ti: '.Characteristics'
          }, {
            n: 'capabilities',
            col: true,
            ti: '.Capabilities'
          }, {
            n: 'contact',
            col: true,
            ti: '.Contact'
          }, {
            n: 'documentation',
            col: true,
            ti: '.Documentation'
          }, {
            n: 'history',
            col: true,
            ti: '.History'
          }, {
            n: 'rules',
            ti: '.ProcessMethodType.Rules'
          }, {
            n: 'algorithm',
            ti: '.ProcessMethodType.Algorithm'
          }, {
            n: 'implementation',
            col: true,
            ti: '.ProcessMethodType.Implementation'
          }]
      }, {
        ln: 'Classification',
        ps: [{
            n: 'classifierList',
            en: 'ClassifierList',
            ti: '.Classification.ClassifierList'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Keywords',
        ps: [{
            n: 'keywordList',
            en: 'KeywordList',
            ti: '.Keywords.KeywordList'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Interfaces',
        ps: [{
            n: 'interfaceList',
            en: 'InterfaceList',
            ti: '.Interfaces.InterfaceList'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Location',
        ps: [{
            n: 'point',
            en: {
              lp: 'Point',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            ti: 'GML_3_1_1.PointType'
          }, {
            n: 'curve',
            mx: false,
            dom: false,
            typed: false,
            en: {
              lp: '_Curve',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            ti: 'GML_3_1_1.AbstractCurveType',
            t: 'er'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Characteristics',
        ps: [{
            n: 'abstractDataRecord',
            mx: false,
            dom: false,
            typed: false,
            en: {
              lp: 'AbstractDataRecord',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.AbstractDataRecordType',
            t: 'er'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'AbstractDerivableProcessType',
        bti: '.AbstractProcessType',
        ps: [{
            n: 'inputs',
            ti: '.InputsPropertyType'
          }, {
            n: 'outputs',
            ti: '.OutputsPropertyType'
          }, {
            n: 'parameters',
            ti: '.ParametersPropertyType'
          }, {
            n: 'method',
            ti: '.MethodPropertyType'
          }, {
            n: 'components',
            ti: '.ComponentsPropertyType'
          }, {
            n: 'dataSources',
            ti: '.DataSourcesPropertyType'
          }, {
            n: 'connections',
            ti: '.ConnectionsPropertyType'
          }]
      }, {
        ln: 'AbstractProcessType',
        bti: '.AbstractSMLType',
        ps: [{
            n: 'keywords',
            col: true,
            ti: '.Keywords'
          }, {
            n: 'identification',
            col: true,
            ti: '.Identification'
          }, {
            n: 'classification',
            col: true,
            ti: '.Classification'
          }, {
            n: 'validTime',
            ti: '.ValidTime'
          }, {
            n: 'securityConstraint',
            ti: '.SecurityConstraint'
          }, {
            n: 'legalConstraint',
            col: true,
            ti: '.LegalConstraint'
          }, {
            n: 'characteristics',
            col: true,
            ti: '.Characteristics'
          }, {
            n: 'capabilities',
            col: true,
            ti: '.Capabilities'
          }, {
            n: 'contact',
            col: true,
            ti: '.Contact'
          }, {
            n: 'documentation',
            col: true,
            ti: '.Documentation'
          }, {
            n: 'history',
            col: true,
            ti: '.History'
          }]
      }, {
        ln: 'AbstractRestrictedProcessType',
        bti: '.AbstractProcessType'
      }, {
        ln: 'Positions.PositionList',
        ps: [{
            n: 'position',
            col: true,
            ti: '.Position'
          }, {
            n: 'timePosition',
            ti: '.TimePosition'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }]
      }, {
        ln: 'DataSourceType',
        bti: '.AbstractProcessType',
        ps: [{
            n: 'dataDefinition',
            ti: '.DataSourceType.DataDefinition'
          }, {
            n: 'values',
            ti: '.DataSourceType.Values'
          }, {
            n: 'observationReference',
            ti: '.DataSourceType.ObservationReference'
          }]
      }, {
        ln: 'EventList',
        ps: [{
            n: 'member',
            col: true,
            ti: '.EventList.Member'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }]
      }, {
        ln: 'TimePosition',
        ps: [{
            n: 'time',
            en: {
              lp: 'Time',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.Time'
          }, {
            n: 'process',
            mx: false,
            dom: false,
            typed: false,
            en: '_Process',
            ti: '.AbstractProcessType',
            t: 'er'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'ContactList.Member',
        ps: [{
            n: 'person',
            en: 'Person',
            ti: '.Person'
          }, {
            n: 'responsibleParty',
            en: 'ResponsibleParty',
            ti: '.ResponsibleParty'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Link.Destination',
        ps: [{
            n: 'ref',
            an: {
              lp: 'ref'
            },
            t: 'a'
          }]
      }, {
        ln: 'ArrayLink.SourceArray',
        ps: [{
            n: 'ref',
            an: {
              lp: 'ref'
            },
            t: 'a'
          }]
      }, {
        ln: 'MethodPropertyType',
        ps: [{
            n: 'processMethod',
            en: 'ProcessMethod',
            ti: '.ProcessMethodType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Connections',
        ps: [{
            n: 'connectionList',
            en: 'ConnectionList',
            ti: '.Connections.ConnectionList'
          }]
      }, {
        ln: 'InterfaceDefinition',
        ps: [{
            n: 'serviceLayer',
            ti: '.LayerPropertyType'
          }, {
            n: 'applicationLayer',
            ti: '.LayerPropertyType'
          }, {
            n: 'presentationLayer',
            ti: '.PresentationLayerPropertyType'
          }, {
            n: 'sessionLayer',
            ti: '.LayerPropertyType'
          }, {
            n: 'transportLayer',
            ti: '.LayerPropertyType'
          }, {
            n: 'networkLayer',
            ti: '.LayerPropertyType'
          }, {
            n: 'dataLinkLayer',
            ti: '.LayerPropertyType'
          }, {
            n: 'physicalLayer',
            ti: '.LayerPropertyType'
          }, {
            n: 'mechanicalLayer',
            ti: '.LayerPropertyType'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }]
      }, {
        ln: 'ComponentArrayType.Parameters',
        bti: '.ParametersPropertyType'
      }, {
        ln: 'Outputs',
        ps: [{
            n: 'outputList',
            en: 'OutputList',
            ti: '.Outputs.OutputList'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Classification.ClassifierList',
        ps: [{
            n: 'classifier',
            col: true,
            ti: '.Classification.ClassifierList.Classifier'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }]
      }, {
        ln: 'OnlineResource',
        ps: [{
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Contact',
        ps: [{
            n: 'person',
            en: 'Person',
            ti: '.Person'
          }, {
            n: 'responsibleParty',
            en: 'ResponsibleParty',
            ti: '.ResponsibleParty'
          }, {
            n: 'contactList',
            en: 'ContactList',
            ti: '.ContactList'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Interfaces.InterfaceList',
        ps: [{
            n: '_interface',
            col: true,
            en: 'interface',
            ti: '.Interface'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }]
      }, {
        ln: 'AbstractPureProcessType',
        bti: '.AbstractRestrictedProcessType',
        ps: [{
            n: 'inputs',
            ti: '.Inputs'
          }, {
            n: 'outputs',
            ti: '.Outputs'
          }, {
            n: 'parameters',
            ti: '.Parameters'
          }]
      }, {
        ln: 'ArrayLink.DestinationArray',
        ps: [{
            n: 'ref',
            an: {
              lp: 'ref'
            },
            t: 'a'
          }]
      }, {
        ln: 'Person',
        ps: [{
            n: 'surname'
          }, {
            n: 'name'
          }, {
            n: 'userID'
          }, {
            n: 'affiliation'
          }, {
            n: 'phoneNumber'
          }, {
            n: 'email'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }]
      }, {
        ln: 'DocumentList.Member',
        ps: [{
            n: 'document',
            en: 'Document',
            ti: '.Document'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'LegalConstraint',
        ps: [{
            n: 'rights',
            en: 'Rights',
            ti: '.Rights'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Link.Source',
        ps: [{
            n: 'ref',
            an: {
              lp: 'ref'
            },
            t: 'a'
          }]
      }, {
        ln: 'ContactInfo.Address',
        ps: [{
            n: 'deliveryPoint',
            col: true
          }, {
            n: 'city'
          }, {
            n: 'administrativeArea'
          }, {
            n: 'postalCode'
          }, {
            n: 'country'
          }, {
            n: 'electronicMailAddress'
          }]
      }, {
        ln: 'ProcessMethodType.Implementation.ImplementationCode.BinaryRef',
        ps: [{
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'ValidTime',
        ps: [{
            n: 'timeInstant',
            en: {
              lp: 'TimeInstant',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            ti: 'GML_3_1_1.TimeInstantType'
          }, {
            n: 'timePeriod',
            en: {
              lp: 'TimePeriod',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            ti: 'GML_3_1_1.TimePeriodType'
          }]
      }, {
        ln: 'Classification.ClassifierList.Classifier',
        ps: [{
            n: 'term',
            en: 'Term',
            ti: '.Term'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }]
      }, {
        ln: 'Identification',
        ps: [{
            n: 'identifierList',
            en: 'IdentifierList',
            ti: '.Identification.IdentifierList'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'ProcessMethodType.Algorithm.AlgorithmDefinition',
        ps: [{
            n: 'description',
            en: {
              lp: 'description',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            ti: 'GML_3_1_1.StringOrRefType'
          }, {
            n: 'mathML',
            ti: '.ProcessMethodType.Algorithm.AlgorithmDefinition.MathML'
          }]
      }, {
        ln: 'Positions',
        ps: [{
            n: 'positionList',
            en: 'PositionList',
            ti: '.Positions.PositionList'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Capabilities',
        ps: [{
            n: 'abstractDataRecord',
            mx: false,
            dom: false,
            typed: false,
            en: {
              lp: 'AbstractDataRecord',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.AbstractDataRecordType',
            t: 'er'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'SecurityConstraint',
        ps: [{
            n: 'security',
            en: 'Security',
            ti: '.Security'
          }]
      }, {
        ln: 'DataSourceType.ObservationReference',
        ps: [{
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'SystemType',
        bti: '.AbstractComponentType',
        ps: [{
            n: 'components',
            ti: '.Components'
          }, {
            n: 'positions',
            ti: '.Positions'
          }, {
            n: 'connections',
            ti: '.Connections'
          }]
      }, {
        ln: 'Components.ComponentList',
        ps: [{
            n: 'component',
            col: true,
            ti: '.Components.ComponentList.Component'
          }]
      }, {
        ln: 'EventList.Member',
        ps: [{
            n: 'event',
            en: 'Event',
            ti: '.Event'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'ProcessChainType',
        bti: '.AbstractPureProcessType',
        ps: [{
            n: 'components',
            ti: '.Components'
          }, {
            n: 'connections',
            ti: '.Connections'
          }]
      }, {
        ln: 'RelaxNG',
        bti: '.RuleLanguageType',
        ps: [{
            n: 'any',
            mx: false,
            t: 'ae'
          }]
      }, {
        ln: 'ComponentsPropertyType',
        ps: [{
            n: 'processList',
            en: 'ProcessList',
            ti: '.AbstractListType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Keywords.KeywordList',
        ps: [{
            n: 'keyword',
            col: true
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }, {
            n: 'codeSpace',
            an: {
              lp: 'codeSpace'
            },
            t: 'a'
          }]
      }, {
        ln: 'ProcessMethodType.Algorithm',
        ps: [{
            n: 'algorithmDefinition',
            en: 'AlgorithmDefinition',
            ti: '.ProcessMethodType.Algorithm.AlgorithmDefinition'
          }]
      }, {
        ln: 'Link',
        ps: [{
            n: 'source',
            ti: '.Link.Source'
          }, {
            n: 'destination',
            ti: '.Link.Destination'
          }, {
            n: 'type',
            an: {
              lp: 'type'
            },
            t: 'a'
          }]
      }, {
        ln: 'ProcessMethodType.Algorithm.AlgorithmDefinition.MathML',
        ps: [{
            n: 'any',
            mx: false,
            t: 'ae'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Connections.ConnectionList',
        ps: [{
            n: 'connection',
            col: true,
            ti: '.Connection'
          }]
      }, {
        ln: 'SensorML.Member',
        ps: [{
            n: 'process',
            mx: false,
            dom: false,
            typed: false,
            en: '_Process',
            ti: '.AbstractProcessType',
            t: 'er'
          }, {
            n: 'documentList',
            en: 'DocumentList',
            ti: '.DocumentList'
          }, {
            n: 'contactList',
            en: 'ContactList',
            ti: '.ContactList'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'AbstractComponentType',
        bti: '.AbstractDerivableComponentType',
        ps: [{
            n: 'inputs',
            ti: '.Inputs'
          }, {
            n: 'outputs',
            ti: '.Outputs'
          }, {
            n: 'parameters',
            ti: '.Parameters'
          }]
      }, {
        ln: 'ProcessMethodType.Rules',
        ps: [{
            n: 'rulesDefinition',
            en: 'RulesDefinition',
            ti: '.ProcessMethodType.Rules.RulesDefinition'
          }]
      }, {
        ln: 'ProcessMethodType.Implementation.ImplementationCode',
        ps: [{
            n: 'description',
            en: {
              lp: 'description',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            ti: 'GML_3_1_1.StringOrRefType'
          }, {
            n: 'keywords',
            col: true,
            ti: '.Keywords'
          }, {
            n: 'identification',
            col: true,
            ti: '.Identification'
          }, {
            n: 'classification',
            col: true,
            ti: '.Classification'
          }, {
            n: 'validTime',
            ti: '.ValidTime'
          }, {
            n: 'securityConstraint',
            ti: '.SecurityConstraint'
          }, {
            n: 'legalConstraint',
            col: true,
            ti: '.LegalConstraint'
          }, {
            n: 'characteristics',
            col: true,
            ti: '.Characteristics'
          }, {
            n: 'capabilities',
            col: true,
            ti: '.Capabilities'
          }, {
            n: 'contact',
            col: true,
            ti: '.Contact'
          }, {
            n: 'documentation',
            col: true,
            ti: '.Documentation'
          }, {
            n: 'history',
            col: true,
            ti: '.History'
          }, {
            n: 'sourceRef',
            ti: '.ProcessMethodType.Implementation.ImplementationCode.SourceRef'
          }, {
            n: 'binaryRef',
            ti: '.ProcessMethodType.Implementation.ImplementationCode.BinaryRef'
          }, {
            n: 'language',
            an: {
              lp: 'language'
            },
            t: 'a'
          }, {
            n: 'framework',
            an: {
              lp: 'framework'
            },
            t: 'a'
          }, {
            n: 'version',
            an: {
              lp: 'version'
            },
            t: 'a'
          }]
      }, {
        ln: 'Document',
        ps: [{
            n: 'description',
            en: {
              lp: 'description',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            ti: 'GML_3_1_1.StringOrRefType'
          }, {
            n: 'date'
          }, {
            n: 'contact',
            ti: '.Contact'
          }, {
            n: 'format'
          }, {
            n: 'onlineResource',
            col: true,
            ti: '.OnlineResource'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'version',
            an: {
              lp: 'version'
            },
            t: 'a'
          }]
      }, {
        ln: 'Term',
        ps: [{
            n: 'codeSpace',
            ti: 'SWE_1_0_1.CodeSpacePropertyType'
          }, {
            n: 'value'
          }, {
            n: 'definition',
            an: {
              lp: 'definition'
            },
            t: 'a'
          }]
      }, {
        ln: 'Position',
        ps: [{
            n: 'process',
            mx: false,
            dom: false,
            typed: false,
            en: '_Process',
            ti: '.AbstractProcessType',
            t: 'er'
          }, {
            n: 'position',
            en: {
              lp: 'Position',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.PositionType'
          }, {
            n: 'vector',
            en: {
              lp: 'Vector',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.VectorType'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Schematron',
        bti: '.RuleLanguageType',
        ps: [{
            n: 'any',
            mx: false,
            t: 'ae'
          }]
      }, {
        ln: 'DataSourceType.Values',
        ps: [{
            n: 'otherAttributes',
            t: 'aa'
          }, {
            n: 'any',
            col: true,
            typed: false,
            mx: false,
            t: 'ae'
          }]
      }, {
        ln: 'Components.ComponentList.Component',
        ps: [{
            n: 'process',
            mx: false,
            dom: false,
            typed: false,
            en: '_Process',
            ti: '.AbstractProcessType',
            t: 'er'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'LayerPropertyType',
        ps: [{
            n: 'abstractDataRecord',
            mx: false,
            dom: false,
            typed: false,
            en: {
              lp: 'AbstractDataRecord',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.AbstractDataRecordType',
            t: 'er'
          }, {
            n: 'category',
            en: {
              lp: 'Category',
              ns: 'http:\/\/www.opengis.net\/swe\/1.0.1'
            },
            ti: 'SWE_1_0_1.Category'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }],
    eis: [{
        en: 'Component',
        ti: '.ComponentType',
        sh: '_Process'
      }, {
        en: 'System',
        ti: '.SystemType',
        sh: '_Process'
      }, {
        en: 'components',
        ti: '.Components'
      }, {
        en: 'DataSource',
        ti: '.DataSourceType',
        sh: '_Process'
      }, {
        en: 'Person',
        ti: '.Person'
      }, {
        en: 'ProcessChain',
        ti: '.ProcessChainType',
        sh: '_Process'
      }, {
        en: 'identification',
        ti: '.Identification'
      }, {
        en: 'contactInfo',
        ti: '.ContactInfo'
      }, {
        en: 'Term',
        ti: '.Term'
      }, {
        en: 'connection',
        ti: '.Connection'
      }, {
        en: 'onlineResource',
        ti: '.OnlineResource'
      }, {
        en: 'method',
        ti: '.MethodPropertyType'
      }, {
        en: 'interfaces',
        ti: '.Interfaces'
      }, {
        en: 'positions',
        ti: '.Positions'
      }, {
        en: 'ResponsibleParty',
        ti: '.ResponsibleParty'
      }, {
        en: 'location',
        ti: '.Location'
      }, {
        en: 'legalConstraint',
        ti: '.LegalConstraint'
      }, {
        en: 'capabilities',
        ti: '.Capabilities'
      }, {
        en: 'ComponentArray',
        ti: '.ComponentArrayType',
        sh: '_Process'
      }, {
        en: 'InterfaceDefinition',
        ti: '.InterfaceDefinition'
      }, {
        en: 'relaxNG',
        ti: '.RelaxNG',
        sh: 'ruleLanguage'
      }, {
        en: 'interface',
        ti: '.Interface'
      }, {
        en: 'documentation',
        ti: '.Documentation'
      }, {
        en: 'ArrayLink',
        ti: '.ArrayLink'
      }, {
        en: 'ProcessMethod',
        ti: '.ProcessMethodType'
      }, {
        en: 'ContactList',
        ti: '.ContactList'
      }, {
        en: 'connections',
        ti: '.Connections'
      }, {
        en: 'ruleLanguage',
        ti: '.RuleLanguageType'
      }, {
        en: '_Process',
        ti: '.AbstractProcessType'
      }, {
        en: 'keywords',
        ti: '.Keywords'
      }, {
        en: 'securityConstraint',
        ti: '.SecurityConstraint'
      }, {
        en: 'schematron',
        ti: '.Schematron',
        sh: 'ruleLanguage'
      }, {
        en: 'timePosition',
        ti: '.TimePosition'
      }, {
        en: 'EventList',
        ti: '.EventList'
      }, {
        en: 'spatialReferenceFrame',
        ti: '.SpatialReferenceFrame'
      }, {
        en: 'SensorML',
        ti: '.SensorML'
      }, {
        en: 'position',
        ti: '.Position'
      }, {
        en: 'classification',
        ti: '.Classification'
      }, {
        en: 'Document',
        ti: '.Document'
      }, {
        en: 'inputs',
        ti: '.Inputs'
      }, {
        en: 'temporalReferenceFrame',
        ti: '.TemporalReferenceFrame'
      }, {
        en: 'Rights',
        ti: '.Rights'
      }, {
        en: 'history',
        ti: '.History'
      }, {
        en: 'Security',
        ti: '.Security'
      }, {
        en: 'contact',
        ti: '.Contact'
      }, {
        en: 'Event',
        ti: '.Event'
      }, {
        en: 'parameters',
        ti: '.Parameters'
      }, {
        en: 'validTime',
        ti: '.ValidTime'
      }, {
        en: 'DocumentList',
        ti: '.DocumentList'
      }, {
        en: 'characteristics',
        ti: '.Characteristics'
      }, {
        en: 'Link',
        ti: '.Link'
      }, {
        en: 'outputs',
        ti: '.Outputs'
      }, {
        en: 'ProcessModel',
        ti: '.ProcessModelType',
        sh: '_Process'
      }]
  };
  return {
    SensorML_1_0_1: SensorML_1_0_1
  };
};
if (typeof define === 'function' && define.amd) {
  define([], SensorML_1_0_1_Module_Factory);
}
else {
  var SensorML_1_0_1_Module = SensorML_1_0_1_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.SensorML_1_0_1 = SensorML_1_0_1_Module.SensorML_1_0_1;
  }
  else {
    var SensorML_1_0_1 = SensorML_1_0_1_Module.SensorML_1_0_1;
  }
}