var SWE_2_0_Module_Factory = function () {
  var SWE_2_0 = {
    n: 'SWE_2_0',
    dens: 'http:\/\/www.opengis.net\/swe\/2.0',
    dans: 'http:\/\/www.w3.org\/1999\/xlink',
    deps: ['XLink_1_0'],
    tis: [{
        ln: 'BinaryEncodingPropertyType',
        ps: [{
            n: 'binaryEncoding',
            en: 'BinaryEncoding',
            ti: '.BinaryEncodingType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'MatrixPropertyByValueType',
        ps: [{
            n: 'matrix',
            en: 'Matrix',
            ti: '.MatrixType'
          }]
      }, {
        ln: 'ComponentOrBlockPropertyType',
        ps: [{
            n: 'component',
            en: 'Component',
            ti: '.ComponentType'
          }, {
            n: 'block',
            en: 'Block',
            ti: '.BlockType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'AllowedTimesPropertyByValueType',
        ps: [{
            n: 'allowedTimes',
            en: 'AllowedTimes',
            ti: '.AllowedTimesType'
          }]
      }, {
        ln: 'TimePropertyType',
        ps: [{
            n: 'time',
            en: 'Time',
            ti: '.TimeType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'UnitReference',
        ps: [{
            n: 'code',
            an: {
              lp: 'code'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'AllowedTokensPropertyByValueType',
        ps: [{
            n: 'allowedTokens',
            en: 'AllowedTokens',
            ti: '.AllowedTokensType'
          }]
      }, {
        ln: 'DataRecordPropertyByValueType',
        ps: [{
            n: 'dataRecord',
            en: 'DataRecord',
            ti: '.DataRecordType'
          }]
      }, {
        ln: 'XMLEncodingPropertyType',
        ps: [{
            n: 'xmlEncoding',
            en: 'XMLEncoding',
            ti: '.XMLEncodingType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'AnyRangePropertyType',
        ps: [{
            n: 'quantityRange',
            en: 'QuantityRange',
            ti: '.QuantityRangeType'
          }, {
            n: 'timeRange',
            en: 'TimeRange',
            ti: '.TimeRangeType'
          }, {
            n: 'countRange',
            en: 'CountRange',
            ti: '.CountRangeType'
          }, {
            n: 'categoryRange',
            en: 'CategoryRange',
            ti: '.CategoryRangeType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'CategoryRangePropertyType',
        ps: [{
            n: 'categoryRange',
            en: 'CategoryRange',
            ti: '.CategoryRangeType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'AnyNumericalPropertyType',
        ps: [{
            n: 'count',
            en: 'Count',
            ti: '.CountType'
          }, {
            n: 'quantity',
            en: 'Quantity',
            ti: '.QuantityType'
          }, {
            n: 'time',
            en: 'Time',
            ti: '.TimeType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'AbstractEncodingPropertyByValueType',
        ps: [{
            n: 'abstractEncoding',
            mx: false,
            dom: false,
            en: 'AbstractEncoding',
            ti: '.AbstractEncodingType',
            t: 'er'
          }]
      }, {
        ln: 'BooleanPropertyType',
        ps: [{
            n: '_boolean',
            en: 'Boolean',
            ti: '.BooleanType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'NilValuesPropertyType',
        ps: [{
            n: 'nilValues',
            en: 'NilValues',
            ti: '.NilValuesType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'AbstractSimpleComponentType',
        bti: '.AbstractDataComponentType',
        ps: [{
            n: 'quality',
            col: true,
            ti: '.QualityPropertyType'
          }, {
            n: 'nilValues',
            ti: '.NilValuesPropertyType'
          }, {
            n: 'referenceFrame',
            an: {
              lp: 'referenceFrame'
            },
            t: 'a'
          }, {
            n: 'axisID',
            an: {
              lp: 'axisID'
            },
            t: 'a'
          }]
      }, {
        ln: 'DataStreamPropertyType',
        ps: [{
            n: 'dataStream',
            en: 'DataStream',
            ti: '.DataStreamType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'CategoryType',
        bti: '.AbstractSimpleComponentType',
        ps: [{
            n: 'codeSpace',
            ti: '.Reference'
          }, {
            n: 'constraint',
            ti: '.AllowedTokensPropertyType'
          }, {
            n: 'value'
          }]
      }, {
        ln: 'BooleanType',
        bti: '.AbstractSimpleComponentType',
        ps: [{
            n: 'value',
            ti: 'Boolean'
          }]
      }, {
        ln: 'QuantityType',
        bti: '.AbstractSimpleComponentType',
        ps: [{
            n: 'uom',
            ti: '.UnitReference'
          }, {
            n: 'constraint',
            ti: '.AllowedValuesPropertyType'
          }, {
            n: 'value',
            ti: 'Double'
          }]
      }, {
        ln: 'VectorPropertyType',
        ps: [{
            n: 'vector',
            en: 'Vector',
            ti: '.VectorType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'DataStreamType.ElementCount',
        tn: null,
        ps: [{
            n: 'count',
            en: 'Count',
            ti: '.CountType'
          }]
      }, {
        ln: 'DataArrayPropertyType',
        ps: [{
            n: 'dataArray',
            mx: false,
            dom: false,
            en: 'DataArray',
            ti: '.DataArrayType',
            t: 'er'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'AbstractSWEType',
        ps: [{
            n: 'extension',
            col: true,
            ti: 'AnyType'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }]
      }, {
        ln: 'XMLEncodingPropertyByValueType',
        ps: [{
            n: 'xmlEncoding',
            en: 'XMLEncoding',
            ti: '.XMLEncodingType'
          }]
      }, {
        ln: 'AllowedValuesType',
        bti: '.AbstractSWEType',
        ps: [{
            n: 'value',
            col: true,
            ti: 'Double'
          }, {
            n: 'interval',
            col: true,
            mx: false,
            dom: false,
            ti: {
              t: 'l',
              bti: 'Double'
            },
            t: 'er'
          }, {
            n: 'significantFigures',
            ti: 'Integer'
          }]
      }, {
        ln: 'AllowedTimesType',
        bti: '.AbstractSWEType',
        ps: [{
            n: 'value',
            col: true,
            mx: false,
            dom: false,
            ti: {
              t: 'l'
            },
            t: 'er'
          }, {
            n: 'interval',
            col: true,
            mx: false,
            dom: false,
            ti: {
              t: 'l'
            },
            t: 'er'
          }, {
            n: 'significantFigures',
            ti: 'Integer'
          }]
      }, {
        ln: 'BinaryEncodingType',
        bti: '.AbstractEncodingType',
        ps: [{
            n: 'member',
            col: true,
            ti: '.BinaryEncodingType.Member'
          }, {
            n: 'byteOrder',
            an: {
              lp: 'byteOrder'
            },
            t: 'a'
          }, {
            n: 'byteEncoding',
            an: {
              lp: 'byteEncoding'
            },
            t: 'a'
          }, {
            n: 'byteLength',
            ti: 'Integer',
            an: {
              lp: 'byteLength'
            },
            t: 'a'
          }]
      }, {
        ln: 'AbstractSWEIdentifiableType',
        bti: '.AbstractSWEType',
        ps: [{
            n: 'identifier'
          }, {
            n: 'label'
          }, {
            n: 'description'
          }]
      }, {
        ln: 'AbstractEncodingPropertyType',
        ps: [{
            n: 'abstractEncoding',
            mx: false,
            dom: false,
            en: 'AbstractEncoding',
            ti: '.AbstractEncodingType',
            t: 'er'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'BlockPropertyType',
        ps: [{
            n: 'block',
            en: 'Block',
            ti: '.BlockType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'QuantityPropertyType',
        ps: [{
            n: 'quantity',
            en: 'Quantity',
            ti: '.QuantityType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'DataStreamType',
        bti: '.AbstractSWEIdentifiableType',
        ps: [{
            n: 'elementCount',
            ti: '.DataStreamType.ElementCount'
          }, {
            n: 'elementType',
            ti: '.DataStreamType.ElementType'
          }, {
            n: 'encoding',
            ti: '.DataStreamType.Encoding'
          }, {
            n: 'values',
            ti: '.EncodedValuesPropertyType'
          }]
      }, {
        ln: 'DataStreamType.Encoding',
        tn: null,
        ps: [{
            n: 'abstractEncoding',
            mx: false,
            dom: false,
            en: 'AbstractEncoding',
            ti: '.AbstractEncodingType',
            t: 'er'
          }]
      }, {
        ln: 'BlockType',
        bti: '.AbstractSWEType',
        ps: [{
            n: 'compression',
            an: {
              lp: 'compression'
            },
            t: 'a'
          }, {
            n: 'encryption',
            an: {
              lp: 'encryption'
            },
            t: 'a'
          }, {
            n: 'paddingBytesAfter',
            ti: 'Integer',
            an: {
              lp: 'paddingBytes-after'
            },
            t: 'a'
          }, {
            n: 'paddingBytesBefore',
            ti: 'Integer',
            an: {
              lp: 'paddingBytes-before'
            },
            t: 'a'
          }, {
            n: 'byteLength',
            ti: 'Integer',
            an: {
              lp: 'byteLength'
            },
            t: 'a'
          }, {
            n: 'ref',
            an: {
              lp: 'ref'
            },
            t: 'a'
          }]
      }, {
        ln: 'AllowedTokensType',
        bti: '.AbstractSWEType',
        ps: [{
            n: 'value',
            col: true
          }, {
            n: 'pattern'
          }]
      }, {
        ln: 'MatrixPropertyType',
        ps: [{
            n: 'matrix',
            en: 'Matrix',
            ti: '.MatrixType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'DataRecordType',
        bti: '.AbstractDataComponentType',
        ps: [{
            n: 'field',
            col: true,
            ti: '.DataRecordType.Field'
          }]
      }, {
        ln: 'DataRecordType.Field',
        tn: null,
        bti: '.AbstractDataComponentPropertyType',
        ps: [{
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }]
      }, {
        ln: 'ComponentPropertyType',
        ps: [{
            n: 'component',
            en: 'Component',
            ti: '.ComponentType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'AllowedTimesPropertyType',
        ps: [{
            n: 'allowedTimes',
            en: 'AllowedTimes',
            ti: '.AllowedTimesType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'DataArrayType',
        bti: '.AbstractDataComponentType',
        ps: [{
            n: 'elementCount',
            ti: '.CountPropertyType'
          }, {
            n: 'elementType',
            ti: '.DataArrayType.ElementType'
          }, {
            n: 'encoding',
            ti: '.DataArrayType.Encoding'
          }, {
            n: 'values',
            ti: '.EncodedValuesPropertyType'
          }]
      }, {
        ln: 'AllowedValuesPropertyType',
        ps: [{
            n: 'allowedValues',
            en: 'AllowedValues',
            ti: '.AllowedValuesType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'EncodedValuesPropertyType',
        ps: [{
            n: 'otherAttributes',
            t: 'aa'
          }, {
            n: 'content',
            col: true,
            typed: false,
            t: 'ae'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'AllowedValuesPropertyByValueType',
        ps: [{
            n: 'allowedValues',
            en: 'AllowedValues',
            ti: '.AllowedValuesType'
          }]
      }, {
        ln: 'AbstractSimpleComponentPropertyType',
        ps: [{
            n: 'abstractSimpleComponent',
            mx: false,
            dom: false,
            en: 'AbstractSimpleComponent',
            ti: '.AbstractSimpleComponentType',
            t: 'er'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'NilValuesType',
        bti: '.AbstractSWEType',
        ps: [{
            n: 'nilValue',
            col: true,
            ti: '.NilValue'
          }]
      }, {
        ln: 'DataRecordPropertyType',
        ps: [{
            n: 'dataRecord',
            en: 'DataRecord',
            ti: '.DataRecordType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'TimeRangeType',
        bti: '.AbstractSimpleComponentType',
        ps: [{
            n: 'uom',
            ti: '.UnitReference'
          }, {
            n: 'constraint',
            ti: '.AllowedTimesPropertyType'
          }, {
            n: 'value',
            ti: {
              t: 'l'
            }
          }, {
            n: 'referenceTime',
            ti: 'Calendar',
            an: {
              lp: 'referenceTime'
            },
            t: 'a'
          }, {
            n: 'localFrame',
            an: {
              lp: 'localFrame'
            },
            t: 'a'
          }]
      }, {
        ln: 'CountRangeType',
        bti: '.AbstractSimpleComponentType',
        ps: [{
            n: 'constraint',
            ti: '.AllowedValuesPropertyType'
          }, {
            n: 'value',
            ti: {
              t: 'l',
              bti: 'Integer'
            }
          }]
      }, {
        ln: 'DataChoiceType.ChoiceValue',
        tn: null,
        ps: [{
            n: 'category',
            en: 'Category',
            ti: '.CategoryType'
          }]
      }, {
        ln: 'BlockPropertyByValueType',
        ps: [{
            n: 'block',
            en: 'Block',
            ti: '.BlockType'
          }]
      }, {
        ln: 'VectorType',
        bti: '.AbstractDataComponentType',
        ps: [{
            n: 'coordinate',
            col: true,
            ti: '.VectorType.Coordinate'
          }, {
            n: 'referenceFrame',
            an: {
              lp: 'referenceFrame'
            },
            t: 'a'
          }, {
            n: 'localFrame',
            an: {
              lp: 'localFrame'
            },
            t: 'a'
          }]
      }, {
        ln: 'DataChoiceType.Item',
        tn: null,
        bti: '.AbstractDataComponentPropertyType',
        ps: [{
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }]
      }, {
        ln: 'BinaryEncodingType.Member',
        tn: null,
        ps: [{
            n: 'component',
            en: 'Component',
            ti: '.ComponentType'
          }, {
            n: 'block',
            en: 'Block',
            ti: '.BlockType'
          }]
      }, {
        ln: 'TextPropertyType',
        ps: [{
            n: 'text',
            en: 'Text',
            ti: '.TextType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'TimeType',
        bti: '.AbstractSimpleComponentType',
        ps: [{
            n: 'uom',
            ti: '.UnitReference'
          }, {
            n: 'constraint',
            ti: '.AllowedTimesPropertyType'
          }, {
            n: 'value',
            ti: {
              t: 'l'
            }
          }, {
            n: 'referenceTime',
            ti: 'Calendar',
            an: {
              lp: 'referenceTime'
            },
            t: 'a'
          }, {
            n: 'localFrame',
            an: {
              lp: 'localFrame'
            },
            t: 'a'
          }]
      }, {
        ln: 'DataArrayPropertyByValueType',
        ps: [{
            n: 'dataArray',
            mx: false,
            dom: false,
            en: 'DataArray',
            ti: '.DataArrayType',
            t: 'er'
          }]
      }, {
        ln: 'TimeRangePropertyType',
        ps: [{
            n: 'timeRange',
            en: 'TimeRange',
            ti: '.TimeRangeType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'CountType',
        bti: '.AbstractSimpleComponentType',
        ps: [{
            n: 'constraint',
            ti: '.AllowedValuesPropertyType'
          }, {
            n: 'value',
            ti: 'Integer'
          }]
      }, {
        ln: 'AbstractEncodingType',
        bti: '.AbstractSWEType'
      }, {
        ln: 'TextEncodingPropertyType',
        ps: [{
            n: 'textEncoding',
            en: 'TextEncoding',
            ti: '.TextEncodingType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'NilValue',
        ps: [{
            n: 'value',
            t: 'v'
          }, {
            n: 'reason',
            an: {
              lp: 'reason'
            },
            t: 'a'
          }]
      }, {
        ln: 'AbstractDataComponentPropertyType',
        ps: [{
            n: 'abstractDataComponent',
            mx: false,
            dom: false,
            en: 'AbstractDataComponent',
            ti: '.AbstractDataComponentType',
            t: 'er'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'CategoryPropertyType',
        ps: [{
            n: 'category',
            en: 'Category',
            ti: '.CategoryType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'TextEncodingPropertyByValueType',
        ps: [{
            n: 'textEncoding',
            en: 'TextEncoding',
            ti: '.TextEncodingType'
          }]
      }, {
        ln: 'Reference',
        ps: [{
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'DataChoiceType',
        bti: '.AbstractDataComponentType',
        ps: [{
            n: 'choiceValue',
            ti: '.DataChoiceType.ChoiceValue'
          }, {
            n: 'item',
            col: true,
            ti: '.DataChoiceType.Item'
          }]
      }, {
        ln: 'AnyScalarPropertyType',
        ps: [{
            n: '_boolean',
            en: 'Boolean',
            ti: '.BooleanType'
          }, {
            n: 'count',
            en: 'Count',
            ti: '.CountType'
          }, {
            n: 'quantity',
            en: 'Quantity',
            ti: '.QuantityType'
          }, {
            n: 'time',
            en: 'Time',
            ti: '.TimeType'
          }, {
            n: 'category',
            en: 'Category',
            ti: '.CategoryType'
          }, {
            n: 'text',
            en: 'Text',
            ti: '.TextType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'DataArrayType.ElementType',
        tn: null,
        bti: '.AbstractDataComponentPropertyType',
        ps: [{
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }]
      }, {
        ln: 'QuantityRangeType',
        bti: '.AbstractSimpleComponentType',
        ps: [{
            n: 'uom',
            ti: '.UnitReference'
          }, {
            n: 'constraint',
            ti: '.AllowedValuesPropertyType'
          }, {
            n: 'value',
            ti: {
              t: 'l',
              bti: 'Double'
            }
          }]
      }, {
        ln: 'AllowedTokensPropertyType',
        ps: [{
            n: 'allowedTokens',
            en: 'AllowedTokens',
            ti: '.AllowedTokensType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'XMLEncodingType',
        bti: '.AbstractEncodingType'
      }, {
        ln: 'AbstractDataComponentType',
        bti: '.AbstractSWEIdentifiableType',
        ps: [{
            n: 'updatable',
            ti: 'Boolean',
            an: {
              lp: 'updatable'
            },
            t: 'a'
          }, {
            n: 'optional',
            ti: 'Boolean',
            an: {
              lp: 'optional'
            },
            t: 'a'
          }, {
            n: 'definition',
            an: {
              lp: 'definition'
            },
            t: 'a'
          }]
      }, {
        ln: 'ComponentType',
        bti: '.AbstractSWEType',
        ps: [{
            n: 'encryption',
            an: {
              lp: 'encryption'
            },
            t: 'a'
          }, {
            n: 'significantBits',
            ti: 'Integer',
            an: {
              lp: 'significantBits'
            },
            t: 'a'
          }, {
            n: 'bitLength',
            ti: 'Integer',
            an: {
              lp: 'bitLength'
            },
            t: 'a'
          }, {
            n: 'byteLength',
            ti: 'Integer',
            an: {
              lp: 'byteLength'
            },
            t: 'a'
          }, {
            n: 'dataType',
            an: {
              lp: 'dataType'
            },
            t: 'a'
          }, {
            n: 'ref',
            an: {
              lp: 'ref'
            },
            t: 'a'
          }]
      }, {
        ln: 'TextEncodingType',
        bti: '.AbstractEncodingType',
        ps: [{
            n: 'collapseWhiteSpaces',
            ti: 'Boolean',
            an: {
              lp: 'collapseWhiteSpaces'
            },
            t: 'a'
          }, {
            n: 'decimalSeparator',
            an: {
              lp: 'decimalSeparator'
            },
            t: 'a'
          }, {
            n: 'tokenSeparator',
            an: {
              lp: 'tokenSeparator'
            },
            t: 'a'
          }, {
            n: 'blockSeparator',
            an: {
              lp: 'blockSeparator'
            },
            t: 'a'
          }]
      }, {
        ln: 'DataChoicePropertyByValueType',
        ps: [{
            n: 'dataChoice',
            en: 'DataChoice',
            ti: '.DataChoiceType'
          }]
      }, {
        ln: 'CategoryRangeType',
        bti: '.AbstractSimpleComponentType',
        ps: [{
            n: 'codeSpace',
            ti: '.Reference'
          }, {
            n: 'constraint',
            ti: '.AllowedTokensPropertyType'
          }, {
            n: 'value',
            ti: {
              t: 'l'
            }
          }]
      }, {
        ln: 'BinaryEncodingPropertyByValueType',
        ps: [{
            n: 'binaryEncoding',
            en: 'BinaryEncoding',
            ti: '.BinaryEncodingType'
          }]
      }, {
        ln: 'QuantityRangePropertyType',
        ps: [{
            n: 'quantityRange',
            en: 'QuantityRange',
            ti: '.QuantityRangeType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'VectorType.Coordinate',
        tn: null,
        bti: '.AnyNumericalPropertyType',
        ps: [{
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }]
      }, {
        ln: 'TextType',
        bti: '.AbstractSimpleComponentType',
        ps: [{
            n: 'constraint',
            ti: '.AllowedTokensPropertyType'
          }, {
            n: 'value'
          }]
      }, {
        ln: 'DataArrayType.Encoding',
        tn: null,
        ps: [{
            n: 'abstractEncoding',
            mx: false,
            dom: false,
            en: 'AbstractEncoding',
            ti: '.AbstractEncodingType',
            t: 'er'
          }]
      }, {
        ln: 'CountRangePropertyType',
        ps: [{
            n: 'countRange',
            en: 'CountRange',
            ti: '.CountRangeType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'CountPropertyType',
        ps: [{
            n: 'count',
            en: 'Count',
            ti: '.CountType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'DataChoicePropertyType',
        ps: [{
            n: 'dataChoice',
            en: 'DataChoice',
            ti: '.DataChoiceType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'VectorPropertyByValueType',
        ps: [{
            n: 'vector',
            en: 'Vector',
            ti: '.VectorType'
          }]
      }, {
        ln: 'DataStreamType.ElementType',
        tn: null,
        bti: '.AbstractDataComponentPropertyType',
        ps: [{
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }]
      }, {
        ln: 'QualityPropertyType',
        ps: [{
            n: 'quantity',
            en: 'Quantity',
            ti: '.QuantityType'
          }, {
            n: 'quantityRange',
            en: 'QuantityRange',
            ti: '.QuantityRangeType'
          }, {
            n: 'category',
            en: 'Category',
            ti: '.CategoryType'
          }, {
            n: 'text',
            en: 'Text',
            ti: '.TextType'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'MatrixType',
        bti: '.DataArrayType',
        ps: [{
            n: 'referenceFrame',
            an: {
              lp: 'referenceFrame'
            },
            t: 'a'
          }, {
            n: 'localFrame',
            an: {
              lp: 'localFrame'
            },
            t: 'a'
          }]
      }, {
        ln: 'DataStreamPropertyByValueType',
        ps: [{
            n: 'dataStream',
            en: 'DataStream',
            ti: '.DataStreamType'
          }]
      }, {
        ln: 'ComponentPropertyByValueType',
        ps: [{
            n: 'component',
            en: 'Component',
            ti: '.ComponentType'
          }]
      }, {
        t: 'enum',
        ln: 'ByteEncodingType',
        vs: ['base64', 'raw']
      }, {
        t: 'enum',
        ln: 'ByteOrderType',
        vs: ['bigEndian', 'littleEndian']
      }, {
        t: 'enum',
        ln: 'TimeIndeterminateValue',
        vs: ['now']
      }],
    eis: [{
        en: 'AbstractSimpleComponent',
        ti: '.AbstractSimpleComponentType',
        sh: 'AbstractDataComponent'
      }, {
        en: 'BinaryEncoding',
        ti: '.BinaryEncodingType',
        sh: 'AbstractEncoding'
      }, {
        en: 'Quantity',
        ti: '.QuantityType',
        sh: 'AbstractSimpleComponent'
      }, {
        en: 'Time',
        ti: '.TimeType',
        sh: 'AbstractSimpleComponent'
      }, {
        en: 'Count',
        ti: '.CountType',
        sh: 'AbstractSimpleComponent'
      }, {
        en: 'interval',
        ti: {
          t: 'l'
        },
        sc: '.AllowedTimesType'
      }, {
        en: 'DataStream',
        ti: '.DataStreamType',
        sh: 'AbstractSWEIdentifiable'
      }, {
        en: 'AllowedTimes',
        ti: '.AllowedTimesType',
        sh: 'AbstractSWE'
      }, {
        en: 'Block',
        ti: '.BlockType',
        sh: 'AbstractSWE'
      }, {
        en: 'AbstractDataComponent',
        ti: '.AbstractDataComponentType',
        sh: 'AbstractSWEIdentifiable'
      }, {
        en: 'Boolean',
        ti: '.BooleanType',
        sh: 'AbstractSimpleComponent'
      }, {
        en: 'AbstractSWEIdentifiable',
        ti: '.AbstractSWEIdentifiableType',
        sh: 'AbstractSWE'
      }, {
        en: 'Vector',
        ti: '.VectorType',
        sh: 'AbstractDataComponent'
      }, {
        en: 'DataChoice',
        ti: '.DataChoiceType',
        sh: 'AbstractDataComponent'
      }, {
        en: 'DataArray',
        ti: '.DataArrayType',
        sh: 'AbstractDataComponent'
      }, {
        en: 'Category',
        ti: '.CategoryType',
        sh: 'AbstractSimpleComponent'
      }, {
        en: 'Component',
        ti: '.ComponentType',
        sh: 'AbstractSWE'
      }, {
        en: 'TextEncoding',
        ti: '.TextEncodingType',
        sh: 'AbstractEncoding'
      }, {
        en: 'Text',
        ti: '.TextType',
        sh: 'AbstractSimpleComponent'
      }, {
        en: 'CountRange',
        ti: '.CountRangeType',
        sh: 'AbstractSimpleComponent'
      }, {
        en: 'NilValues',
        ti: '.NilValuesType',
        sh: 'AbstractSWE'
      }, {
        en: 'AbstractEncoding',
        ti: '.AbstractEncodingType',
        sh: 'AbstractSWE'
      }, {
        en: 'XMLEncoding',
        ti: '.XMLEncodingType',
        sh: 'AbstractEncoding'
      }, {
        en: 'AllowedValues',
        ti: '.AllowedValuesType',
        sh: 'AbstractSWE'
      }, {
        en: 'AllowedTokens',
        ti: '.AllowedTokensType',
        sh: 'AbstractSWE'
      }, {
        en: 'QuantityRange',
        ti: '.QuantityRangeType',
        sh: 'AbstractSimpleComponent'
      }, {
        en: 'value',
        ti: {
          t: 'l'
        },
        sc: '.AllowedTimesType'
      }, {
        en: 'interval',
        ti: {
          t: 'l',
          bti: 'Double'
        },
        sc: '.AllowedValuesType'
      }, {
        en: 'CategoryRange',
        ti: '.CategoryRangeType',
        sh: 'AbstractSimpleComponent'
      }, {
        en: 'AbstractSWE',
        ti: '.AbstractSWEType'
      }, {
        en: 'DataRecord',
        ti: '.DataRecordType',
        sh: 'AbstractDataComponent'
      }, {
        en: 'Matrix',
        ti: '.MatrixType',
        sh: 'DataArray'
      }, {
        en: 'TimeRange',
        ti: '.TimeRangeType',
        sh: 'AbstractSimpleComponent'
      }]
  };
  return {
    SWE_2_0: SWE_2_0
  };
};
if (typeof define === 'function' && define.amd) {
  define([], SWE_2_0_Module_Factory);
}
else {
  var SWE_2_0_Module = SWE_2_0_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.SWE_2_0 = SWE_2_0_Module.SWE_2_0;
  }
  else {
    var SWE_2_0 = SWE_2_0_Module.SWE_2_0;
  }
}