var SWE_1_0_1_Module_Factory = function () {
  var SWE_1_0_1 = {
    n: 'SWE_1_0_1',
    dens: 'http:\/\/www.opengis.net\/swe\/1.0.1',
    dans: 'http:\/\/www.w3.org\/1999\/xlink',
    deps: ['XLink_1_0', 'GML_3_1_1'],
    tis: [{
        ln: 'AllowedTokens',
        tn: null,
        ps: [{
            n: 'valueList',
            col: true,
            mx: false,
            dom: false,
            ti: {
              t: 'l'
            },
            t: 'er'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }]
      }, {
        ln: 'IntervalPropertyType',
        ps: [{
            n: 'interval',
            en: 'Interval',
            ti: '.IntervalType'
          }]
      }, {
        ln: 'ConditionalValueType.Data',
        tn: null,
        ps: [{
            n: 'count',
            en: 'Count',
            ti: '.Count'
          }, {
            n: 'quantity',
            en: 'Quantity',
            ti: '.Quantity'
          }, {
            n: 'time',
            en: 'Time',
            ti: '.Time'
          }, {
            n: '_boolean',
            en: 'Boolean',
            ti: '.Boolean'
          }, {
            n: 'category',
            en: 'Category',
            ti: '.Category'
          }, {
            n: 'text',
            en: 'Text',
            ti: '.Text'
          }, {
            n: 'quantityRange',
            en: 'QuantityRange',
            ti: '.QuantityRange'
          }, {
            n: 'countRange',
            en: 'CountRange',
            ti: '.CountRange'
          }, {
            n: 'timeRange',
            en: 'TimeRange',
            ti: '.TimeRange'
          }, {
            n: 'abstractDataRecord',
            mx: false,
            dom: false,
            en: 'AbstractDataRecord',
            ti: '.AbstractDataRecordType',
            t: 'er'
          }, {
            n: 'abstractDataArray',
            mx: false,
            dom: false,
            en: 'AbstractDataArray',
            ti: '.AbstractDataArrayType',
            t: 'er'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'QualityPropertyType',
        ps: [{
            n: 'quantity',
            en: 'Quantity',
            ti: '.Quantity'
          }, {
            n: 'quantityRange',
            en: 'QuantityRange',
            ti: '.QuantityRange'
          }, {
            n: 'category',
            en: 'Category',
            ti: '.Category'
          }, {
            n: 'text',
            en: 'Text',
            ti: '.Text'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'CompoundPhenomenonType',
        bti: '.PhenomenonType',
        ps: [{
            n: 'dimension',
            ti: 'Integer',
            an: {
              lp: 'dimension'
            },
            t: 'a'
          }]
      }, {
        ln: 'TimeObjectPropertyType',
        ps: [{
            n: 'timeObject',
            mx: false,
            dom: false,
            en: {
              lp: '_TimeObject',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            ti: 'GML_3_1_1.AbstractTimeObjectType',
            t: 'er'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'BinaryBlock.Member',
        tn: null,
        ps: [{
            n: 'component',
            en: 'Component',
            ti: '.BinaryBlock.Member.Component'
          }, {
            n: 'block',
            en: 'Block',
            ti: '.BinaryBlock.Member.Block'
          }]
      }, {
        ln: 'QuantityRange',
        tn: null,
        bti: '.AbstractDataComponentType',
        ps: [{
            n: 'uom',
            ti: '.UomPropertyType'
          }, {
            n: 'constraint',
            ti: '.AllowedValuesPropertyType'
          }, {
            n: 'quality',
            col: true,
            ti: '.QualityPropertyType'
          }, {
            n: 'value',
            ti: {
              t: 'l',
              bti: 'Double'
            }
          }, {
            n: 'referenceFrame',
            an: {
              lp: 'referenceFrame'
            },
            t: 'a'
          }, {
            n: 'axisID',
            an: {
              lp: 'axisID'
            },
            t: 'a'
          }]
      }, {
        ln: 'TimeRangePropertyType',
        ps: [{
            n: 'timeRange',
            en: 'TimeRange',
            ti: '.TimeRange'
          }]
      }, {
        ln: 'Quantity',
        tn: null,
        bti: '.AbstractDataComponentType',
        ps: [{
            n: 'uom',
            ti: '.UomPropertyType'
          }, {
            n: 'constraint',
            ti: '.AllowedValuesPropertyType'
          }, {
            n: 'quality',
            col: true,
            ti: '.QualityPropertyType'
          }, {
            n: 'value',
            ti: 'Double'
          }, {
            n: 'referenceFrame',
            an: {
              lp: 'referenceFrame'
            },
            t: 'a'
          }, {
            n: 'axisID',
            an: {
              lp: 'axisID'
            },
            t: 'a'
          }]
      }, {
        ln: 'Count',
        tn: null,
        bti: '.AbstractDataComponentType',
        ps: [{
            n: 'constraint',
            ti: '.AllowedValuesPropertyType'
          }, {
            n: 'quality',
            col: true,
            ti: '.QualityPropertyType'
          }, {
            n: 'value',
            ti: 'Integer'
          }, {
            n: 'referenceFrame',
            an: {
              lp: 'referenceFrame'
            },
            t: 'a'
          }, {
            n: 'axisID',
            an: {
              lp: 'axisID'
            },
            t: 'a'
          }]
      }, {
        ln: 'BinaryBlock',
        tn: null,
        bti: '.AbstractEncodingType',
        ps: [{
            n: 'member',
            col: true,
            ti: '.BinaryBlock.Member'
          }, {
            n: 'byteLength',
            ti: 'Integer',
            an: {
              lp: 'byteLength'
            },
            t: 'a'
          }, {
            n: 'byteEncoding',
            an: {
              lp: 'byteEncoding'
            },
            t: 'a'
          }, {
            n: 'byteOrder',
            an: {
              lp: 'byteOrder'
            },
            t: 'a'
          }]
      }, {
        ln: 'ArrayType',
        ps: [{
            n: 'element',
            col: true,
            ti: '.XMLDataPropertyType'
          }, {
            n: 'rs',
            an: {
              lp: 'RS'
            },
            t: 'a'
          }, {
            n: 'elementCount',
            ti: 'Integer',
            an: {
              lp: 'elementCount'
            },
            t: 'a'
          }]
      }, {
        ln: 'ConstrainedPhenomenonType',
        bti: '.PhenomenonType',
        ps: [{
            n: 'base',
            ti: '.PhenomenonPropertyType'
          }, {
            n: 'otherConstraint',
            col: true
          }, {
            n: 'singleConstraint',
            col: true,
            ti: '.AnyDataPropertyType'
          }]
      }, {
        ln: 'DataRecordPropertyType',
        ps: [{
            n: 'dataRecord',
            en: 'DataRecord',
            ti: '.DataRecordType'
          }]
      }, {
        ln: 'CurveType',
        bti: '.AbstractDataArrayType',
        ps: [{
            n: 'elementType',
            ti: '.SimpleDataRecordPropertyType'
          }, {
            n: 'encoding',
            ti: '.BlockEncodingPropertyType'
          }, {
            n: 'values',
            ti: '.DataValuePropertyType'
          }]
      }, {
        ln: 'TimeInstantGridType',
        bti: '.TimeGridType'
      }, {
        ln: 'Text',
        tn: null,
        bti: '.AbstractDataComponentType',
        ps: [{
            n: 'value'
          }]
      }, {
        ln: 'AbstractEncodingType',
        ps: [{
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }]
      }, {
        ln: 'TimeAggregatePropertyType',
        ps: [{
            n: 'timeAggregate',
            en: 'TimeAggregate',
            ti: '.TimeAggregateType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'RecordPropertyType',
        ps: [{
            n: 'record',
            en: 'Record',
            ti: '.RecordType'
          }]
      }, {
        ln: 'ObservableProperty',
        tn: null,
        bti: '.AbstractDataComponentType'
      }, {
        ln: 'ArrayPropertyType',
        ps: [{
            n: 'array',
            en: 'Array',
            ti: '.ArrayType'
          }]
      }, {
        ln: 'AnyScalarPropertyType',
        ps: [{
            n: 'count',
            en: 'Count',
            ti: '.Count'
          }, {
            n: 'quantity',
            en: 'Quantity',
            ti: '.Quantity'
          }, {
            n: 'time',
            en: 'Time',
            ti: '.Time'
          }, {
            n: '_boolean',
            en: 'Boolean',
            ti: '.Boolean'
          }, {
            n: 'category',
            en: 'Category',
            ti: '.Category'
          }, {
            n: 'text',
            en: 'Text',
            ti: '.Text'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'QuantityPropertyType',
        ps: [{
            n: 'quantity',
            en: 'Quantity',
            ti: '.Quantity'
          }]
      }, {
        ln: 'ConditionalDataType',
        bti: '.AbstractDataRecordType',
        ps: [{
            n: '_case',
            col: true,
            en: 'case',
            ti: '.ConditionalDataType.Case'
          }]
      }, {
        ln: 'PhenomenonPropertyType',
        ps: [{
            n: 'phenomenon',
            mx: false,
            dom: false,
            en: 'Phenomenon',
            ti: '.PhenomenonType',
            t: 'er'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'EnvelopeType',
        bti: '.AbstractVectorType',
        ps: [{
            n: 'time',
            ti: '.TimeRangePropertyType'
          }, {
            n: 'lowerCorner',
            ti: '.VectorPropertyType'
          }, {
            n: 'upperCorner',
            ti: '.VectorPropertyType'
          }]
      }, {
        ln: 'TimeIntervalGridPropertyType',
        ps: [{
            n: 'timeIntervalGrid',
            en: 'TimeIntervalGrid',
            ti: '.TimeIntervalGridType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'DataStreamDefinitionPropertyType',
        ps: [{
            n: 'dataStreamDefinition',
            en: 'DataStreamDefinition',
            ti: '.DataStreamDefinitionType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'CountPropertyType',
        ps: [{
            n: 'count',
            en: 'Count',
            ti: '.Count'
          }]
      }, {
        ln: 'TimeGridEnvelopePropertyType.TimeGridEnvelope',
        tn: null,
        ps: [{
            n: 'low',
            ti: 'Integer'
          }, {
            n: 'high',
            ti: 'Integer'
          }]
      }, {
        ln: 'AbstractDataArrayType',
        bti: '.AbstractDataComponentType',
        ps: [{
            n: 'elementCount',
            ti: '.AbstractDataArrayType.ElementCount'
          }]
      }, {
        ln: 'AbstractConditionalType.Condition',
        tn: null,
        ps: [{
            n: 'count',
            en: 'Count',
            ti: '.Count'
          }, {
            n: 'quantity',
            en: 'Quantity',
            ti: '.Quantity'
          }, {
            n: 'time',
            en: 'Time',
            ti: '.Time'
          }, {
            n: '_boolean',
            en: 'Boolean',
            ti: '.Boolean'
          }, {
            n: 'category',
            en: 'Category',
            ti: '.Category'
          }, {
            n: 'text',
            en: 'Text',
            ti: '.Text'
          }, {
            n: 'quantityRange',
            en: 'QuantityRange',
            ti: '.QuantityRange'
          }, {
            n: 'countRange',
            en: 'CountRange',
            ti: '.CountRange'
          }, {
            n: 'timeRange',
            en: 'TimeRange',
            ti: '.TimeRange'
          }, {
            n: 'abstractDataRecord',
            mx: false,
            dom: false,
            en: 'AbstractDataRecord',
            ti: '.AbstractDataRecordType',
            t: 'er'
          }, {
            n: 'abstractDataArray',
            mx: false,
            dom: false,
            en: 'AbstractDataArray',
            ti: '.AbstractDataArrayType',
            t: 'er'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'MultiplexedStreamFormatType',
        bti: '.AbstractEncodingType',
        ps: [{
            n: 'type',
            an: {
              lp: 'type'
            },
            t: 'a'
          }, {
            n: 'version',
            an: {
              lp: 'version'
            },
            t: 'a'
          }]
      }, {
        ln: 'TimeRange',
        tn: null,
        bti: '.AbstractDataComponentType',
        ps: [{
            n: 'uom',
            ti: '.UomPropertyType'
          }, {
            n: 'constraint',
            ti: '.AllowedTimesPropertyType'
          }, {
            n: 'quality',
            ti: '.QualityPropertyType'
          }, {
            n: 'value',
            ti: {
              t: 'l'
            }
          }, {
            n: 'referenceTime',
            an: {
              lp: 'referenceTime'
            },
            t: 'a'
          }, {
            n: 'referenceFrame',
            an: {
              lp: 'referenceFrame'
            },
            t: 'a'
          }, {
            n: 'localFrame',
            an: {
              lp: 'localFrame'
            },
            t: 'a'
          }]
      }, {
        ln: 'PhenomenonSeriesType',
        bti: '.CompoundPhenomenonType',
        ps: [{
            n: 'base',
            ti: '.PhenomenonPropertyType'
          }, {
            n: 'constraintList',
            col: true,
            ti: '.DataArrayPropertyType'
          }, {
            n: 'otherConstraint',
            col: true
          }]
      }, {
        ln: 'TimePropertyType',
        ps: [{
            n: 'time',
            en: 'Time',
            ti: '.Time'
          }]
      }, {
        ln: 'AbstractConditionalType',
        bti: '.AbstractDataRecordType',
        ps: [{
            n: 'condition',
            col: true,
            ti: '.AbstractConditionalType.Condition'
          }]
      }, {
        ln: 'TimeGeometricComplexType',
        bti: 'GML_3_1_1.AbstractTimeComplexType',
        ps: [{
            n: 'primitive',
            col: true,
            ti: '.TimeGeometricPrimitivePropertyType'
          }]
      }, {
        ln: 'PositionType',
        bti: '.AbstractVectorType',
        ps: [{
            n: 'time',
            ti: '.TimePropertyType'
          }, {
            n: 'location',
            ti: '.VectorPropertyType'
          }, {
            n: 'orientation',
            ti: '.VectorOrSquareMatrixPropertyType'
          }, {
            n: 'velocity',
            ti: '.VectorPropertyType'
          }, {
            n: 'angularVelocity',
            ti: '.VectorOrSquareMatrixPropertyType'
          }, {
            n: 'acceleration',
            ti: '.VectorPropertyType'
          }, {
            n: 'angularAcceleration',
            ti: '.VectorOrSquareMatrixPropertyType'
          }, {
            n: 'state',
            ti: '.VectorOrSquareMatrixPropertyType'
          }]
      }, {
        ln: 'XMLDataPropertyType',
        ps: [{
            n: 'item',
            en: 'Item',
            ti: 'AnyType'
          }, {
            n: 'record',
            en: 'Record',
            ti: '.RecordType'
          }, {
            n: 'array',
            en: 'Array',
            ti: '.ArrayType'
          }]
      }, {
        ln: 'AllowedValues',
        tn: null,
        ps: [{
            n: 'min',
            ti: 'Double'
          }, {
            n: 'max',
            ti: 'Double'
          }, {
            n: 'intervalOrValueList',
            col: true,
            mx: false,
            dom: false,
            etis: [{
                en: 'interval',
                ti: {
                  t: 'l',
                  bti: 'Double'
                }
              }, {
                en: 'valueList',
                ti: {
                  t: 'l',
                  bti: 'Double'
                }
              }],
            t: 'ers'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }]
      }, {
        ln: 'AbstractMatrixType',
        bti: '.AbstractDataArrayType',
        ps: [{
            n: 'referenceFrame',
            an: {
              lp: 'referenceFrame'
            },
            t: 'a'
          }, {
            n: 'localFrame',
            an: {
              lp: 'localFrame'
            },
            t: 'a'
          }]
      }, {
        ln: 'DataStreamDefinitionType',
        ps: [{
            n: 'streamComponent',
            col: true,
            ti: '.DataBlockDefinitionPropertyType'
          }, {
            n: 'streamEncoding',
            ti: '.MultiplexedStreamFormatPropertyType'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }]
      }, {
        ln: 'VectorType',
        bti: '.AbstractVectorType',
        ps: [{
            n: 'coordinate',
            col: true,
            ti: '.VectorType.Coordinate'
          }]
      }, {
        ln: 'CurvePropertyType',
        ps: [{
            n: 'curve',
            en: 'Curve',
            ti: '.CurveType'
          }]
      }, {
        ln: 'XMLBlockType',
        bti: '.AbstractEncodingType',
        ps: [{
            n: 'xmlElement',
            ti: 'QName',
            an: {
              lp: 'xmlElement'
            },
            t: 'a'
          }]
      }, {
        ln: 'EnvelopePropertyType',
        ps: [{
            n: 'envelope',
            en: 'Envelope',
            ti: '.EnvelopeType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'StandardFormat',
        tn: null,
        bti: '.AbstractEncodingType',
        ps: [{
            n: 'mimeType',
            an: {
              lp: 'mimeType'
            },
            t: 'a'
          }]
      }, {
        ln: 'DataArrayPropertyType',
        ps: [{
            n: 'dataArray',
            en: 'DataArray',
            ti: '.DataArrayType'
          }]
      }, {
        ln: 'BooleanPropertyType',
        ps: [{
            n: '_boolean',
            en: 'Boolean',
            ti: '.Boolean'
          }]
      }, {
        ln: 'TimeGridType',
        bti: 'GML_3_1_1.AbstractTimeComplexType',
        ps: [{
            n: 'extent',
            ti: '.TimeGridEnvelopePropertyType'
          }, {
            n: 'originPos',
            ti: 'GML_3_1_1.TimePositionType'
          }, {
            n: 'origin',
            ti: 'GML_3_1_1.TimeInstantPropertyType'
          }, {
            n: 'offsetDuration'
          }, {
            n: 'offsetInterval',
            ti: 'GML_3_1_1.TimeIntervalLengthType'
          }, {
            n: 'duration'
          }]
      }, {
        ln: 'VectorType.Coordinate',
        tn: null,
        ps: [{
            n: 'count',
            en: 'Count',
            ti: '.Count'
          }, {
            n: 'quantity',
            en: 'Quantity',
            ti: '.Quantity'
          }, {
            n: 'time',
            en: 'Time',
            ti: '.Time'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }]
      }, {
        ln: 'Category',
        tn: null,
        bti: '.AbstractDataComponentType',
        ps: [{
            n: 'codeSpace',
            ti: '.CodeSpacePropertyType'
          }, {
            n: 'constraint',
            ti: '.AllowedTokensPropertyType'
          }, {
            n: 'quality',
            ti: '.QualityPropertyType'
          }, {
            n: 'value'
          }, {
            n: 'referenceFrame',
            an: {
              lp: 'referenceFrame'
            },
            t: 'a'
          }, {
            n: 'axisID',
            an: {
              lp: 'axisID'
            },
            t: 'a'
          }]
      }, {
        ln: 'RecordType',
        ps: [{
            n: 'field',
            col: true,
            ti: '.ItemPropertyType'
          }, {
            n: 'rs',
            an: {
              lp: 'RS'
            },
            t: 'a'
          }, {
            n: 'fieldCount',
            ti: 'Integer',
            an: {
              lp: 'fieldCount'
            },
            t: 'a'
          }]
      }, {
        ln: 'TextPropertyType',
        ps: [{
            n: 'text',
            en: 'Text',
            ti: '.Text'
          }]
      }, {
        ln: 'BlockEncodingPropertyType',
        ps: [{
            n: 'standardFormat',
            en: 'StandardFormat',
            ti: '.StandardFormat'
          }, {
            n: 'binaryBlock',
            en: 'BinaryBlock',
            ti: '.BinaryBlock'
          }, {
            n: 'textBlock',
            en: 'TextBlock',
            ti: '.TextBlock'
          }, {
            n: 'xmlBlock',
            en: 'XMLBlock',
            ti: '.XMLBlockType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'TextBlock',
        tn: null,
        bti: '.AbstractEncodingType',
        ps: [{
            n: 'tokenSeparator',
            an: {
              lp: 'tokenSeparator'
            },
            t: 'a'
          }, {
            n: 'blockSeparator',
            an: {
              lp: 'blockSeparator'
            },
            t: 'a'
          }, {
            n: 'decimalSeparator',
            an: {
              lp: 'decimalSeparator'
            },
            t: 'a'
          }]
      }, {
        ln: 'IntervalType',
        ps: [{
            n: 'lowerBound',
            ti: 'AnyType'
          }, {
            n: 'upperBound',
            ti: 'AnyType'
          }]
      }, {
        ln: 'AllowedTimesPropertyType',
        ps: [{
            n: 'allowedTimes',
            en: 'AllowedTimes',
            ti: '.AllowedTimes'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'TimeGeometricPrimitivePropertyType',
        ps: [{
            n: 'timeGeometricPrimitive',
            mx: false,
            dom: false,
            en: {
              lp: '_TimeGeometricPrimitive',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            ti: 'GML_3_1_1.AbstractTimeGeometricPrimitiveType',
            t: 'er'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'TimeInstantGridPropertyType',
        ps: [{
            n: 'timeInstantGrid',
            en: 'TimeInstantGrid',
            ti: '.TimeInstantGridType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'SquareMatrixType',
        bti: '.AbstractMatrixType',
        ps: [{
            n: 'elementType',
            ti: '.QuantityPropertyType'
          }, {
            n: 'encoding',
            ti: '.BlockEncodingPropertyType'
          }, {
            n: 'values',
            ti: '.DataValuePropertyType'
          }]
      }, {
        ln: 'TimeGeometricComplexPropertyType',
        ps: [{
            n: 'timeGeometricComplex',
            en: 'TimeGeometricComplex',
            ti: '.TimeGeometricComplexType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'UomPropertyType',
        ps: [{
            n: 'unitDefinition',
            mx: false,
            dom: false,
            en: {
              lp: 'UnitDefinition',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            ti: 'GML_3_1_1.UnitDefinitionType',
            t: 'er'
          }, {
            n: 'code',
            an: {
              lp: 'code'
            },
            t: 'a'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'TimeIntervalGridType',
        bti: '.TimeGridType',
        ps: [{
            n: 'windowDuration'
          }, {
            n: 'windowInterval',
            ti: 'GML_3_1_1.TimeIntervalLengthType'
          }]
      }, {
        ln: 'VectorOrSquareMatrixPropertyType',
        ps: [{
            n: 'vector',
            en: 'Vector',
            ti: '.VectorType'
          }, {
            n: 'squareMatrix',
            en: 'SquareMatrix',
            ti: '.SquareMatrixType'
          }]
      }, {
        ln: 'CountRange',
        tn: null,
        bti: '.AbstractDataComponentType',
        ps: [{
            n: 'constraint',
            ti: '.AllowedValuesPropertyType'
          }, {
            n: 'quality',
            col: true,
            ti: '.QualityPropertyType'
          }, {
            n: 'value',
            ti: {
              t: 'l',
              bti: 'Integer'
            }
          }, {
            n: 'referenceFrame',
            an: {
              lp: 'referenceFrame'
            },
            t: 'a'
          }, {
            n: 'axisID',
            an: {
              lp: 'axisID'
            },
            t: 'a'
          }]
      }, {
        ln: 'TimeAggregateType',
        bti: 'GML_3_1_1.AbstractTimeObjectType',
        ps: [{
            n: 'member',
            col: true,
            ti: '.TimeObjectPropertyType'
          }]
      }, {
        ln: 'AllowedValuesPropertyType',
        ps: [{
            n: 'allowedValues',
            en: 'AllowedValues',
            ti: '.AllowedValues'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'DataValuePropertyType',
        ps: [{
            n: 'otherAttributes',
            t: 'aa'
          }, {
            n: 'content',
            col: true,
            typed: false,
            t: 'ae'
          }, {
            n: 'recordCount',
            ti: 'Integer',
            an: {
              lp: 'recordCount'
            },
            t: 'a'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'SimpleDataRecordPropertyType',
        ps: [{
            n: 'simpleDataRecord',
            en: 'SimpleDataRecord',
            ti: '.SimpleDataRecordType'
          }]
      }, {
        ln: 'DataComponentPropertyType',
        ps: [{
            n: 'count',
            en: 'Count',
            ti: '.Count'
          }, {
            n: 'quantity',
            en: 'Quantity',
            ti: '.Quantity'
          }, {
            n: 'time',
            en: 'Time',
            ti: '.Time'
          }, {
            n: '_boolean',
            en: 'Boolean',
            ti: '.Boolean'
          }, {
            n: 'category',
            en: 'Category',
            ti: '.Category'
          }, {
            n: 'text',
            en: 'Text',
            ti: '.Text'
          }, {
            n: 'quantityRange',
            en: 'QuantityRange',
            ti: '.QuantityRange'
          }, {
            n: 'countRange',
            en: 'CountRange',
            ti: '.CountRange'
          }, {
            n: 'timeRange',
            en: 'TimeRange',
            ti: '.TimeRange'
          }, {
            n: 'abstractDataRecord',
            mx: false,
            dom: false,
            en: 'AbstractDataRecord',
            ti: '.AbstractDataRecordType',
            t: 'er'
          }, {
            n: 'abstractDataArray',
            mx: false,
            dom: false,
            en: 'AbstractDataArray',
            ti: '.AbstractDataArrayType',
            t: 'er'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'AbstractDataArrayType.ElementCount',
        tn: null,
        ps: [{
            n: 'count',
            en: 'Count',
            ti: '.Count'
          }, {
            n: 'ref',
            ti: 'IDREF',
            an: {
              lp: 'ref'
            },
            t: 'a'
          }]
      }, {
        ln: 'BinaryBlock.Member.Block',
        tn: null,
        ps: [{
            n: 'ref',
            an: {
              lp: 'ref'
            },
            t: 'a'
          }, {
            n: 'byteLength',
            ti: 'Integer',
            an: {
              lp: 'byteLength'
            },
            t: 'a'
          }, {
            n: 'paddingBytesBefore',
            ti: 'Integer',
            an: {
              lp: 'paddingBytes-before'
            },
            t: 'a'
          }, {
            n: 'paddingBytesAfter',
            ti: 'Integer',
            an: {
              lp: 'paddingBytes-after'
            },
            t: 'a'
          }, {
            n: 'encryption',
            an: {
              lp: 'encryption'
            },
            t: 'a'
          }, {
            n: 'compression',
            an: {
              lp: 'compression'
            },
            t: 'a'
          }]
      }, {
        ln: 'MultiplexedStreamFormatPropertyType',
        ps: [{
            n: 'multiplexedStreamFormat',
            en: 'MultiplexedStreamFormat',
            ti: '.MultiplexedStreamFormatType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'DataRecordType',
        bti: '.AbstractDataRecordType',
        ps: [{
            n: 'field',
            col: true,
            ti: '.DataComponentPropertyType'
          }]
      }, {
        ln: 'AllowedTimes',
        tn: null,
        ps: [{
            n: 'min',
            ti: {
              t: 'l'
            }
          }, {
            n: 'max',
            ti: {
              t: 'l'
            }
          }, {
            n: 'intervalOrValueList',
            col: true,
            mx: false,
            dom: false,
            etis: [{
                en: 'interval',
                ti: {
                  t: 'l'
                }
              }, {
                en: 'valueList',
                ti: {
                  t: 'l'
                }
              }],
            t: 'ers'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }]
      }, {
        ln: 'GeoLocationArea',
        tn: null,
        bti: '.AbstractVectorType',
        ps: [{
            n: 'member',
            col: true,
            ti: '.EnvelopePropertyType'
          }, {
            n: 'geoLocationAreaName',
            an: {
              lp: 'name'
            },
            t: 'a'
          }]
      }, {
        ln: 'CategoryPropertyType',
        ps: [{
            n: 'category',
            en: 'Category',
            ti: '.Category'
          }]
      }, {
        ln: 'TimeGridEnvelopePropertyType',
        ps: [{
            n: 'timeGridEnvelope',
            en: 'TimeGridEnvelope',
            ti: '.TimeGridEnvelopePropertyType.TimeGridEnvelope'
          }]
      }, {
        ln: 'TimePositionListType',
        ps: [{
            n: 'value',
            ti: {
              t: 'l'
            },
            t: 'v'
          }, {
            n: 'frame',
            an: {
              lp: 'frame'
            },
            t: 'a'
          }, {
            n: 'calendarEraName',
            an: {
              lp: 'calendarEraName'
            },
            t: 'a'
          }, {
            n: 'indeterminatePosition',
            ti: 'GML_3_1_1.TimeIndeterminateValueType',
            an: {
              lp: 'indeterminatePosition'
            },
            t: 'a'
          }, {
            n: 'count',
            ti: 'Integer',
            an: {
              lp: 'count'
            },
            t: 'a'
          }]
      }, {
        ln: 'AbstractDataRecordType',
        bti: '.AbstractDataComponentType'
      }, {
        ln: 'PhenomenonType',
        bti: 'GML_3_1_1.DefinitionType'
      }, {
        ln: 'DataBlockDefinitionType',
        ps: [{
            n: 'components',
            ti: '.DataComponentPropertyType'
          }, {
            n: 'encoding',
            ti: '.BlockEncodingPropertyType'
          }, {
            n: 'id',
            ti: 'ID',
            an: {
              lp: 'id'
            },
            t: 'a'
          }]
      }, {
        ln: 'VectorPropertyType',
        ps: [{
            n: 'vector',
            en: 'Vector',
            ti: '.VectorType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'AbstractVectorType',
        bti: '.AbstractDataRecordType',
        ps: [{
            n: 'referenceFrame',
            an: {
              lp: 'referenceFrame'
            },
            t: 'a'
          }, {
            n: 'localFrame',
            an: {
              lp: 'localFrame'
            },
            t: 'a'
          }]
      }, {
        ln: 'TimeGridPropertyType',
        ps: [{
            n: 'timeInstantGrid',
            en: 'TimeInstantGrid',
            ti: '.TimeInstantGridType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'Boolean',
        tn: null,
        bti: '.AbstractDataComponentType',
        ps: [{
            n: 'quality',
            ti: '.QualityPropertyType'
          }, {
            n: 'value',
            ti: 'Boolean'
          }, {
            n: 'referenceFrame',
            an: {
              lp: 'referenceFrame'
            },
            t: 'a'
          }, {
            n: 'axisID',
            an: {
              lp: 'axisID'
            },
            t: 'a'
          }]
      }, {
        ln: 'BinaryBlock.Member.Component',
        tn: null,
        ps: [{
            n: 'ref',
            an: {
              lp: 'ref'
            },
            t: 'a'
          }, {
            n: 'dataType',
            an: {
              lp: 'dataType'
            },
            t: 'a'
          }, {
            n: 'significantBits',
            ti: 'Integer',
            an: {
              lp: 'significantBits'
            },
            t: 'a'
          }, {
            n: 'bitLength',
            ti: 'Integer',
            an: {
              lp: 'bitLength'
            },
            t: 'a'
          }, {
            n: 'paddingBitsBefore',
            ti: 'Integer',
            an: {
              lp: 'paddingBits-before'
            },
            t: 'a'
          }, {
            n: 'paddingBitsAfter',
            ti: 'Integer',
            an: {
              lp: 'paddingBits-after'
            },
            t: 'a'
          }, {
            n: 'encryption',
            an: {
              lp: 'encryption'
            },
            t: 'a'
          }]
      }, {
        ln: 'NormalizedCurveType',
        bti: '.AbstractDataRecordType',
        ps: [{
            n: 'inputGain',
            ti: '.QuantityPropertyType'
          }, {
            n: 'inputBias',
            ti: '.QuantityPropertyType'
          }, {
            n: 'outputGain',
            ti: '.QuantityPropertyType'
          }, {
            n: 'outputBias',
            ti: '.QuantityPropertyType'
          }, {
            n: 'interpolationMethod',
            ti: '.CategoryPropertyType'
          }, {
            n: 'extrapolationMethod',
            ti: '.CategoryPropertyType'
          }, {
            n: 'function',
            ti: '.CurvePropertyType'
          }]
      }, {
        ln: 'AnyDataPropertyType',
        ps: [{
            n: 'count',
            en: 'Count',
            ti: '.Count'
          }, {
            n: 'quantity',
            en: 'Quantity',
            ti: '.Quantity'
          }, {
            n: 'time',
            en: 'Time',
            ti: '.Time'
          }, {
            n: '_boolean',
            en: 'Boolean',
            ti: '.Boolean'
          }, {
            n: 'category',
            en: 'Category',
            ti: '.Category'
          }, {
            n: 'text',
            en: 'Text',
            ti: '.Text'
          }, {
            n: 'quantityRange',
            en: 'QuantityRange',
            ti: '.QuantityRange'
          }, {
            n: 'countRange',
            en: 'CountRange',
            ti: '.CountRange'
          }, {
            n: 'timeRange',
            en: 'TimeRange',
            ti: '.TimeRange'
          }, {
            n: 'abstractDataRecord',
            mx: false,
            dom: false,
            en: 'AbstractDataRecord',
            ti: '.AbstractDataRecordType',
            t: 'er'
          }, {
            n: 'abstractDataArray',
            mx: false,
            dom: false,
            en: 'AbstractDataArray',
            ti: '.AbstractDataArrayType',
            t: 'er'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'CompositePhenomenonType',
        bti: '.CompoundPhenomenonType',
        ps: [{
            n: 'base',
            ti: '.PhenomenonPropertyType'
          }, {
            n: 'component',
            col: true,
            ti: '.PhenomenonPropertyType'
          }]
      }, {
        ln: 'DataBlockDefinitionPropertyType',
        ps: [{
            n: 'dataBlockDefinition',
            en: 'DataBlockDefinition',
            ti: '.DataBlockDefinitionType'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'ItemPropertyType',
        ps: [{
            n: 'item',
            en: 'Item',
            ti: 'AnyType'
          }]
      }, {
        ln: 'CodeSpacePropertyType',
        ps: [{
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'QuantityRangePropertyType',
        ps: [{
            n: 'quantityRange',
            en: 'QuantityRange',
            ti: '.QuantityRange'
          }]
      }, {
        ln: 'SimpleDataRecordType',
        bti: '.AbstractDataRecordType',
        ps: [{
            n: 'field',
            col: true,
            ti: '.AnyScalarPropertyType'
          }]
      }, {
        ln: 'Time',
        tn: null,
        bti: '.AbstractDataComponentType',
        ps: [{
            n: 'uom',
            ti: '.UomPropertyType'
          }, {
            n: 'constraint',
            ti: '.AllowedTimesPropertyType'
          }, {
            n: 'quality',
            ti: '.QualityPropertyType'
          }, {
            n: 'value',
            ti: {
              t: 'l'
            }
          }, {
            n: 'referenceTime',
            an: {
              lp: 'referenceTime'
            },
            t: 'a'
          }, {
            n: 'referenceFrame',
            an: {
              lp: 'referenceFrame'
            },
            t: 'a'
          }, {
            n: 'localFrame',
            an: {
              lp: 'localFrame'
            },
            t: 'a'
          }]
      }, {
        ln: 'ConditionalDataType.Case',
        tn: null,
        ps: [{
            n: 'conditionalValue',
            en: 'ConditionalValue',
            ti: '.ConditionalValueType'
          }, {
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'AbstractDataComponentType',
        bti: 'GML_3_1_1.AbstractGMLType',
        ps: [{
            n: 'fixed',
            ti: 'Boolean',
            an: {
              lp: 'fixed'
            },
            t: 'a'
          }, {
            n: 'definition',
            an: {
              lp: 'definition'
            },
            t: 'a'
          }]
      }, {
        ln: 'CountRangePropertyType',
        ps: [{
            n: 'countRange',
            en: 'CountRange',
            ti: '.CountRange'
          }]
      }, {
        ln: 'AllowedTokensPropertyType',
        ps: [{
            n: 'allowedTokens',
            en: 'AllowedTokens',
            ti: '.AllowedTokens'
          }, {
            n: 'remoteSchema',
            an: {
              lp: 'remoteSchema',
              ns: 'http:\/\/www.opengis.net\/gml'
            },
            t: 'a'
          }, {
            n: 'type',
            ti: 'XLink_1_0.TypeType',
            t: 'a'
          }, {
            n: 'href',
            t: 'a'
          }, {
            n: 'role',
            t: 'a'
          }, {
            n: 'arcrole',
            t: 'a'
          }, {
            n: 'title',
            t: 'a'
          }, {
            n: 'show',
            ti: 'XLink_1_0.ShowType',
            t: 'a'
          }, {
            n: 'actuate',
            ti: 'XLink_1_0.ActuateType',
            t: 'a'
          }]
      }, {
        ln: 'ConditionalValueType',
        bti: '.AbstractConditionalType',
        ps: [{
            n: 'data',
            ti: '.ConditionalValueType.Data'
          }]
      }, {
        ln: 'ScopedNameType',
        ps: [{
            n: 'value',
            t: 'v'
          }, {
            n: 'codeSpace',
            an: {
              lp: 'codeSpace'
            },
            t: 'a'
          }]
      }, {
        ln: 'DataArrayType',
        bti: '.AbstractDataArrayType',
        ps: [{
            n: 'elementType',
            ti: '.DataComponentPropertyType'
          }, {
            n: 'encoding',
            ti: '.BlockEncodingPropertyType'
          }, {
            n: 'values',
            ti: '.DataValuePropertyType'
          }]
      }, {
        t: 'enum',
        ln: 'ByteOrder',
        vs: ['bigEndian', 'littleEndian']
      }, {
        t: 'enum',
        ln: 'ByteEncoding',
        vs: ['base64', 'raw', 'hex']
      }],
    eis: [{
        en: 'BinaryBlock',
        ti: '.BinaryBlock'
      }, {
        en: 'interval',
        ti: {
          t: 'l',
          bti: 'Double'
        },
        sc: '.AllowedValues'
      }, {
        en: 'AllowedValues',
        ti: '.AllowedValues'
      }, {
        en: 'Category',
        ti: '.Category'
      }, {
        en: 'ConditionalValue',
        ti: '.ConditionalValueType',
        sh: 'AbstractDataRecord'
      }, {
        en: 'TimeIntervalGrid',
        ti: '.TimeIntervalGridType',
        sh: 'TimeGrid'
      }, {
        en: 'QuantityRange',
        ti: '.QuantityRange'
      }, {
        en: 'DataArray',
        ti: '.DataArrayType',
        sh: 'AbstractDataArray'
      }, {
        en: 'Curve',
        ti: '.CurveType',
        sh: 'AbstractDataArray'
      }, {
        en: 'AllowedTimes',
        ti: '.AllowedTimes'
      }, {
        en: 'XMLBlock',
        ti: '.XMLBlockType'
      }, {
        en: 'GeoLocationArea',
        ti: '.GeoLocationArea',
        sh: 'AbstractDataRecord'
      }, {
        en: 'Item',
        ti: 'AnyType'
      }, {
        en: 'StandardFormat',
        ti: '.StandardFormat'
      }, {
        en: 'TextBlock',
        ti: '.TextBlock'
      }, {
        en: 'CountRange',
        ti: '.CountRange'
      }, {
        en: 'SimpleDataRecord',
        ti: '.SimpleDataRecordType',
        sh: 'AbstractDataRecord'
      }, {
        en: 'AllowedTokens',
        ti: '.AllowedTokens'
      }, {
        en: 'AbstractDataArray',
        ti: '.AbstractDataArrayType'
      }, {
        en: 'ConstrainedPhenomenon',
        ti: '.ConstrainedPhenomenonType',
        sh: 'Phenomenon'
      }, {
        en: 'ObservableProperty',
        ti: '.ObservableProperty'
      }, {
        en: 'Array',
        ti: '.ArrayType'
      }, {
        en: 'TimeGrid',
        ti: '.TimeGridType',
        sh: {
          lp: '_TimeComplex',
          ns: 'http:\/\/www.opengis.net\/gml'
        }
      }, {
        en: 'MultiplexedStreamFormat',
        ti: '.MultiplexedStreamFormatType'
      }, {
        en: 'ConditionalData',
        ti: '.ConditionalDataType',
        sh: 'AbstractDataRecord'
      }, {
        en: 'Time',
        ti: '.Time'
      }, {
        en: 'Count',
        ti: '.Count'
      }, {
        en: 'Text',
        ti: '.Text'
      }, {
        en: 'Boolean',
        ti: '.Boolean'
      }, {
        en: 'DataStreamDefinition',
        ti: '.DataStreamDefinitionType'
      }, {
        en: 'AbstractDataRecord',
        ti: '.AbstractDataRecordType'
      }, {
        en: 'Record',
        ti: '.RecordType'
      }, {
        en: 'valueList',
        ti: {
          t: 'l'
        },
        sc: '.AllowedTimes'
      }, {
        en: 'CompoundPhenomenon',
        ti: '.CompoundPhenomenonType',
        sh: 'Phenomenon'
      }, {
        en: 'DataRecord',
        ti: '.DataRecordType',
        sh: 'AbstractDataRecord'
      }, {
        en: 'valueList',
        ti: {
          t: 'l'
        },
        sc: '.AllowedTokens'
      }, {
        en: 'Vector',
        ti: '.VectorType',
        sh: 'AbstractDataRecord'
      }, {
        en: 'CompositePhenomenon',
        ti: '.CompositePhenomenonType',
        sh: 'CompoundPhenomenon'
      }, {
        en: 'NormalizedCurve',
        ti: '.NormalizedCurveType',
        sh: 'AbstractDataRecord'
      }, {
        en: 'SquareMatrix',
        ti: '.SquareMatrixType',
        sh: 'AbstractDataArray'
      }, {
        en: 'Phenomenon',
        ti: '.PhenomenonType',
        sh: {
          lp: 'Definition',
          ns: 'http:\/\/www.opengis.net\/gml'
        }
      }, {
        en: 'PhenomenonSeries',
        ti: '.PhenomenonSeriesType',
        sh: 'CompoundPhenomenon'
      }, {
        en: 'TimeInstantGrid',
        ti: '.TimeInstantGridType',
        sh: 'TimeGrid'
      }, {
        en: 'TimeGeometricComplex',
        ti: '.TimeGeometricComplexType',
        sh: {
          lp: '_TimeComplex',
          ns: 'http:\/\/www.opengis.net\/gml'
        }
      }, {
        en: 'Interval',
        ti: '.IntervalType'
      }, {
        en: 'valueList',
        ti: {
          t: 'l',
          bti: 'Double'
        },
        sc: '.AllowedValues'
      }, {
        en: 'TimeAggregate',
        ti: '.TimeAggregateType',
        sh: {
          lp: '_TimeObject',
          ns: 'http:\/\/www.opengis.net\/gml'
        }
      }, {
        en: 'Envelope',
        ti: '.EnvelopeType',
        sh: 'AbstractDataRecord'
      }, {
        en: 'Position',
        ti: '.PositionType',
        sh: 'AbstractDataRecord'
      }, {
        en: 'TimeRange',
        ti: '.TimeRange'
      }, {
        en: 'interval',
        ti: {
          t: 'l'
        },
        sc: '.AllowedTimes'
      }, {
        en: 'Quantity',
        ti: '.Quantity'
      }, {
        en: 'DataBlockDefinition',
        ti: '.DataBlockDefinitionType'
      }]
  };
  return {
    SWE_1_0_1: SWE_1_0_1
  };
};
if (typeof define === 'function' && define.amd) {
  define([], SWE_1_0_1_Module_Factory);
}
else {
  var SWE_1_0_1_Module = SWE_1_0_1_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.SWE_1_0_1 = SWE_1_0_1_Module.SWE_1_0_1;
  }
  else {
    var SWE_1_0_1 = SWE_1_0_1_Module.SWE_1_0_1;
  }
}