var WFS_1_0_0_Module_Factory = function () {
  var WFS_1_0_0 = {
    name: 'WFS_1_0_0',
    defaultElementNamespaceURI: 'http:\/\/www.opengis.net\/wfs',
    typeInfos: [{
        type: 'classInfo',
        localName: 'DescribeFeatureTypeType',
        propertyInfos: [{
            type: 'element',
            name: 'typeName',
            collection: true,
            elementName: 'TypeName',
            typeInfo: 'String'
          }, {
            name: 'version',
            typeInfo: 'String',
            attributeName: 'version',
            type: 'attribute'
          }, {
            name: 'service',
            typeInfo: 'String',
            attributeName: 'service',
            type: 'attribute'
          }, {
            name: 'outputFormat',
            typeInfo: 'String',
            attributeName: 'outputFormat',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'DeleteElementType',
        propertyInfos: [{
            type: 'element',
            name: 'filter',
            elementName: {
              localPart: 'Filter',
              namespaceURI: 'http:\/\/www.opengis.net\/ogc'
            },
            typeInfo: 'Filter_1_0_0.FilterType'
          }, {
            name: 'handle',
            typeInfo: 'String',
            attributeName: 'handle',
            type: 'attribute'
          }, {
            name: 'typeName',
            typeInfo: 'String',
            attributeName: 'typeName',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'GetFeatureType',
        propertyInfos: [{
            type: 'element',
            name: 'query',
            collection: true,
            elementName: 'Query',
            typeInfo: 'WFS_1_0_0.QueryType'
          }, {
            name: 'version',
            typeInfo: 'String',
            attributeName: 'version',
            type: 'attribute'
          }, {
            name: 'service',
            typeInfo: 'String',
            attributeName: 'service',
            type: 'attribute'
          }, {
            name: 'handle',
            typeInfo: 'String',
            attributeName: 'handle',
            type: 'attribute'
          }, {
            name: 'outputFormat',
            typeInfo: 'String',
            attributeName: 'outputFormat',
            type: 'attribute'
          }, {
            name: 'maxFeatures',
            typeInfo: 'Integer',
            attributeName: 'maxFeatures',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'EmptyType',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'QueryType',
        propertyInfos: [{
            type: 'element',
            name: 'propertyName',
            collection: true,
            elementName: {
              localPart: 'PropertyName',
              namespaceURI: 'http:\/\/www.opengis.net\/ogc'
            },
            typeInfo: 'Filter_1_0_0.PropertyNameType'
          }, {
            type: 'element',
            name: 'filter',
            elementName: {
              localPart: 'Filter',
              namespaceURI: 'http:\/\/www.opengis.net\/ogc'
            },
            typeInfo: 'Filter_1_0_0.FilterType'
          }, {
            name: 'handle',
            typeInfo: 'String',
            attributeName: 'handle',
            type: 'attribute'
          }, {
            name: 'typeName',
            typeInfo: 'String',
            attributeName: 'typeName',
            type: 'attribute'
          }, {
            name: 'featureVersion',
            typeInfo: 'String',
            attributeName: 'featureVersion',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'GetFeatureWithLockType',
        propertyInfos: [{
            type: 'element',
            name: 'query',
            collection: true,
            elementName: 'Query',
            typeInfo: 'WFS_1_0_0.QueryType'
          }, {
            name: 'version',
            typeInfo: 'String',
            attributeName: 'version',
            type: 'attribute'
          }, {
            name: 'service',
            typeInfo: 'String',
            attributeName: 'service',
            type: 'attribute'
          }, {
            name: 'handle',
            typeInfo: 'String',
            attributeName: 'handle',
            type: 'attribute'
          }, {
            name: 'expiry',
            typeInfo: 'Integer',
            attributeName: 'expiry',
            type: 'attribute'
          }, {
            name: 'outputFormat',
            typeInfo: 'String',
            attributeName: 'outputFormat',
            type: 'attribute'
          }, {
            name: 'maxFeatures',
            typeInfo: 'Integer',
            attributeName: 'maxFeatures',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'LockFeatureType',
        propertyInfos: [{
            type: 'element',
            name: 'lock',
            collection: true,
            elementName: 'Lock',
            typeInfo: 'WFS_1_0_0.LockType'
          }, {
            name: 'version',
            typeInfo: 'String',
            attributeName: 'version',
            type: 'attribute'
          }, {
            name: 'service',
            typeInfo: 'String',
            attributeName: 'service',
            type: 'attribute'
          }, {
            name: 'expiry',
            typeInfo: 'Integer',
            attributeName: 'expiry',
            type: 'attribute'
          }, {
            name: 'lockAction',
            typeInfo: 'String',
            attributeName: 'lockAction',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'InsertElementType',
        propertyInfos: [{
            name: 'feature',
            collection: true,
            elementName: {
              localPart: '_Feature',
              namespaceURI: 'http:\/\/www.opengis.net\/gml'
            },
            typeInfo: 'GML_2_1_2.AbstractFeatureType',
            type: 'elementRef'
          }, {
            name: 'handle',
            typeInfo: 'String',
            attributeName: 'handle',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'UpdateElementType',
        propertyInfos: [{
            type: 'element',
            name: 'property',
            collection: true,
            elementName: 'Property',
            typeInfo: 'WFS_1_0_0.PropertyType'
          }, {
            type: 'element',
            name: 'filter',
            elementName: {
              localPart: 'Filter',
              namespaceURI: 'http:\/\/www.opengis.net\/ogc'
            },
            typeInfo: 'Filter_1_0_0.FilterType'
          }, {
            name: 'handle',
            typeInfo: 'String',
            attributeName: 'handle',
            type: 'attribute'
          }, {
            name: 'typeName',
            typeInfo: 'String',
            attributeName: 'typeName',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'NativeType',
        propertyInfos: [{
            name: 'vendorId',
            typeInfo: 'String',
            attributeName: 'vendorId',
            type: 'attribute'
          }, {
            name: 'safeToIgnore',
            typeInfo: 'Boolean',
            attributeName: 'safeToIgnore',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'WFSLockFeatureResponseType',
        propertyInfos: [{
            type: 'element',
            name: 'lockId',
            elementName: 'LockId',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'featuresLocked',
            elementName: 'FeaturesLocked',
            typeInfo: 'WFS_1_0_0.FeaturesLockedType'
          }, {
            type: 'element',
            name: 'featuresNotLocked',
            elementName: 'FeaturesNotLocked',
            typeInfo: 'WFS_1_0_0.FeaturesNotLockedType'
          }]
      }, {
        type: 'classInfo',
        localName: 'TransactionType',
        propertyInfos: [{
            type: 'element',
            name: 'lockId',
            elementName: 'LockId',
            typeInfo: 'String'
          }, {
            name: 'insertOrUpdateOrDelete',
            collection: true,
            elementTypeInfos: [{
                elementName: 'Insert',
                typeInfo: 'WFS_1_0_0.InsertElementType'
              }, {
                elementName: 'Update',
                typeInfo: 'WFS_1_0_0.UpdateElementType'
              }, {
                elementName: 'Delete',
                typeInfo: 'WFS_1_0_0.DeleteElementType'
              }, {
                elementName: 'Native',
                typeInfo: 'WFS_1_0_0.NativeType'
              }],
            type: 'elements'
          }, {
            name: 'version',
            typeInfo: 'String',
            attributeName: 'version',
            type: 'attribute'
          }, {
            name: 'service',
            typeInfo: 'String',
            attributeName: 'service',
            type: 'attribute'
          }, {
            name: 'handle',
            typeInfo: 'String',
            attributeName: 'handle',
            type: 'attribute'
          }, {
            name: 'releaseAction',
            typeInfo: 'String',
            attributeName: 'releaseAction',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'FeatureCollectionType',
        baseTypeInfo: 'GML_2_1_2.AbstractFeatureCollectionType',
        propertyInfos: [{
            name: 'lockId',
            typeInfo: 'String',
            attributeName: 'lockId',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'GetCapabilitiesType',
        propertyInfos: [{
            name: 'version',
            typeInfo: 'String',
            attributeName: 'version',
            type: 'attribute'
          }, {
            name: 'service',
            typeInfo: 'String',
            attributeName: 'service',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'WFSTransactionResponseType',
        propertyInfos: [{
            type: 'element',
            name: 'insertResult',
            collection: true,
            elementName: 'InsertResult',
            typeInfo: 'WFS_1_0_0.InsertResultType'
          }, {
            type: 'element',
            name: 'transactionResult',
            elementName: 'TransactionResult',
            typeInfo: 'WFS_1_0_0.TransactionResultType'
          }, {
            name: 'version',
            typeInfo: 'String',
            attributeName: 'version',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'PropertyType',
        propertyInfos: [{
            type: 'element',
            name: 'name',
            elementName: 'Name',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'value',
            elementName: 'Value',
            typeInfo: 'AnyType'
          }]
      }, {
        type: 'classInfo',
        localName: 'FeaturesNotLockedType',
        propertyInfos: [{
            type: 'element',
            name: 'featureId',
            collection: true,
            elementName: {
              localPart: 'FeatureId',
              namespaceURI: 'http:\/\/www.opengis.net\/ogc'
            },
            typeInfo: 'Filter_1_0_0.FeatureIdType'
          }]
      }, {
        type: 'classInfo',
        localName: 'TransactionResultType',
        propertyInfos: [{
            type: 'element',
            name: 'status',
            elementName: 'Status',
            typeInfo: 'WFS_1_0_0.StatusType'
          }, {
            type: 'element',
            name: 'locator',
            elementName: 'Locator',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'message',
            elementName: 'Message',
            typeInfo: 'String'
          }, {
            name: 'handle',
            typeInfo: 'String',
            attributeName: 'handle',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'FeaturesLockedType',
        propertyInfos: [{
            type: 'element',
            name: 'featureId',
            collection: true,
            elementName: {
              localPart: 'FeatureId',
              namespaceURI: 'http:\/\/www.opengis.net\/ogc'
            },
            typeInfo: 'Filter_1_0_0.FeatureIdType'
          }]
      }, {
        type: 'classInfo',
        localName: 'LockType',
        propertyInfos: [{
            type: 'element',
            name: 'filter',
            elementName: {
              localPart: 'Filter',
              namespaceURI: 'http:\/\/www.opengis.net\/ogc'
            },
            typeInfo: 'Filter_1_0_0.FilterType'
          }, {
            name: 'handle',
            typeInfo: 'String',
            attributeName: 'handle',
            type: 'attribute'
          }, {
            name: 'typeName',
            typeInfo: 'String',
            attributeName: 'typeName',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'StatusType',
        propertyInfos: [{
            type: 'element',
            name: 'success',
            elementName: 'SUCCESS',
            typeInfo: 'WFS_1_0_0.EmptyType'
          }, {
            type: 'element',
            name: 'failed',
            elementName: 'FAILED',
            typeInfo: 'WFS_1_0_0.EmptyType'
          }, {
            type: 'element',
            name: 'partial',
            elementName: 'PARTIAL',
            typeInfo: 'WFS_1_0_0.EmptyType'
          }]
      }, {
        type: 'classInfo',
        localName: 'InsertResultType',
        propertyInfos: [{
            type: 'element',
            name: 'featureId',
            collection: true,
            elementName: {
              localPart: 'FeatureId',
              namespaceURI: 'http:\/\/www.opengis.net\/ogc'
            },
            typeInfo: 'Filter_1_0_0.FeatureIdType'
          }, {
            name: 'handle',
            typeInfo: 'String',
            attributeName: 'handle',
            type: 'attribute'
          }]
      }, {
        type: 'enumInfo',
        localName: 'AllSomeType',
        baseTypeInfo: 'String',
        values: ['ALL', 'SOME']
      }],
    elementInfos: [{
        elementName: 'GetFeatureWithLock',
        typeInfo: 'WFS_1_0_0.GetFeatureWithLockType'
      }, {
        elementName: 'SUCCESS',
        typeInfo: 'WFS_1_0_0.EmptyType'
      }, {
        elementName: 'GetFeature',
        typeInfo: 'WFS_1_0_0.GetFeatureType'
      }, {
        elementName: 'PARTIAL',
        typeInfo: 'WFS_1_0_0.EmptyType'
      }, {
        elementName: 'FeatureCollection',
        typeInfo: 'WFS_1_0_0.FeatureCollectionType',
        substitutionHead: {
          localPart: '_FeatureCollection',
          namespaceURI: 'http:\/\/www.opengis.net\/gml'
        }
      }, {
        elementName: 'Transaction',
        typeInfo: 'WFS_1_0_0.TransactionType'
      }, {
        elementName: 'WFS_LockFeatureResponse',
        typeInfo: 'WFS_1_0_0.WFSLockFeatureResponseType'
      }, {
        elementName: 'LockId',
        typeInfo: 'String'
      }, {
        elementName: 'LockFeature',
        typeInfo: 'WFS_1_0_0.LockFeatureType'
      }, {
        elementName: 'Query',
        typeInfo: 'WFS_1_0_0.QueryType'
      }, {
        elementName: 'DescribeFeatureType',
        typeInfo: 'WFS_1_0_0.DescribeFeatureTypeType'
      }, {
        elementName: 'Delete',
        typeInfo: 'WFS_1_0_0.DeleteElementType'
      }, {
        elementName: 'Insert',
        typeInfo: 'WFS_1_0_0.InsertElementType'
      }, {
        elementName: 'Update',
        typeInfo: 'WFS_1_0_0.UpdateElementType'
      }, {
        elementName: 'GetCapabilities',
        typeInfo: 'WFS_1_0_0.GetCapabilitiesType'
      }, {
        elementName: 'FAILED',
        typeInfo: 'WFS_1_0_0.EmptyType'
      }, {
        elementName: 'Native',
        typeInfo: 'WFS_1_0_0.NativeType'
      }, {
        elementName: 'Property',
        typeInfo: 'WFS_1_0_0.PropertyType'
      }, {
        elementName: 'WFS_TransactionResponse',
        typeInfo: 'WFS_1_0_0.WFSTransactionResponseType'
      }]
  };
  return {
    WFS_1_0_0: WFS_1_0_0
  };
};
if (typeof define === 'function' && define.amd) {
  define([], WFS_1_0_0_Module_Factory);
}
else {
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.WFS_1_0_0 = WFS_1_0_0_Module_Factory().WFS_1_0_0;
  }
  else {
    var WFS_1_0_0 = WFS_1_0_0_Module_Factory().WFS_1_0_0;
  }
}