var WMS_1_0_0_Module_Factory = function () {
  var WMS_1_0_0 = {
    name: 'WMS_1_0_0',
    typeInfos: [{
        type: 'classInfo',
        localName: 'DCPType',
        propertyInfos: [{
            type: 'element',
            name: 'http',
            elementName: 'HTTP',
            typeInfo: 'WMS_1_0_0.HTTP'
          }]
      }, {
        type: 'classInfo',
        localName: 'HTTP',
        propertyInfos: [{
            name: 'getOrPost',
            collection: true,
            elementTypeInfos: [{
                elementName: 'Get',
                typeInfo: 'WMS_1_0_0.Get'
              }, {
                elementName: 'Post',
                typeInfo: 'WMS_1_0_0.Post'
              }],
            type: 'elements'
          }]
      }, {
        type: 'classInfo',
        localName: 'WMTMSCapabilities',
        propertyInfos: [{
            name: 'version',
            typeInfo: 'String',
            attributeName: 'version',
            type: 'attribute'
          }, {
            name: 'updateSequence',
            typeInfo: 'String',
            attributeName: 'updateSequence',
            type: 'attribute'
          }, {
            type: 'element',
            name: 'service',
            elementName: 'Service',
            typeInfo: 'WMS_1_0_0.Service'
          }, {
            type: 'element',
            name: 'capability',
            elementName: 'Capability',
            typeInfo: 'WMS_1_0_0.Capability'
          }]
      }, {
        type: 'classInfo',
        localName: 'Service',
        propertyInfos: [{
            type: 'element',
            name: 'name',
            elementName: 'Name',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'title',
            elementName: 'Title',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: '_abstract',
            elementName: 'Abstract',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'keywords',
            elementName: 'Keywords',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'fees',
            elementName: 'Fees',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'accessConstraints',
            elementName: 'AccessConstraints',
            typeInfo: 'String'
          }]
      }, {
        type: 'classInfo',
        localName: 'Capability',
        propertyInfos: [{
            type: 'element',
            name: 'request',
            elementName: 'Request',
            typeInfo: 'WMS_1_0_0.Request'
          }, {
            type: 'element',
            name: 'exception',
            elementName: 'Exception',
            typeInfo: 'WMS_1_0_0.Exception'
          }, {
            type: 'element',
            name: 'vendorSpecificCapabilities',
            elementName: 'VendorSpecificCapabilities',
            typeInfo: 'WMS_1_0_0.VendorSpecificCapabilities'
          }, {
            type: 'element',
            name: 'layer',
            elementName: 'Layer',
            typeInfo: 'WMS_1_0_0.Layer'
          }]
      }, {
        type: 'classInfo',
        localName: 'SVG',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'WBMP',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'WebCGM',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'FeatureInfo',
        propertyInfos: [{
            type: 'element',
            name: 'format',
            elementName: 'Format',
            typeInfo: 'WMS_1_0_0.Format'
          }, {
            type: 'element',
            name: 'dcpType',
            collection: true,
            elementName: 'DCPType',
            typeInfo: 'WMS_1_0_0.DCPType'
          }]
      }, {
        type: 'classInfo',
        localName: 'Format',
        propertyInfos: [{
            name: 'gifOrJPEGOrPNGOrWebCGMOrSVGOrGML1OrGML2OrGML3OrWBMPOrWMSXMLOrMIMEOrINIMAGEOrTIFFOrGeoTIFFOrPPMOrBLANK',
            collection: true,
            elementTypeInfos: [{
                elementName: 'GIF',
                typeInfo: 'WMS_1_0_0.GIF'
              }, {
                elementName: 'JPEG',
                typeInfo: 'WMS_1_0_0.JPEG'
              }, {
                elementName: 'PNG',
                typeInfo: 'WMS_1_0_0.PNG'
              }, {
                elementName: 'WebCGM',
                typeInfo: 'WMS_1_0_0.WebCGM'
              }, {
                elementName: 'SVG',
                typeInfo: 'WMS_1_0_0.SVG'
              }, {
                elementName: 'GML.1',
                typeInfo: 'WMS_1_0_0.GML1'
              }, {
                elementName: 'GML.2',
                typeInfo: 'WMS_1_0_0.GML2'
              }, {
                elementName: 'GML.3',
                typeInfo: 'WMS_1_0_0.GML3'
              }, {
                elementName: 'WBMP',
                typeInfo: 'WMS_1_0_0.WBMP'
              }, {
                elementName: 'WMS_XML',
                typeInfo: 'WMS_1_0_0.WMSXML'
              }, {
                elementName: 'MIME',
                typeInfo: 'WMS_1_0_0.MIME'
              }, {
                elementName: 'INIMAGE',
                typeInfo: 'WMS_1_0_0.INIMAGE'
              }, {
                elementName: 'TIFF',
                typeInfo: 'WMS_1_0_0.TIFF'
              }, {
                elementName: 'GeoTIFF',
                typeInfo: 'WMS_1_0_0.GeoTIFF'
              }, {
                elementName: 'PPM',
                typeInfo: 'WMS_1_0_0.PPM'
              }, {
                elementName: 'BLANK',
                typeInfo: 'WMS_1_0_0.BLANK'
              }],
            type: 'elements'
          }]
      }, {
        type: 'classInfo',
        localName: 'PNG',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'JPEG',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'PPM',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'MIME',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'LatLonBoundingBox',
        propertyInfos: [{
            name: 'minx',
            typeInfo: 'String',
            attributeName: 'minx',
            type: 'attribute'
          }, {
            name: 'miny',
            typeInfo: 'String',
            attributeName: 'miny',
            type: 'attribute'
          }, {
            name: 'maxx',
            typeInfo: 'String',
            attributeName: 'maxx',
            type: 'attribute'
          }, {
            name: 'maxy',
            typeInfo: 'String',
            attributeName: 'maxy',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'GeoTIFF',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'TIFF',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'GIF',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'GML1',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'GML2',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'GML3',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'WMSXML',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'INIMAGE',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'BLANK',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'BoundingBox',
        propertyInfos: [{
            name: 'srs',
            typeInfo: 'String',
            attributeName: 'SRS',
            type: 'attribute'
          }, {
            name: 'minx',
            typeInfo: 'String',
            attributeName: 'minx',
            type: 'attribute'
          }, {
            name: 'miny',
            typeInfo: 'String',
            attributeName: 'miny',
            type: 'attribute'
          }, {
            name: 'maxx',
            typeInfo: 'String',
            attributeName: 'maxx',
            type: 'attribute'
          }, {
            name: 'maxy',
            typeInfo: 'String',
            attributeName: 'maxy',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'Style',
        propertyInfos: [{
            type: 'element',
            name: 'name',
            elementName: 'Name',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'title',
            elementName: 'Title',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: '_abstract',
            elementName: 'Abstract',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'styleURL',
            elementName: 'StyleURL',
            typeInfo: 'String'
          }]
      }, {
        type: 'classInfo',
        localName: 'Request',
        propertyInfos: [{
            name: 'mapOrCapabilitiesOrFeatureInfo',
            collection: true,
            elementTypeInfos: [{
                elementName: 'Map',
                typeInfo: 'WMS_1_0_0.Map'
              }, {
                elementName: 'Capabilities',
                typeInfo: 'WMS_1_0_0.Capabilities'
              }, {
                elementName: 'FeatureInfo',
                typeInfo: 'WMS_1_0_0.FeatureInfo'
              }],
            type: 'elements'
          }]
      }, {
        type: 'classInfo',
        localName: 'Exception',
        propertyInfos: [{
            type: 'element',
            name: 'format',
            elementName: 'Format',
            typeInfo: 'WMS_1_0_0.Format'
          }]
      }, {
        type: 'classInfo',
        localName: 'VendorSpecificCapabilities',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'Layer',
        propertyInfos: [{
            name: 'queryable',
            typeInfo: 'String',
            attributeName: 'queryable',
            type: 'attribute'
          }, {
            type: 'element',
            name: 'name',
            elementName: 'Name',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'title',
            elementName: 'Title',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: '_abstract',
            elementName: 'Abstract',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'keywords',
            elementName: 'Keywords',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'srs',
            elementName: 'SRS',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'latLonBoundingBox',
            elementName: 'LatLonBoundingBox',
            typeInfo: 'WMS_1_0_0.LatLonBoundingBox'
          }, {
            type: 'element',
            name: 'boundingBox',
            collection: true,
            elementName: 'BoundingBox',
            typeInfo: 'WMS_1_0_0.BoundingBox'
          }, {
            type: 'element',
            name: 'dataURL',
            elementName: 'DataURL',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'style',
            collection: true,
            elementName: 'Style',
            typeInfo: 'WMS_1_0_0.Style'
          }, {
            type: 'element',
            name: 'scaleHint',
            elementName: 'ScaleHint',
            typeInfo: 'WMS_1_0_0.ScaleHint'
          }, {
            type: 'element',
            name: 'layer',
            collection: true,
            elementName: 'Layer',
            typeInfo: 'WMS_1_0_0.Layer'
          }]
      }, {
        type: 'classInfo',
        localName: 'Post',
        propertyInfos: [{
            name: 'onlineResource',
            typeInfo: 'String',
            attributeName: 'onlineResource',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'Map',
        propertyInfos: [{
            type: 'element',
            name: 'format',
            elementName: 'Format',
            typeInfo: 'WMS_1_0_0.Format'
          }, {
            type: 'element',
            name: 'dcpType',
            collection: true,
            elementName: 'DCPType',
            typeInfo: 'WMS_1_0_0.DCPType'
          }]
      }, {
        type: 'classInfo',
        localName: 'Capabilities',
        propertyInfos: [{
            type: 'element',
            name: 'format',
            elementName: 'Format',
            typeInfo: 'WMS_1_0_0.Format'
          }, {
            type: 'element',
            name: 'dcpType',
            collection: true,
            elementName: 'DCPType',
            typeInfo: 'WMS_1_0_0.DCPType'
          }]
      }, {
        type: 'classInfo',
        localName: 'Get',
        propertyInfos: [{
            name: 'onlineResource',
            typeInfo: 'String',
            attributeName: 'onlineResource',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'ScaleHint',
        propertyInfos: [{
            name: 'min',
            typeInfo: 'String',
            attributeName: 'min',
            type: 'attribute'
          }, {
            name: 'max',
            typeInfo: 'String',
            attributeName: 'max',
            type: 'attribute'
          }]
      }],
    elementInfos: [{
        elementName: 'DCPType',
        typeInfo: 'WMS_1_0_0.DCPType'
      }, {
        elementName: 'HTTP',
        typeInfo: 'WMS_1_0_0.HTTP'
      }, {
        elementName: 'WMT_MS_Capabilities',
        typeInfo: 'WMS_1_0_0.WMTMSCapabilities'
      }, {
        elementName: 'Service',
        typeInfo: 'WMS_1_0_0.Service'
      }, {
        elementName: 'Capability',
        typeInfo: 'WMS_1_0_0.Capability'
      }, {
        elementName: 'SVG',
        typeInfo: 'WMS_1_0_0.SVG'
      }, {
        elementName: 'WBMP',
        typeInfo: 'WMS_1_0_0.WBMP'
      }, {
        elementName: 'WebCGM',
        typeInfo: 'WMS_1_0_0.WebCGM'
      }, {
        elementName: 'FeatureInfo',
        typeInfo: 'WMS_1_0_0.FeatureInfo'
      }, {
        elementName: 'Format',
        typeInfo: 'WMS_1_0_0.Format'
      }, {
        elementName: 'PNG',
        typeInfo: 'WMS_1_0_0.PNG'
      }, {
        elementName: 'JPEG',
        typeInfo: 'WMS_1_0_0.JPEG'
      }, {
        elementName: 'PPM',
        typeInfo: 'WMS_1_0_0.PPM'
      }, {
        elementName: 'MIME',
        typeInfo: 'WMS_1_0_0.MIME'
      }, {
        elementName: 'LatLonBoundingBox',
        typeInfo: 'WMS_1_0_0.LatLonBoundingBox'
      }, {
        elementName: 'GeoTIFF',
        typeInfo: 'WMS_1_0_0.GeoTIFF'
      }, {
        elementName: 'TIFF',
        typeInfo: 'WMS_1_0_0.TIFF'
      }, {
        elementName: 'GIF',
        typeInfo: 'WMS_1_0_0.GIF'
      }, {
        elementName: 'GML.1',
        typeInfo: 'WMS_1_0_0.GML1'
      }, {
        elementName: 'GML.2',
        typeInfo: 'WMS_1_0_0.GML2'
      }, {
        elementName: 'GML.3',
        typeInfo: 'WMS_1_0_0.GML3'
      }, {
        elementName: 'WMS_XML',
        typeInfo: 'WMS_1_0_0.WMSXML'
      }, {
        elementName: 'INIMAGE',
        typeInfo: 'WMS_1_0_0.INIMAGE'
      }, {
        elementName: 'BLANK',
        typeInfo: 'WMS_1_0_0.BLANK'
      }, {
        elementName: 'BoundingBox',
        typeInfo: 'WMS_1_0_0.BoundingBox'
      }, {
        elementName: 'Style',
        typeInfo: 'WMS_1_0_0.Style'
      }, {
        elementName: 'Request',
        typeInfo: 'WMS_1_0_0.Request'
      }, {
        elementName: 'Exception',
        typeInfo: 'WMS_1_0_0.Exception'
      }, {
        elementName: 'VendorSpecificCapabilities',
        typeInfo: 'WMS_1_0_0.VendorSpecificCapabilities'
      }, {
        elementName: 'Layer',
        typeInfo: 'WMS_1_0_0.Layer'
      }, {
        elementName: 'Post',
        typeInfo: 'WMS_1_0_0.Post'
      }, {
        elementName: 'Map',
        typeInfo: 'WMS_1_0_0.Map'
      }, {
        elementName: 'Capabilities',
        typeInfo: 'WMS_1_0_0.Capabilities'
      }, {
        elementName: 'Get',
        typeInfo: 'WMS_1_0_0.Get'
      }, {
        elementName: 'ScaleHint',
        typeInfo: 'WMS_1_0_0.ScaleHint'
      }]
  };
  return {
    WMS_1_0_0: WMS_1_0_0
  };
};
if (typeof define === 'function' && define.amd) {
  define([], WMS_1_0_0_Module_Factory);
}
else {
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.WMS_1_0_0 = WMS_1_0_0_Module_Factory().WMS_1_0_0;
  }
  else {
    var WMS_1_0_0 = WMS_1_0_0_Module_Factory().WMS_1_0_0;
  }
}