var WMS_1_1_0_Module_Factory = function () {
  var WMS_1_1_0 = {
    name: 'WMS_1_1_0',
    typeInfos: [{
        type: 'classInfo',
        localName: 'DCPType',
        propertyInfos: [{
            type: 'element',
            name: 'http',
            elementName: 'HTTP',
            typeInfo: 'WMS_1_1_0.HTTP'
          }]
      }, {
        type: 'classInfo',
        localName: 'HTTP',
        propertyInfos: [{
            name: 'getOrPost',
            collection: true,
            elementTypeInfos: [{
                elementName: 'Get',
                typeInfo: 'WMS_1_1_0.Get'
              }, {
                elementName: 'Post',
                typeInfo: 'WMS_1_1_0.Post'
              }],
            type: 'elements'
          }]
      }, {
        type: 'classInfo',
        localName: 'FeatureListURL',
        propertyInfos: [{
            type: 'element',
            name: 'format',
            elementName: 'Format',
            typeInfo: 'WMS_1_1_0.Format'
          }, {
            type: 'element',
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: 'WMS_1_1_0.OnlineResource'
          }]
      }, {
        type: 'classInfo',
        localName: 'Format',
        propertyInfos: [{
            name: 'value',
            typeInfo: 'String',
            type: 'value'
          }]
      }, {
        type: 'classInfo',
        localName: 'OnlineResource',
        propertyInfos: [{
            name: 'xmlnsXlink',
            typeInfo: 'String',
            attributeName: 'xmlns:xlink',
            type: 'attribute'
          }, {
            name: 'xlinkType',
            typeInfo: 'String',
            attributeName: 'xlink:type',
            type: 'attribute'
          }, {
            name: 'xlinkHref',
            typeInfo: 'String',
            attributeName: 'xlink:href',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'WMTMSCapabilities',
        propertyInfos: [{
            name: 'version',
            typeInfo: 'String',
            attributeName: 'version',
            type: 'attribute'
          }, {
            name: 'updateSequence',
            typeInfo: 'String',
            attributeName: 'updateSequence',
            type: 'attribute'
          }, {
            type: 'element',
            name: 'service',
            elementName: 'Service',
            typeInfo: 'WMS_1_1_0.Service'
          }, {
            type: 'element',
            name: 'capability',
            elementName: 'Capability',
            typeInfo: 'WMS_1_1_0.Capability'
          }]
      }, {
        type: 'classInfo',
        localName: 'Service',
        propertyInfos: [{
            type: 'element',
            name: 'name',
            elementName: 'Name',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'title',
            elementName: 'Title',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: '_abstract',
            elementName: 'Abstract',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'keywordList',
            elementName: 'KeywordList',
            typeInfo: 'WMS_1_1_0.KeywordList'
          }, {
            type: 'element',
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: 'WMS_1_1_0.OnlineResource'
          }, {
            type: 'element',
            name: 'contactInformation',
            elementName: 'ContactInformation',
            typeInfo: 'WMS_1_1_0.ContactInformation'
          }, {
            type: 'element',
            name: 'fees',
            elementName: 'Fees',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'accessConstraints',
            elementName: 'AccessConstraints',
            typeInfo: 'String'
          }]
      }, {
        type: 'classInfo',
        localName: 'Capability',
        propertyInfos: [{
            type: 'element',
            name: 'request',
            elementName: 'Request',
            typeInfo: 'WMS_1_1_0.Request'
          }, {
            type: 'element',
            name: 'exception',
            elementName: 'Exception',
            typeInfo: 'WMS_1_1_0.Exception'
          }, {
            type: 'element',
            name: 'vendorSpecificCapabilities',
            elementName: 'VendorSpecificCapabilities',
            typeInfo: 'WMS_1_1_0.VendorSpecificCapabilities'
          }, {
            type: 'element',
            name: 'userDefinedSymbolization',
            elementName: 'UserDefinedSymbolization',
            typeInfo: 'WMS_1_1_0.UserDefinedSymbolization'
          }, {
            type: 'element',
            name: 'layer',
            elementName: 'Layer',
            typeInfo: 'WMS_1_1_0.Layer'
          }]
      }, {
        type: 'classInfo',
        localName: 'LogoURL',
        propertyInfos: [{
            name: 'width',
            typeInfo: 'String',
            attributeName: 'width',
            type: 'attribute'
          }, {
            name: 'height',
            typeInfo: 'String',
            attributeName: 'height',
            type: 'attribute'
          }, {
            type: 'element',
            name: 'format',
            elementName: 'Format',
            typeInfo: 'WMS_1_1_0.Format'
          }, {
            type: 'element',
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: 'WMS_1_1_0.OnlineResource'
          }]
      }, {
        type: 'classInfo',
        localName: 'ContactPersonPrimary',
        propertyInfos: [{
            type: 'element',
            name: 'contactPerson',
            elementName: 'ContactPerson',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'contactOrganization',
            elementName: 'ContactOrganization',
            typeInfo: 'String'
          }]
      }, {
        type: 'classInfo',
        localName: 'DescribeLayer',
        propertyInfos: [{
            type: 'element',
            name: 'format',
            collection: true,
            elementName: 'Format',
            typeInfo: 'WMS_1_1_0.Format'
          }, {
            type: 'element',
            name: 'dcpType',
            collection: true,
            elementName: 'DCPType',
            typeInfo: 'WMS_1_1_0.DCPType'
          }]
      }, {
        type: 'classInfo',
        localName: 'Identifier',
        propertyInfos: [{
            name: 'authority',
            typeInfo: 'String',
            attributeName: 'authority',
            type: 'attribute'
          }, {
            name: 'value',
            typeInfo: 'String',
            type: 'value'
          }]
      }, {
        type: 'classInfo',
        localName: 'UserDefinedSymbolization',
        propertyInfos: [{
            name: 'supportSLD',
            typeInfo: 'String',
            attributeName: 'SupportSLD',
            type: 'attribute'
          }, {
            name: 'userLayer',
            typeInfo: 'String',
            attributeName: 'UserLayer',
            type: 'attribute'
          }, {
            name: 'userStyle',
            typeInfo: 'String',
            attributeName: 'UserStyle',
            type: 'attribute'
          }, {
            name: 'remoteWFS',
            typeInfo: 'String',
            attributeName: 'RemoteWFS',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'ContactAddress',
        propertyInfos: [{
            type: 'element',
            name: 'addressType',
            elementName: 'AddressType',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'address',
            elementName: 'Address',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'city',
            elementName: 'City',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'stateOrProvince',
            elementName: 'StateOrProvince',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'postCode',
            elementName: 'PostCode',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'country',
            elementName: 'Country',
            typeInfo: 'String'
          }]
      }, {
        type: 'classInfo',
        localName: 'Request',
        propertyInfos: [{
            type: 'element',
            name: 'getCapabilities',
            elementName: 'GetCapabilities',
            typeInfo: 'WMS_1_1_0.GetCapabilities'
          }, {
            type: 'element',
            name: 'getMap',
            elementName: 'GetMap',
            typeInfo: 'WMS_1_1_0.GetMap'
          }, {
            type: 'element',
            name: 'getFeatureInfo',
            elementName: 'GetFeatureInfo',
            typeInfo: 'WMS_1_1_0.GetFeatureInfo'
          }, {
            type: 'element',
            name: 'describeLayer',
            elementName: 'DescribeLayer',
            typeInfo: 'WMS_1_1_0.DescribeLayer'
          }]
      }, {
        type: 'classInfo',
        localName: 'Exception',
        propertyInfos: [{
            type: 'element',
            name: 'format',
            collection: true,
            elementName: 'Format',
            typeInfo: 'WMS_1_1_0.Format'
          }]
      }, {
        type: 'classInfo',
        localName: 'VendorSpecificCapabilities',
        propertyInfos: []
      }, {
        type: 'classInfo',
        localName: 'Layer',
        propertyInfos: [{
            name: 'queryable',
            typeInfo: 'String',
            attributeName: 'queryable',
            type: 'attribute'
          }, {
            name: 'cascaded',
            typeInfo: 'String',
            attributeName: 'cascaded',
            type: 'attribute'
          }, {
            name: 'opaque',
            typeInfo: 'String',
            attributeName: 'opaque',
            type: 'attribute'
          }, {
            name: 'noSubsets',
            typeInfo: 'String',
            attributeName: 'noSubsets',
            type: 'attribute'
          }, {
            name: 'fixedWidth',
            typeInfo: 'String',
            attributeName: 'fixedWidth',
            type: 'attribute'
          }, {
            name: 'fixedHeight',
            typeInfo: 'String',
            attributeName: 'fixedHeight',
            type: 'attribute'
          }, {
            type: 'element',
            name: 'name',
            elementName: 'Name',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'title',
            elementName: 'Title',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: '_abstract',
            elementName: 'Abstract',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'keywordList',
            elementName: 'KeywordList',
            typeInfo: 'WMS_1_1_0.KeywordList'
          }, {
            type: 'element',
            name: 'srs',
            elementName: 'SRS',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'latLonBoundingBox',
            elementName: 'LatLonBoundingBox',
            typeInfo: 'WMS_1_1_0.LatLonBoundingBox'
          }, {
            type: 'element',
            name: 'boundingBox',
            collection: true,
            elementName: 'BoundingBox',
            typeInfo: 'WMS_1_1_0.BoundingBox'
          }, {
            type: 'element',
            name: 'dimension',
            collection: true,
            elementName: 'Dimension',
            typeInfo: 'WMS_1_1_0.Dimension'
          }, {
            type: 'element',
            name: 'extent',
            collection: true,
            elementName: 'Extent',
            typeInfo: 'WMS_1_1_0.Extent'
          }, {
            type: 'element',
            name: 'attribution',
            elementName: 'Attribution',
            typeInfo: 'WMS_1_1_0.Attribution'
          }, {
            type: 'element',
            name: 'authorityURL',
            collection: true,
            elementName: 'AuthorityURL',
            typeInfo: 'WMS_1_1_0.AuthorityURL'
          }, {
            type: 'element',
            name: 'identifier',
            collection: true,
            elementName: 'Identifier',
            typeInfo: 'WMS_1_1_0.Identifier'
          }, {
            type: 'element',
            name: 'metadataURL',
            collection: true,
            elementName: 'MetadataURL',
            typeInfo: 'WMS_1_1_0.MetadataURL'
          }, {
            type: 'element',
            name: 'dataURL',
            collection: true,
            elementName: 'DataURL',
            typeInfo: 'WMS_1_1_0.DataURL'
          }, {
            type: 'element',
            name: 'featureListURL',
            collection: true,
            elementName: 'FeatureListURL',
            typeInfo: 'WMS_1_1_0.FeatureListURL'
          }, {
            type: 'element',
            name: 'style',
            collection: true,
            elementName: 'Style',
            typeInfo: 'WMS_1_1_0.Style'
          }, {
            type: 'element',
            name: 'scaleHint',
            elementName: 'ScaleHint',
            typeInfo: 'WMS_1_1_0.ScaleHint'
          }, {
            type: 'element',
            name: 'layer',
            collection: true,
            elementName: 'Layer',
            typeInfo: 'WMS_1_1_0.Layer'
          }]
      }, {
        type: 'classInfo',
        localName: 'Get',
        propertyInfos: [{
            type: 'element',
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: 'WMS_1_1_0.OnlineResource'
          }]
      }, {
        type: 'classInfo',
        localName: 'Post',
        propertyInfos: [{
            type: 'element',
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: 'WMS_1_1_0.OnlineResource'
          }]
      }, {
        type: 'classInfo',
        localName: 'GetMap',
        propertyInfos: [{
            type: 'element',
            name: 'format',
            collection: true,
            elementName: 'Format',
            typeInfo: 'WMS_1_1_0.Format'
          }, {
            type: 'element',
            name: 'dcpType',
            collection: true,
            elementName: 'DCPType',
            typeInfo: 'WMS_1_1_0.DCPType'
          }]
      }, {
        type: 'classInfo',
        localName: 'ScaleHint',
        propertyInfos: [{
            name: 'min',
            typeInfo: 'String',
            attributeName: 'min',
            type: 'attribute'
          }, {
            name: 'max',
            typeInfo: 'String',
            attributeName: 'max',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'Attribution',
        propertyInfos: [{
            type: 'element',
            name: 'title',
            elementName: 'Title',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: 'WMS_1_1_0.OnlineResource'
          }, {
            type: 'element',
            name: 'logoURL',
            elementName: 'LogoURL',
            typeInfo: 'WMS_1_1_0.LogoURL'
          }]
      }, {
        type: 'classInfo',
        localName: 'GetFeatureInfo',
        propertyInfos: [{
            type: 'element',
            name: 'format',
            collection: true,
            elementName: 'Format',
            typeInfo: 'WMS_1_1_0.Format'
          }, {
            type: 'element',
            name: 'dcpType',
            collection: true,
            elementName: 'DCPType',
            typeInfo: 'WMS_1_1_0.DCPType'
          }]
      }, {
        type: 'classInfo',
        localName: 'ServiceException',
        propertyInfos: [{
            name: 'code',
            typeInfo: 'String',
            attributeName: 'code',
            type: 'attribute'
          }, {
            name: 'value',
            typeInfo: 'String',
            type: 'value'
          }]
      }, {
        type: 'classInfo',
        localName: 'MetadataURL',
        propertyInfos: [{
            name: 'type',
            typeInfo: 'String',
            attributeName: 'type',
            type: 'attribute'
          }, {
            type: 'element',
            name: 'format',
            elementName: 'Format',
            typeInfo: 'WMS_1_1_0.Format'
          }, {
            type: 'element',
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: 'WMS_1_1_0.OnlineResource'
          }]
      }, {
        type: 'classInfo',
        localName: 'Extent',
        propertyInfos: [{
            name: 'name',
            typeInfo: 'String',
            attributeName: 'name',
            type: 'attribute'
          }, {
            name: '_default',
            typeInfo: 'String',
            attributeName: 'default',
            type: 'attribute'
          }, {
            name: 'value',
            typeInfo: 'String',
            type: 'value'
          }]
      }, {
        type: 'classInfo',
        localName: 'LatLonBoundingBox',
        propertyInfos: [{
            name: 'minx',
            typeInfo: 'String',
            attributeName: 'minx',
            type: 'attribute'
          }, {
            name: 'miny',
            typeInfo: 'String',
            attributeName: 'miny',
            type: 'attribute'
          }, {
            name: 'maxx',
            typeInfo: 'String',
            attributeName: 'maxx',
            type: 'attribute'
          }, {
            name: 'maxy',
            typeInfo: 'String',
            attributeName: 'maxy',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'GetCapabilities',
        propertyInfos: [{
            type: 'element',
            name: 'format',
            collection: true,
            elementName: 'Format',
            typeInfo: 'WMS_1_1_0.Format'
          }, {
            type: 'element',
            name: 'dcpType',
            collection: true,
            elementName: 'DCPType',
            typeInfo: 'WMS_1_1_0.DCPType'
          }]
      }, {
        type: 'classInfo',
        localName: 'BoundingBox',
        propertyInfos: [{
            name: 'srs',
            typeInfo: 'String',
            attributeName: 'SRS',
            type: 'attribute'
          }, {
            name: 'minx',
            typeInfo: 'String',
            attributeName: 'minx',
            type: 'attribute'
          }, {
            name: 'miny',
            typeInfo: 'String',
            attributeName: 'miny',
            type: 'attribute'
          }, {
            name: 'maxx',
            typeInfo: 'String',
            attributeName: 'maxx',
            type: 'attribute'
          }, {
            name: 'maxy',
            typeInfo: 'String',
            attributeName: 'maxy',
            type: 'attribute'
          }, {
            name: 'resx',
            typeInfo: 'String',
            attributeName: 'resx',
            type: 'attribute'
          }, {
            name: 'resy',
            typeInfo: 'String',
            attributeName: 'resy',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'Style',
        propertyInfos: [{
            type: 'element',
            name: 'name',
            elementName: 'Name',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'title',
            elementName: 'Title',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: '_abstract',
            elementName: 'Abstract',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'legendURL',
            collection: true,
            elementName: 'LegendURL',
            typeInfo: 'WMS_1_1_0.LegendURL'
          }, {
            type: 'element',
            name: 'styleSheetURL',
            elementName: 'StyleSheetURL',
            typeInfo: 'WMS_1_1_0.StyleSheetURL'
          }, {
            type: 'element',
            name: 'styleURL',
            elementName: 'StyleURL',
            typeInfo: 'WMS_1_1_0.StyleURL'
          }]
      }, {
        type: 'classInfo',
        localName: 'LegendURL',
        propertyInfos: [{
            name: 'width',
            typeInfo: 'String',
            attributeName: 'width',
            type: 'attribute'
          }, {
            name: 'height',
            typeInfo: 'String',
            attributeName: 'height',
            type: 'attribute'
          }, {
            type: 'element',
            name: 'format',
            elementName: 'Format',
            typeInfo: 'WMS_1_1_0.Format'
          }, {
            type: 'element',
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: 'WMS_1_1_0.OnlineResource'
          }]
      }, {
        type: 'classInfo',
        localName: 'StyleSheetURL',
        propertyInfos: [{
            type: 'element',
            name: 'format',
            elementName: 'Format',
            typeInfo: 'WMS_1_1_0.Format'
          }, {
            type: 'element',
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: 'WMS_1_1_0.OnlineResource'
          }]
      }, {
        type: 'classInfo',
        localName: 'StyleURL',
        propertyInfos: [{
            type: 'element',
            name: 'format',
            elementName: 'Format',
            typeInfo: 'WMS_1_1_0.Format'
          }, {
            type: 'element',
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: 'WMS_1_1_0.OnlineResource'
          }]
      }, {
        type: 'classInfo',
        localName: 'Keyword',
        propertyInfos: [{
            name: 'value',
            typeInfo: 'String',
            type: 'value'
          }]
      }, {
        type: 'classInfo',
        localName: 'ServiceExceptionReport',
        propertyInfos: [{
            name: 'version',
            typeInfo: 'String',
            attributeName: 'version',
            type: 'attribute'
          }, {
            type: 'element',
            name: 'serviceException',
            collection: true,
            elementName: 'ServiceException',
            typeInfo: 'WMS_1_1_0.ServiceException'
          }]
      }, {
        type: 'classInfo',
        localName: 'KeywordList',
        propertyInfos: [{
            type: 'element',
            name: 'keyword',
            collection: true,
            elementName: 'Keyword',
            typeInfo: 'WMS_1_1_0.Keyword'
          }]
      }, {
        type: 'classInfo',
        localName: 'ContactInformation',
        propertyInfos: [{
            type: 'element',
            name: 'contactPersonPrimary',
            elementName: 'ContactPersonPrimary',
            typeInfo: 'WMS_1_1_0.ContactPersonPrimary'
          }, {
            type: 'element',
            name: 'contactPosition',
            elementName: 'ContactPosition',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'contactAddress',
            elementName: 'ContactAddress',
            typeInfo: 'WMS_1_1_0.ContactAddress'
          }, {
            type: 'element',
            name: 'contactVoiceTelephone',
            elementName: 'ContactVoiceTelephone',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'contactFacsimileTelephone',
            elementName: 'ContactFacsimileTelephone',
            typeInfo: 'String'
          }, {
            type: 'element',
            name: 'contactElectronicMailAddress',
            elementName: 'ContactElectronicMailAddress',
            typeInfo: 'String'
          }]
      }, {
        type: 'classInfo',
        localName: 'AuthorityURL',
        propertyInfos: [{
            name: 'name',
            typeInfo: 'String',
            attributeName: 'name',
            type: 'attribute'
          }, {
            type: 'element',
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: 'WMS_1_1_0.OnlineResource'
          }]
      }, {
        type: 'classInfo',
        localName: 'Dimension',
        propertyInfos: [{
            name: 'name',
            typeInfo: 'String',
            attributeName: 'name',
            type: 'attribute'
          }, {
            name: 'units',
            typeInfo: 'String',
            attributeName: 'units',
            type: 'attribute'
          }, {
            name: 'unitSymbol',
            typeInfo: 'String',
            attributeName: 'unitSymbol',
            type: 'attribute'
          }]
      }, {
        type: 'classInfo',
        localName: 'DataURL',
        propertyInfos: [{
            type: 'element',
            name: 'format',
            elementName: 'Format',
            typeInfo: 'WMS_1_1_0.Format'
          }, {
            type: 'element',
            name: 'onlineResource',
            elementName: 'OnlineResource',
            typeInfo: 'WMS_1_1_0.OnlineResource'
          }]
      }],
    elementInfos: [{
        elementName: 'DCPType',
        typeInfo: 'WMS_1_1_0.DCPType'
      }, {
        elementName: 'HTTP',
        typeInfo: 'WMS_1_1_0.HTTP'
      }, {
        elementName: 'FeatureListURL',
        typeInfo: 'WMS_1_1_0.FeatureListURL'
      }, {
        elementName: 'Format',
        typeInfo: 'WMS_1_1_0.Format'
      }, {
        elementName: 'OnlineResource',
        typeInfo: 'WMS_1_1_0.OnlineResource'
      }, {
        elementName: 'WMT_MS_Capabilities',
        typeInfo: 'WMS_1_1_0.WMTMSCapabilities'
      }, {
        elementName: 'Service',
        typeInfo: 'WMS_1_1_0.Service'
      }, {
        elementName: 'Capability',
        typeInfo: 'WMS_1_1_0.Capability'
      }, {
        elementName: 'LogoURL',
        typeInfo: 'WMS_1_1_0.LogoURL'
      }, {
        elementName: 'ContactPersonPrimary',
        typeInfo: 'WMS_1_1_0.ContactPersonPrimary'
      }, {
        elementName: 'DescribeLayer',
        typeInfo: 'WMS_1_1_0.DescribeLayer'
      }, {
        elementName: 'Identifier',
        typeInfo: 'WMS_1_1_0.Identifier'
      }, {
        elementName: 'UserDefinedSymbolization',
        typeInfo: 'WMS_1_1_0.UserDefinedSymbolization'
      }, {
        elementName: 'ContactAddress',
        typeInfo: 'WMS_1_1_0.ContactAddress'
      }, {
        elementName: 'Request',
        typeInfo: 'WMS_1_1_0.Request'
      }, {
        elementName: 'Exception',
        typeInfo: 'WMS_1_1_0.Exception'
      }, {
        elementName: 'VendorSpecificCapabilities',
        typeInfo: 'WMS_1_1_0.VendorSpecificCapabilities'
      }, {
        elementName: 'Layer',
        typeInfo: 'WMS_1_1_0.Layer'
      }, {
        elementName: 'Get',
        typeInfo: 'WMS_1_1_0.Get'
      }, {
        elementName: 'Post',
        typeInfo: 'WMS_1_1_0.Post'
      }, {
        elementName: 'GetMap',
        typeInfo: 'WMS_1_1_0.GetMap'
      }, {
        elementName: 'ScaleHint',
        typeInfo: 'WMS_1_1_0.ScaleHint'
      }, {
        elementName: 'Attribution',
        typeInfo: 'WMS_1_1_0.Attribution'
      }, {
        elementName: 'GetFeatureInfo',
        typeInfo: 'WMS_1_1_0.GetFeatureInfo'
      }, {
        elementName: 'ServiceException',
        typeInfo: 'WMS_1_1_0.ServiceException'
      }, {
        elementName: 'MetadataURL',
        typeInfo: 'WMS_1_1_0.MetadataURL'
      }, {
        elementName: 'Extent',
        typeInfo: 'WMS_1_1_0.Extent'
      }, {
        elementName: 'LatLonBoundingBox',
        typeInfo: 'WMS_1_1_0.LatLonBoundingBox'
      }, {
        elementName: 'GetCapabilities',
        typeInfo: 'WMS_1_1_0.GetCapabilities'
      }, {
        elementName: 'BoundingBox',
        typeInfo: 'WMS_1_1_0.BoundingBox'
      }, {
        elementName: 'Style',
        typeInfo: 'WMS_1_1_0.Style'
      }, {
        elementName: 'LegendURL',
        typeInfo: 'WMS_1_1_0.LegendURL'
      }, {
        elementName: 'StyleSheetURL',
        typeInfo: 'WMS_1_1_0.StyleSheetURL'
      }, {
        elementName: 'StyleURL',
        typeInfo: 'WMS_1_1_0.StyleURL'
      }, {
        elementName: 'Keyword',
        typeInfo: 'WMS_1_1_0.Keyword'
      }, {
        elementName: 'ServiceExceptionReport',
        typeInfo: 'WMS_1_1_0.ServiceExceptionReport'
      }, {
        elementName: 'KeywordList',
        typeInfo: 'WMS_1_1_0.KeywordList'
      }, {
        elementName: 'ContactInformation',
        typeInfo: 'WMS_1_1_0.ContactInformation'
      }, {
        elementName: 'AuthorityURL',
        typeInfo: 'WMS_1_1_0.AuthorityURL'
      }, {
        elementName: 'Dimension',
        typeInfo: 'WMS_1_1_0.Dimension'
      }, {
        elementName: 'DataURL',
        typeInfo: 'WMS_1_1_0.DataURL'
      }]
  };
  return {
    WMS_1_1_0: WMS_1_1_0
  };
};
if (typeof define === 'function' && define.amd) {
  define([], WMS_1_1_0_Module_Factory);
}
else {
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.WMS_1_1_0 = WMS_1_1_0_Module_Factory().WMS_1_1_0;
  }
  else {
    var WMS_1_1_0 = WMS_1_1_0_Module_Factory().WMS_1_1_0;
  }
}