var WMS_1_0_0_Module_Factory = function () {
  var WMS_1_0_0 = {
    n: 'WMS_1_0_0',
    tis: [{
        ln: 'DCPType',
        ps: [{
            n: 'http',
            en: 'HTTP',
            ti: 'WMS_1_0_0.HTTP'
          }]
      }, {
        ln: 'HTTP',
        ps: [{
            n: 'getOrPost',
            col: true,
            etis: [{
                en: 'Get',
                ti: 'WMS_1_0_0.Get'
              }, {
                en: 'Post',
                ti: 'WMS_1_0_0.Post'
              }],
            t: 'es'
          }]
      }, {
        ln: 'WMTMSCapabilities',
        ps: [{
            n: 'version',
            t: 'a'
          }, {
            n: 'updateSequence',
            t: 'a'
          }, {
            n: 'service',
            en: 'Service',
            ti: 'WMS_1_0_0.Service'
          }, {
            n: 'capability',
            en: 'Capability',
            ti: 'WMS_1_0_0.Capability'
          }]
      }, {
        ln: 'Service',
        ps: [{
            n: 'name',
            en: 'Name'
          }, {
            n: 'title',
            en: 'Title'
          }, {
            n: '_abstract',
            en: 'Abstract'
          }, {
            n: 'keywords',
            en: 'Keywords'
          }, {
            n: 'onlineResource',
            en: 'OnlineResource'
          }, {
            n: 'fees',
            en: 'Fees'
          }, {
            n: 'accessConstraints',
            en: 'AccessConstraints'
          }]
      }, {
        ln: 'Capability',
        ps: [{
            n: 'request',
            en: 'Request',
            ti: 'WMS_1_0_0.Request'
          }, {
            n: 'exception',
            en: 'Exception',
            ti: 'WMS_1_0_0.Exception'
          }, {
            n: 'vendorSpecificCapabilities',
            en: 'VendorSpecificCapabilities',
            ti: 'WMS_1_0_0.VendorSpecificCapabilities'
          }, {
            n: 'layer',
            en: 'Layer',
            ti: 'WMS_1_0_0.Layer'
          }]
      }, {
        ln: 'SVG'
      }, {
        ln: 'WBMP'
      }, {
        ln: 'WebCGM'
      }, {
        ln: 'FeatureInfo',
        ps: [{
            n: 'format',
            en: 'Format',
            ti: 'WMS_1_0_0.Format'
          }, {
            n: 'dcpType',
            col: true,
            en: 'DCPType',
            ti: 'WMS_1_0_0.DCPType'
          }]
      }, {
        ln: 'Format',
        ps: [{
            n: 'gifOrJPEGOrPNGOrWebCGMOrSVGOrGML1OrGML2OrGML3OrWBMPOrWMSXMLOrMIMEOrINIMAGEOrTIFFOrGeoTIFFOrPPMOrBLANK',
            col: true,
            etis: [{
                en: 'GIF',
                ti: 'WMS_1_0_0.GIF'
              }, {
                en: 'JPEG',
                ti: 'WMS_1_0_0.JPEG'
              }, {
                en: 'PNG',
                ti: 'WMS_1_0_0.PNG'
              }, {
                en: 'WebCGM',
                ti: 'WMS_1_0_0.WebCGM'
              }, {
                en: 'SVG',
                ti: 'WMS_1_0_0.SVG'
              }, {
                en: 'GML.1',
                ti: 'WMS_1_0_0.GML1'
              }, {
                en: 'GML.2',
                ti: 'WMS_1_0_0.GML2'
              }, {
                en: 'GML.3',
                ti: 'WMS_1_0_0.GML3'
              }, {
                en: 'WBMP',
                ti: 'WMS_1_0_0.WBMP'
              }, {
                en: 'WMS_XML',
                ti: 'WMS_1_0_0.WMSXML'
              }, {
                en: 'MIME',
                ti: 'WMS_1_0_0.MIME'
              }, {
                en: 'INIMAGE',
                ti: 'WMS_1_0_0.INIMAGE'
              }, {
                en: 'TIFF',
                ti: 'WMS_1_0_0.TIFF'
              }, {
                en: 'GeoTIFF',
                ti: 'WMS_1_0_0.GeoTIFF'
              }, {
                en: 'PPM',
                ti: 'WMS_1_0_0.PPM'
              }, {
                en: 'BLANK',
                ti: 'WMS_1_0_0.BLANK'
              }],
            t: 'es'
          }]
      }, {
        ln: 'PNG'
      }, {
        ln: 'JPEG'
      }, {
        ln: 'PPM'
      }, {
        ln: 'MIME'
      }, {
        ln: 'LatLonBoundingBox',
        ps: [{
            n: 'minx',
            t: 'a'
          }, {
            n: 'miny',
            t: 'a'
          }, {
            n: 'maxx',
            t: 'a'
          }, {
            n: 'maxy',
            t: 'a'
          }]
      }, {
        ln: 'GeoTIFF'
      }, {
        ln: 'TIFF'
      }, {
        ln: 'GIF'
      }, {
        ln: 'GML1'
      }, {
        ln: 'GML2'
      }, {
        ln: 'GML3'
      }, {
        ln: 'WMSXML'
      }, {
        ln: 'INIMAGE'
      }, {
        ln: 'BLANK'
      }, {
        ln: 'BoundingBox',
        ps: [{
            n: 'srs',
            an: 'SRS',
            t: 'a'
          }, {
            n: 'minx',
            t: 'a'
          }, {
            n: 'miny',
            t: 'a'
          }, {
            n: 'maxx',
            t: 'a'
          }, {
            n: 'maxy',
            t: 'a'
          }]
      }, {
        ln: 'Style',
        ps: [{
            n: 'name',
            en: 'Name'
          }, {
            n: 'title',
            en: 'Title'
          }, {
            n: '_abstract',
            en: 'Abstract'
          }, {
            n: 'styleURL',
            en: 'StyleURL'
          }]
      }, {
        ln: 'Request',
        ps: [{
            n: 'mapOrCapabilitiesOrFeatureInfo',
            col: true,
            etis: [{
                en: 'Map',
                ti: 'WMS_1_0_0.Map'
              }, {
                en: 'Capabilities',
                ti: 'WMS_1_0_0.Capabilities'
              }, {
                en: 'FeatureInfo',
                ti: 'WMS_1_0_0.FeatureInfo'
              }],
            t: 'es'
          }]
      }, {
        ln: 'Exception',
        ps: [{
            n: 'format',
            en: 'Format',
            ti: 'WMS_1_0_0.Format'
          }]
      }, {
        ln: 'VendorSpecificCapabilities'
      }, {
        ln: 'Layer',
        ps: [{
            n: 'queryable',
            t: 'a'
          }, {
            n: 'name',
            en: 'Name'
          }, {
            n: 'title',
            en: 'Title'
          }, {
            n: '_abstract',
            en: 'Abstract'
          }, {
            n: 'keywords',
            en: 'Keywords'
          }, {
            n: 'srs',
            en: 'SRS'
          }, {
            n: 'latLonBoundingBox',
            en: 'LatLonBoundingBox',
            ti: 'WMS_1_0_0.LatLonBoundingBox'
          }, {
            n: 'boundingBox',
            col: true,
            en: 'BoundingBox',
            ti: 'WMS_1_0_0.BoundingBox'
          }, {
            n: 'dataURL',
            en: 'DataURL'
          }, {
            n: 'style',
            col: true,
            en: 'Style',
            ti: 'WMS_1_0_0.Style'
          }, {
            n: 'scaleHint',
            en: 'ScaleHint',
            ti: 'WMS_1_0_0.ScaleHint'
          }, {
            n: 'layer',
            col: true,
            en: 'Layer',
            ti: 'WMS_1_0_0.Layer'
          }]
      }, {
        ln: 'Post',
        ps: [{
            n: 'onlineResource',
            t: 'a'
          }]
      }, {
        ln: 'Map',
        ps: [{
            n: 'format',
            en: 'Format',
            ti: 'WMS_1_0_0.Format'
          }, {
            n: 'dcpType',
            col: true,
            en: 'DCPType',
            ti: 'WMS_1_0_0.DCPType'
          }]
      }, {
        ln: 'Capabilities',
        ps: [{
            n: 'format',
            en: 'Format',
            ti: 'WMS_1_0_0.Format'
          }, {
            n: 'dcpType',
            col: true,
            en: 'DCPType',
            ti: 'WMS_1_0_0.DCPType'
          }]
      }, {
        ln: 'Get',
        ps: [{
            n: 'onlineResource',
            t: 'a'
          }]
      }, {
        ln: 'ScaleHint',
        ps: [{
            n: 'min',
            t: 'a'
          }, {
            n: 'max',
            t: 'a'
          }]
      }],
    eis: [{
        en: 'DCPType',
        ti: 'WMS_1_0_0.DCPType'
      }, {
        en: 'HTTP',
        ti: 'WMS_1_0_0.HTTP'
      }, {
        en: 'WMT_MS_Capabilities',
        ti: 'WMS_1_0_0.WMTMSCapabilities'
      }, {
        en: 'Service',
        ti: 'WMS_1_0_0.Service'
      }, {
        en: 'Capability',
        ti: 'WMS_1_0_0.Capability'
      }, {
        en: 'SVG',
        ti: 'WMS_1_0_0.SVG'
      }, {
        en: 'WBMP',
        ti: 'WMS_1_0_0.WBMP'
      }, {
        en: 'WebCGM',
        ti: 'WMS_1_0_0.WebCGM'
      }, {
        en: 'FeatureInfo',
        ti: 'WMS_1_0_0.FeatureInfo'
      }, {
        en: 'Format',
        ti: 'WMS_1_0_0.Format'
      }, {
        en: 'PNG',
        ti: 'WMS_1_0_0.PNG'
      }, {
        en: 'JPEG',
        ti: 'WMS_1_0_0.JPEG'
      }, {
        en: 'PPM',
        ti: 'WMS_1_0_0.PPM'
      }, {
        en: 'MIME',
        ti: 'WMS_1_0_0.MIME'
      }, {
        en: 'LatLonBoundingBox',
        ti: 'WMS_1_0_0.LatLonBoundingBox'
      }, {
        en: 'GeoTIFF',
        ti: 'WMS_1_0_0.GeoTIFF'
      }, {
        en: 'TIFF',
        ti: 'WMS_1_0_0.TIFF'
      }, {
        en: 'GIF',
        ti: 'WMS_1_0_0.GIF'
      }, {
        en: 'GML.1',
        ti: 'WMS_1_0_0.GML1'
      }, {
        en: 'GML.2',
        ti: 'WMS_1_0_0.GML2'
      }, {
        en: 'GML.3',
        ti: 'WMS_1_0_0.GML3'
      }, {
        en: 'WMS_XML',
        ti: 'WMS_1_0_0.WMSXML'
      }, {
        en: 'INIMAGE',
        ti: 'WMS_1_0_0.INIMAGE'
      }, {
        en: 'BLANK',
        ti: 'WMS_1_0_0.BLANK'
      }, {
        en: 'BoundingBox',
        ti: 'WMS_1_0_0.BoundingBox'
      }, {
        en: 'Style',
        ti: 'WMS_1_0_0.Style'
      }, {
        en: 'Request',
        ti: 'WMS_1_0_0.Request'
      }, {
        en: 'Exception',
        ti: 'WMS_1_0_0.Exception'
      }, {
        en: 'VendorSpecificCapabilities',
        ti: 'WMS_1_0_0.VendorSpecificCapabilities'
      }, {
        en: 'Layer',
        ti: 'WMS_1_0_0.Layer'
      }, {
        en: 'Post',
        ti: 'WMS_1_0_0.Post'
      }, {
        en: 'Map',
        ti: 'WMS_1_0_0.Map'
      }, {
        en: 'Capabilities',
        ti: 'WMS_1_0_0.Capabilities'
      }, {
        en: 'Get',
        ti: 'WMS_1_0_0.Get'
      }, {
        en: 'ScaleHint',
        ti: 'WMS_1_0_0.ScaleHint'
      }]
  };
  return {
    WMS_1_0_0: WMS_1_0_0
  };
};
if (typeof define === 'function' && define.amd) {
  define([], WMS_1_0_0_Module_Factory);
}
else {
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.WMS_1_0_0 = WMS_1_0_0_Module_Factory().WMS_1_0_0;
  }
  else {
    var WMS_1_0_0 = WMS_1_0_0_Module_Factory().WMS_1_0_0;
  }
}