<DOCFLEX_TEMPLATE VER='1.19'>
CREATED='2005-10-08 05:00:00'
LAST_UPDATE='2014-07-05 20:02:57'
DESIGNER_TOOL='DocFlex SDK 1.x'
DESIGNER_LICENSE_TYPE='Filigris Works Team'
APP_ID='docflex-xml-wsdldoc'
APP_NAME='DocFlex/XML WSDLDoc'
APP_VER='1.0.b'
APP_AUTHOR='Copyright © 2014 Filigris Works, Leonid Rudy Softwareprodukte. All rights reserved.'
FEATURE_TYPE='pro'
TEMPLATE_TYPE='DocumentTemplate'
DSM_TYPE_ID='wsdldoc'
ROOT_ET='<ANY>'
<TEMPLATE_PARAMS>
	PARAM={
		param.name='integration';
		param.title='Integrations';
		param.title.style.bold='true';
		param.group='true';
	}
	PARAM={
		param.name='integration.XMLSpy';
		param.title='XMLSpy';
		param.type='boolean';
	}
	PARAM={
		param.name='integration.OxygenXML';
		param.title='Oxygen XML';
		param.type='boolean';
	}
</TEMPLATE_PARAMS>
<STYLES>
	CHAR_STYLE={
		style.name='Default Paragraph Font';
		style.id='cs1';
		style.default='true';
	}
	CHAR_STYLE={
		style.name='Hyperlink';
		style.id='cs2';
		text.decor.underline='true';
		text.color.foreground='#0000FF';
	}
	PAR_STYLE={
		style.name='Normal';
		style.id='s1';
		style.default='true';
	}
	CHAR_STYLE={
		style.name='Normal Smallest';
		style.id='cs3';
		text.font.name='Arial';
		text.font.size='8';
	}
</STYLES>
FMT={
	doc.lengthUnits='pt';
	doc.hlink.style.link='cs2';
}
<ROOT>
	<AREA_SEC>
		FMT={
			sec.outputStyle='table';
			text.style='cs3';
			text.option.renderNLs='false';
			table.sizing='Relative';
			table.cell.padding.both='2.5';
			table.bkgr.color='#E7EDF6';
			table.border.style='solid';
			table.border.color='#999999';
			table.page.keepTogether='true';
			table.option.borderStylesInHTML='true';
		}
		<AREA>
			<HR>
				FMT={
					rule.style='dashed';
					rule.color='#B2B2B2';
					par.margin.top='10';
					par.margin.bottom='5';
					par.page.keepWithNext='true';
				}
			</HR>
			<CTRL_GROUP>
				<CTRLS>
					<PANEL>
						FMT={
							ctrl.size.width='499.5';
							ctrl.size.height='59.3';
						}
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<TEXT_CTRL>
										TEXT='WSDL documentation generated with'
									</TEXT_CTRL>
									<DATA_CTRL>
										FORMULA='output.generator.name'
										<URL_HLINK>
											COND='output.generator.name == "DocFlex/XML RE"'
											TARGET_FRAME_EXPR='"_blank"'
											TARGET_FRAME_ALWAYS
											URL_EXPR='"http://www.filigris.com/docflex-xml/#docflex-xml-re"'
										</URL_HLINK>
										<URL_HLINK>
											TARGET_FRAME_EXPR='"_blank"'
											TARGET_FRAME_ALWAYS
											URL_EXPR='"http://www.filigris.com/docflex-xml/"'
										</URL_HLINK>
									</DATA_CTRL>
									<DATA_CTRL>
										FORMULA='output.generator.version'
									</DATA_CTRL>
									<TEXT_CTRL>
										TEXT='using'
									</TEXT_CTRL>
									<DATA_CTRL>
										FORMULA='template.appName'
										<URL_HLINK>
											TARGET_FRAME_EXPR='"_blank"'
											TARGET_FRAME_ALWAYS
											URL_EXPR='"http://www.filigris.com/docflex-xml/wsdldoc/"'
										</URL_HLINK>
									</DATA_CTRL>
									<DATA_CTRL>
										FORMULA='template.appVersion'
									</DATA_CTRL>
									<TEXT_CTRL>
										TEXT='template set'
									</TEXT_CTRL>
									<DELIMITER>
										FMT={
											txtfl.delimiter.type='text';
											txtfl.delimiter.text='. ';
										}
									</DELIMITER>
									<SS_CALL_CTRL>
										COND='checkVar ("has-diagrams")'
										SS_NAME='Integration Notice'
									</SS_CALL_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</PANEL>
				</CTRLS>
			</CTRL_GROUP>
		</AREA>
	</AREA_SEC>
</ROOT>
<STOCK_SECTIONS>
	<FOLDER>
		SS_NAME='Integration Notice'
		<BODY>
			<AREA_SEC>
				COND='getBooleanParam("integration.XMLSpy")'
				<AREA>
					<CTRL_GROUP>
						<CTRLS>
							<TEXT_CTRL>
								TEXT='All XSD diagrams generated by'
							</TEXT_CTRL>
							<TEXT_CTRL>
								TEXT='Altova XMLSpy'
								<URL_HLINK>
									TARGET_FRAME_EXPR='"_blank"'
									TARGET_FRAME_ALWAYS
									URL_EXPR='"http://www.altova.com/xmlspy"'
								</URL_HLINK>
							</TEXT_CTRL>
							<TEXT_CTRL>
								TEXT='via'
							</TEXT_CTRL>
							<TEXT_CTRL>
								TEXT='DocFlex/XML XMLSpy Integration'
								<URL_HLINK>
									TARGET_FRAME_EXPR='"_blank"'
									TARGET_FRAME_ALWAYS
									URL_EXPR='"http://www.filigris.com/docflex-xml/XMLSpy/"'
								</URL_HLINK>
							</TEXT_CTRL>
							<DELIMITER>
								FMT={
									txtfl.delimiter.type='none';
								}
							</DELIMITER>
							<TEXT_CTRL>
								TEXT='.'
							</TEXT_CTRL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
			<AREA_SEC>
				COND='getBooleanParam("integration.OxygenXML")'
				<AREA>
					<CTRL_GROUP>
						<CTRLS>
							<TEXT_CTRL>
								TEXT='All XSD diagrams generated by'
							</TEXT_CTRL>
							<TEXT_CTRL>
								TEXT='Oxygen XML Editor'
								<URL_HLINK>
									TARGET_FRAME_EXPR='"_blank"'
									TARGET_FRAME_ALWAYS
									URL_EXPR='"http://www.oxygenxml.com"'
								</URL_HLINK>
							</TEXT_CTRL>
							<TEXT_CTRL>
								TEXT='via'
							</TEXT_CTRL>
							<TEXT_CTRL>
								TEXT='DocFlex/XML OxygenXML Integration'
								<URL_HLINK>
									TARGET_FRAME_EXPR='"_blank"'
									TARGET_FRAME_ALWAYS
									URL_EXPR='"http://www.filigris.com/docflex-xml/OxygenXML/"'
								</URL_HLINK>
							</TEXT_CTRL>
							<DELIMITER>
								FMT={
									txtfl.delimiter.type='none';
								}
							</DELIMITER>
							<TEXT_CTRL>
								TEXT='.'
							</TEXT_CTRL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
		</BODY>
	</FOLDER>
</STOCK_SECTIONS>
CHECKSUM='2Mr+MFLS6MPJ8yVqiTLj?YoZv6slPrtEll3M0eEhX7s'
</DOCFLEX_TEMPLATE>